[.topic]
[#updating-access-entries]
= Update access entries

include::../../attributes.txt[]

You can update an access entry using the {aws-management-console} or the {aws} CLI.


[#access-update-console]
== {aws-management-console}
. Open the link:eks/home#/clusters[Amazon EKS console,type="console"].
. Choose the name of the cluster that you want to create an access entry in.
. Choose the *Access* tab.
. Choose the access entry that you want to update.
. Choose *Edit*.
. For *Username*, you can change the existing value.
. For *Groups*, you can remove existing group names or add new group names. If the following groups names exist, don't remove them:  *system:nodes* or  *system:bootstrappers*. Removing these groups can cause your cluster to function improperly. If you don't specify any group names and want to use Amazon EKS authorization, associate an  <<access-policies,access policy>> in a later step.
. For *Tags*, you can assign labels to the access entry. For example, to make it easier to find all resources with the same tag. You can also remove existing tags.
. Choose *Save changes*.
. If you want to associate an access policy to the entry, see <<access-policies>>.

[#access-update-cli]
== {aws} CLI
. Install the {aws} CLI, as described in  link:cli/latest/userguide/cli-chap-install.html[Installing, updating, and uninstalling the {aws} CLI,type="documentation"] in the {aws} Command Line Interface User Guide.
. To update an access entry
Replace [.replaceable]`my-cluster` with the name of your cluster, [.replaceable]`111122223333` with your {aws} account ID, and [.replaceable]`EKS-my-cluster-my-namespace-Viewers` with the name of an IAM role.
+
[source,bash,subs="verbatim,attributes"]
----
aws eks update-access-entry --cluster-name my-cluster --principal-arn {arn-aws}iam::111122223333:role/EKS-my-cluster-my-namespace-Viewers --kubernetes-groups Viewers
----
+
You can't use the `--kubernetes-groups` option if the type of the access entry is a value other than `STANDARD`. You also can't associate an access policy to an access entry with a type other than `STANDARD`. 


📝 https://github.com/search?q=repo%3Aawsdocs%2Famazon-eks-user-guide+%5B%23updating-access-entries%5D&type=code[Edit this page on GitHub]