include::../../attributes.txt[]

[.topic]
[#security-iam-service-with-iam]
= How Amazon EKS works with IAM
:info_titleabbrev: Amazon EKS and IAM

Before you use IAM to manage access to Amazon EKS, you should understand what IAM features are available to use with Amazon EKS. To get a high-level view of how Amazon EKS and other {aws} services work with IAM, see link:IAM/latest/UserGuide/reference_aws-services-that-work-with-iam.html[{aws} services that work with IAM,type="documentation"] in the _IAM User Guide_.

[.topiclist]
[[Topic List]]

[#security-iam-service-with-iam-id-based-policies]
== Amazon EKS identity-based policies

With IAM identity-based policies, you can specify allowed or denied actions and resources as well as the conditions under which actions are allowed or denied. Amazon EKS supports specific actions, resources, and condition keys. To learn about all of the elements that you use in a JSON policy, see link:IAM/latest/UserGuide/reference_policies_elements.html[IAM JSON policy elements reference,type="documentation"] in the _IAM User Guide_.

[#security-iam-service-with-iam-id-based-policies-actions]
=== Actions

Administrators can use {aws} JSON policies to specify who has access to what. That is, which *principal* can perform *actions* on what *resources*, and under what *conditions*.

The `Action` element of a JSON policy describes the actions that you can use to allow or deny access in a policy. Policy actions usually have the same name as the associated {aws} API operation. There are some exceptions, such as _permission-only actions_ that don't have a matching API operation. There are also some operations that require multiple actions in a policy. These additional actions are called _dependent actions_.

Include actions in a policy to grant permissions to perform the associated operation.

Policy actions in Amazon EKS use the following prefix before the action: `eks:`. For example, to grant someone permission to get descriptive information about an Amazon EKS cluster, you include the `DescribeCluster` action in their policy. Policy statements must include either an `Action` or `NotAction` element. 

To specify multiple actions in a single statement, separate them with commas as follows:

[source,json,subs="verbatim,attributes"]
----
"Action": ["eks:action1", "eks:action2"]
----

You can specify multiple actions using wildcards (*). For example, to specify all actions that begin with the word `Describe`, include the following action:

[source,json,subs="verbatim,attributes"]
----
"Action": "eks:Describe*"
----


To see a list of Amazon EKS actions, see link:service-authorization/latest/reference/list_amazonelastickubernetesservice.html#amazonelastickubernetesservice-actions-as-permissions[Actions defined by Amazon Elastic Kubernetes Service,type="documentation"] in the _Service Authorization Reference_.

[#security-iam-service-with-iam-id-based-policies-resources]
=== Resources

Administrators can use {aws} JSON policies to specify who has access to what. That is, which *principal* can perform *actions* on what *resources*, and under what *conditions*.

The `Resource` JSON policy element specifies the object or objects to which the action applies. Statements must include either a `Resource` or a `NotResource` element. As a best practice, specify a resource using its link:IAM/latest/UserGuide/reference-arns.html[Amazon Resource Name (ARN),type="documentation"]. You can do this for actions that support a specific resource type, known as _resource-level permissions_.

For actions that don't support resource-level permissions, such as listing operations, use a wildcard (*) to indicate that the statement applies to all resources.

[source]
----
"Resource": "*"
----

The Amazon EKS cluster resource has the following ARN.

[source,none,subs="verbatim,attributes"]
----
{arn-aws}eks:region-code:account-id:cluster/cluster-name
----

For more information about the format of ARNs, see link:general/latest/gr/aws-arns-and-namespaces.html[Amazon resource names (ARNs) and {aws} service namespaces,type="documentation"].

For example, to specify the cluster with the name [.replaceable]`my-cluster` in your statement, use the following ARN:

[source,json,subs="verbatim,attributes"]
----
"Resource": "{arn-aws}eks:region-code:111122223333:cluster/my-cluster"
----

To specify all clusters that belong to a specific account and {aws} Region, use the wildcard (*):

[source,json,subs="verbatim,attributes"]
----
"Resource": "{arn-aws}eks:region-code:111122223333:cluster/*"
----

Some Amazon EKS actions, such as those for creating resources, can't be performed on a specific resource. In those cases, you must use the wildcard (*).

[source,json,subs="verbatim,attributes"]
----
"Resource": "*"
----

To see a list of Amazon EKS resource types and their ARNs, see link:service-authorization/latest/reference/list_amazonelastickubernetesservice.html#amazonelastickubernetesservice-resources-for-iam-policies[Resources defined by Amazon Elastic Kubernetes Service,type="documentation"] in the _Service Authorization Reference_. To learn with which actions you can specify the ARN of each resource, see link:service-authorization/latest/reference/list_amazonelastickubernetesservice.html#amazonelastickubernetesservice-actions-as-permissions[Actions defined by Amazon Elastic Kubernetes Service,type="documentation"].

[#security-iam-service-with-iam-id-based-policies-conditionkeys]
=== Condition keys

Amazon EKS defines its own set of condition keys and also supports using some global condition keys. To see all {aws} global condition keys, see link:IAM/latest/UserGuide/reference_policies_condition-keys.html[{aws} Global Condition Context Keys,type="documentation"] in the _IAM User Guide_.

You can set condition keys when associating an OpenID Connect provider to your cluster. For more information, see <<oidc-identity-provider-iam-policy>>.

All Amazon EC2 actions support the `aws:RequestedRegion` and `ec2:Region` condition keys. For more information, see link:AWSEC2/latest/UserGuide/ExamplePolicies_EC2.html#iam-example-region[Example: Restricting Access to a Specific {aws} Region,type="documentation"]. 

For a list of Amazon EKS condition keys, see link:service-authorization/latest/reference/list_amazonelastickubernetesservice.html#amazonelastickubernetesservice-policy-keys[Conditions defined by Amazon Elastic Kubernetes Service,type="documentation"] in the _Service Authorization Reference_. To learn which actions and resources you can use a condition key with, see link:service-authorization/latest/reference/list_amazonelastickubernetesservice.html#amazonelastickubernetesservice-actions-as-permissions[Actions defined by Amazon Elastic Kubernetes Service,type="documentation"].

[#security-iam-service-with-iam-id-based-policies-examples]
=== Examples


To view examples of Amazon EKS identity-based policies, see <<security-iam-id-based-policy-examples>>.

When you create an Amazon EKS cluster, the link:IAM/latest/UserGuide/id_roles.html#iam-term-principal[IAM principal,type="documentation"] that creates the cluster is automatically granted `system:masters` permissions in the cluster's role-based access control (RBAC) configuration in the Amazon EKS control plane. This principal doesn't appear in any visible configuration, so make sure to keep track of which principal originally created the cluster. To grant additional IAM principals the ability to interact with your cluster, edit the `aws-auth ConfigMap` within Kubernetes and create a Kubernetes `rolebinding` or `clusterrolebinding` with the name of a `group` that you specify in the `aws-auth ConfigMap`.

For more information about working with the ConfigMap, see <<grant-k8s-access>>.

[#security-iam-service-with-iam-resource-based-policies]
== Amazon EKS resource-based policies

Amazon EKS does not support resource-based policies.

[#security-iam-service-with-iam-tags]
== Authorization based on Amazon EKS tags

You can attach tags to Amazon EKS resources or pass tags in a request to Amazon EKS. To control access based on tags, you provide tag information in the link:IAM/latest/UserGuide/reference_policies_elements_condition.html[condition element,type="documentation"] of a policy using the `aws:ResourceTag/[.replaceable]``key-name```, `aws:RequestTag/[.replaceable]``key-name```, or `aws:TagKeys` condition keys. For more information about tagging Amazon EKS resources, see <<eks-using-tags>>. For more information about which actions that you can use tags in condition keys with, see link:service-authorization/latest/reference/list_amazonelastickubernetesservice.html#amazonelastickubernetesservice-actions-as-permissions[Actions defined by Amazon EKS,type="documentation"] in the link:service-authorization/latest/reference/reference.html[Service Authorization Reference,type="documentation"].

[#security-iam-service-with-iam-roles]
== Amazon EKS IAM roles

An link:IAM/latest/UserGuide/id_roles.html[IAM role,type="documentation"] is an entity within your {aws} account that has specific permissions.

[#security-iam-service-with-iam-roles-tempcreds]
=== Using temporary credentials with Amazon EKS

You can use temporary credentials to sign in with federation, assume an IAM role, or to assume a cross-account role. You obtain temporary security credentials by calling {aws} STS API operations such as link:STS/latest/APIReference/API_AssumeRole.html[AssumeRole,type="documentation"] or link:STS/latest/APIReference/API_GetFederationToken.html[GetFederationToken,type="documentation"]. 

Amazon EKS supports using temporary credentials. 

[#security-iam-service-with-iam-roles-service-linked]
=== Service-linked roles

link:IAM/latest/UserGuide/id_roles.html#iam-term-service-linked-role[Service-linked roles,type="documentation"] allow {aws} services to access resources in other services to complete an action on your behalf. Service-linked roles appear in your IAM account and are owned by the service. An administrator can view but can't edit the permissions for service-linked roles.

Amazon EKS supports service-linked roles. For details about creating or managing Amazon EKS service-linked roles, see <<using-service-linked-roles>>.

[#security-iam-service-with-iam-roles-service]
=== Service roles

This feature allows a service to assume a link:IAM/latest/UserGuide/id_roles.html#iam-term-service-role[service role,type="documentation"] on your behalf. This role allows the service to access resources in other services to complete an action on your behalf. Service roles appear in your IAM account and are owned by the account. This means that an IAM administrator can change the permissions for this role. However, doing so might break the functionality of the service.

Amazon EKS supports service roles. For more information, see <<cluster-iam-role>> and <<create-node-role>>.

[#security-iam-service-with-iam-roles-choose]
=== Choosing an IAM role in Amazon EKS

When you create a cluster resource in Amazon EKS, you must choose a role to allow Amazon EKS to access several other {aws} resources on your behalf. If you have previously created a service role, then Amazon EKS provides you with a list of roles to choose from. It's important to choose a role that has the Amazon EKS managed policies attached to it. For more information, see <<check-service-role>> and <<check-worker-node-role>>.
