[.topic]
[[security-iam,security-iam.title]]
= Identity and access management for Amazon EKS
:info_titleabbrev: IAM Reference

include::../../attributes.txt[]

include::security-iam-service-with-iam.adoc[leveloffset=+1]

include::security-iam-id-based-policy-examples.adoc[leveloffset=+1]

include::using-service-linked-roles.adoc[leveloffset=+1]

include::pod-execution-role.adoc[leveloffset=+1]

include::connector-iam-role.adoc[leveloffset=+1]

include::security-iam-awsmanpol.adoc[leveloffset=+1]

include::security-iam-troubleshoot.adoc[leveloffset=+1]

include::cluster-iam-role.adoc[leveloffset=+1]

include::create-node-role.adoc[leveloffset=+1]

include::auto-cluster-iam-role.adoc[leveloffset=+1]

include::auto-create-node-role.adoc[leveloffset=+1]

[abstract]
--
How to authenticate requests and manage access your Amazon EKS resources.
--

{aws} Identity and Access Management (IAM) is an {aws} service that helps an administrator securely control access to {aws} resources. IAM administrators control who can be  _authenticated_ (signed in) and _authorized_ (have permissions) to use Amazon EKS resources. IAM is an {aws} service that you can use with no additional charge.

[[security-iam-audience,security-iam-audience.title]]
== Audience

How you use {aws} Identity and Access Management (IAM) differs, depending on the work that you do in Amazon EKS.

*Service user* – If you use the Amazon EKS service to do your job, then your administrator provides you with the credentials and permissions that you need. As you use more Amazon EKS features to do your work, you might need additional permissions. Understanding how access is managed can help you request the right permissions from your administrator. If you cannot access a feature in Amazon EKS, see <<security-iam-troubleshoot>>.

*Service administrator* – If you're in charge of Amazon EKS resources at your company, you probably have full access to Amazon EKS. It's your job to determine which Amazon EKS features and resources your service users should access. You must then submit requests to your IAM administrator to change the permissions of your service users. Review the information on this page to understand the basic concepts of IAM. To learn more about how your company can use IAM with Amazon EKS, see <<security-iam-service-with-iam>>.

*IAM administrator* – If you're an IAM administrator, you might want to learn details about how you can write policies to manage access to Amazon EKS. To view example Amazon EKS identity-based policies that you can use in IAM, see <<security-iam-id-based-policy-examples>>.

[[security-iam-authentication,security-iam-authentication.title]]
== Authenticating with identities

Authentication is how you sign in to {aws} using your identity credentials. You must be  _authenticated_ (signed in to {aws}) as the {aws} account root user, as an IAM user, or by assuming an IAM role.

You can sign in to {aws} as a federated identity by using credentials provided through an identity source. {aws} IAM Identity Center (IAM Identity Center) users, your company's single sign-on authentication, and your Google or Facebook credentials are examples of federated identities. When you sign in as a federated identity, your administrator previously set up identity federation using IAM roles. When you access {aws} by using federation, you are indirectly assuming a role.

Depending on the type of user you are, you can sign in to the {aws-management-console} or the {aws} access portal. For more information about signing in to {aws}, see link:signin/latest/userguide/how-to-sign-in.html[How to sign in to your {aws} account,type="documentation"] in the _{aws} Sign-In User Guide_.

If you access {aws} programmatically, {aws} provides a software development kit (SDK) and a command line interface (CLI) to cryptographically sign your requests by using your credentials. If you don't use {aws} tools, you must sign requests yourself. For more information about using the recommended method to sign requests yourself, see  link:IAM/latest/UserGuide/reference_aws-signing.html[Signing {aws} API requests,type="documentation"] in the _IAM User Guide_.

Regardless of the authentication method that you use, you might be required to provide additional security information. For example, {aws} recommends that you use multi-factor authentication (MFA) to increase the security of your account. To learn more, see link:singlesignon/latest/userguide/enable-mfa.html[Multi-factor authentication,type="documentation"] in the _{aws} IAM Identity Center User Guide_ and  link:IAM/latest/UserGuide/id_credentials_mfa.html[Using multi-factor authentication (MFA) in {aws},type="documentation"] in the _IAM User Guide_.

[[security-iam-authentication-rootuser,security-iam-authentication-rootuser.title]]
=== {aws} account root user

When you create an {aws} account, you begin with one sign-in identity that has complete access to all {aws} services and resources in the account. This identity is called the {aws} account  _root user_ and is accessed by signing in with the email address and password that you used to create the account. We strongly recommend that you don't use the root user for your everyday tasks. Safeguard your root user credentials and use them to perform the tasks that only the root user can perform. For the complete list of tasks that require you to sign in as the root user, see  link:IAM/latest/UserGuide/id_root-user.html#root-user-tasks[Tasks that require root user credentials,type="documentation"] in the _IAM User Guide_. 

[[security-iam-authentication-iamuser,security-iam-authentication-iamuser.title]]
=== IAM users and groups

An  _ link:IAM/latest/UserGuide/id_users.html[IAM user,type="documentation"]_ is an identity within your {aws} account that has specific permissions for a single person or application. Where possible, we recommend relying on temporary credentials instead of creating IAM users who have long-term credentials such as passwords and access keys. However, if you have specific use cases that require long-term credentials with IAM users, we recommend that you rotate access keys. For more information, see  link:IAM/latest/UserGuide/best-practices.html#rotate-credentials[Rotate access keys regularly for use cases that require long-term credentials,type="documentation"] in the _IAM User Guide_.

An  link:IAM/latest/UserGuide/id_groups.html[IAM group,type="documentation"] is an identity that specifies a collection of IAM users. You can't sign in as a group. You can use groups to specify permissions for multiple users at a time. Groups make permissions easier to manage for large sets of users. For example, you could have a group named _IAMAdmins_ and give that group permissions to administer IAM resources.

Users are different from roles. A user is uniquely associated with one person or application, but a role is intended to be assumable by anyone who needs it. Users have permanent long-term credentials, but roles provide temporary credentials. To learn more, see  link:IAM/latest/UserGuide/id.html#id_which-to-choose[When to create an IAM user (instead of a role),type="documentation"] in the _IAM User Guide_.

[[security-iam-authentication-iamrole,security-iam-authentication-iamrole.title]]
=== IAM roles

An  _ link:IAM/latest/UserGuide/id_roles.html[IAM role,type="documentation"]_ is an identity within your {aws} account that has specific permissions. It is similar to an IAM user, but is not associated with a specific person. You can temporarily assume an IAM role in the {aws-management-console} by  link:IAM/latest/UserGuide/id_roles_use_switch-role-console.html[switching roles,type="documentation"]. You can assume a role by calling an {aws} CLI or {aws} API operation or by using a custom URL. For more information about methods for using roles, see  link:IAM/latest/UserGuide/id_roles_use.html[Using IAM roles,type="documentation"] in the _IAM User Guide_.

IAM roles with temporary credentials are useful in the following situations:



* *Federated user access* – To assign permissions to a federated identity, you create a role and define permissions for the role. When a federated identity authenticates, the identity is associated with the role and is granted the permissions that are defined by the role. For information about roles for federation, see  link:IAM/latest/UserGuide/id_roles_create_for-idp.html[Creating a role for a third-party Identity Provider,type="documentation"] in the _IAM User Guide_. If you use IAM Identity Center, you configure a permission set. To control what your identities can access after they authenticate, IAM Identity Center correlates the permission set to a role in IAM. For information about permissions sets, see link:singlesignon/latest/userguide/permissionsetsconcept.html[Permission sets,type="documentation"] in the _{aws} IAM Identity Center User Guide_.
* *Temporary IAM user permissions* – An IAM user or role can assume an IAM role to temporarily take on different permissions for a specific task.
* *Cross-account access* – You can use an IAM role to allow someone (a trusted principal) in a different account to access resources in your account. Roles are the primary way to grant cross-account access. However, with some {aws} services, you can attach a policy directly to a resource (instead of using a role as a proxy). To learn the difference between roles and resource-based policies for cross-account access, see  link:IAM/latest/UserGuide/access_policies-cross-account-resource-access.html[Cross account resource access in IAM,type="documentation"] in the _IAM User Guide_.
* *Cross-service access* – Some {aws} services use features in other {aws} services. For example, when you make a call in a service, it's common for that service to run applications in Amazon EC2 or store objects in Amazon S3. A service might do this using the calling principal's permissions, using a service role, or using a service-linked role. 
+
** *Forward access sessions (FAS)* – When you use an IAM user or role to perform actions in {aws}, you are considered a principal. When you use some services, you might perform an action that then initiates another action in a different service. FAS uses the permissions of the principal calling an {aws} service, combined with the requesting {aws} service to make requests to downstream services. FAS requests are only made when a service receives a request that requires interactions with other {aws} services or resources to complete. In this case, you must have permissions to perform both actions. For policy details when making FAS requests, see  link:IAM/latest/UserGuide/access_forward_access_sessions.html[Forward access sessions,type="documentation"]. 
** *Service role* – A service role is an  link:IAM/latest/UserGuide/id_roles.html[IAM role,type="documentation"] that a service assumes to perform actions on your behalf. An IAM administrator can create, modify, and delete a service role from within IAM. For more information, see  link:IAM/latest/UserGuide/id_roles_create_for-service.html[Creating a role to delegate permissions to an {aws} service,type="documentation"] in the _IAM User Guide_. 
** *Service-linked role* – A service-linked role is a type of service role that is linked to an {aws} service. The service can assume the role to perform an action on your behalf. Service-linked roles appear in your {aws} account and are owned by the service. An IAM administrator can view, but not edit the permissions for service-linked roles. 
* *Applications running on Amazon EC2* – You can use an IAM role to manage temporary credentials for applications that are running on an EC2 instance and making {aws} CLI or {aws} API requests. This is preferable to storing access keys within the EC2 instance. To assign an {aws} role to an EC2 instance and make it available to all of its applications, you create an instance profile that is attached to the instance. An instance profile contains the role and enables programs that are running on the EC2 instance to get temporary credentials. For more information, see  link:IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html[Using an IAM role to grant permissions to applications running on Amazon EC2 instances,type="documentation"] in the _IAM User Guide_. 

To learn whether to use IAM roles or IAM users, see   link:IAM/latest/UserGuide/id.html#id_which-to-choose_role[When to create an IAM role (instead of a user),type="documentation"] in the _IAM User Guide_.

[[security-iam-access-manage,security-iam-access-manage.title]]
== Managing access using policies

You control access in {aws} by creating policies and attaching them to {aws} identities or resources. A policy is an object in {aws} that, when associated with an identity or resource, defines their permissions. {aws} evaluates these policies when a principal (user, root user, or role session) makes a request. Permissions in the policies determine whether the request is allowed or denied. Most policies are stored in {aws} as JSON documents. For more information about the structure and contents of JSON policy documents, see   link:IAM/latest/UserGuide/access_policies.html#access_policies-json[Overview of JSON policies,type="documentation"] in the _IAM User Guide_.

Administrators can use {aws} JSON policies to specify who has access to what. That is, which *principal* can perform *actions* on what *resources*, and under what *conditions*.

By default, users and roles have no permissions. To grant users permission to perform actions on the resources that they need, an IAM administrator can create IAM policies. The administrator can then add the IAM policies to roles, and users can assume the roles.

IAM policies define permissions for an action regardless of the method that you use to perform the operation. For example, suppose that you have a policy that allows the `iam:GetRole` action. A user with that policy can get role information from the {aws-management-console}, the {aws} CLI, or the {aws} API.

[[security-iam-access-manage-id-based-policies,security-iam-access-manage-id-based-policies.title]]
=== Identity-based policies

Identity-based policies are JSON permissions policy documents that you can attach to an identity, such as an IAM user, group of users, or role. These policies control what actions users and roles can perform, on which resources, and under what conditions. To learn how to create an identity-based policy, see   link:IAM/latest/UserGuide/access_policies_create.html[Creating IAM policies,type="documentation"] in the _IAM User Guide_.

Identity-based policies can be further categorized as _inline policies_ or _managed policies_. Inline policies are embedded directly into a single user, group, or role. Managed policies are standalone policies that you can attach to multiple users, groups, and roles in your {aws} account. Managed policies include {aws} managed policies and customer managed policies. To learn how to choose between a managed policy or an inline policy, see  link:IAM/latest/UserGuide/access_policies_managed-vs-inline.html#choosing-managed-or-inline[Choosing between managed policies and inline policies,type="documentation"] in the _IAM User Guide_.

[[security-iam-access-manage-resource-based-policies,security-iam-access-manage-resource-based-policies.title]]
=== Resource-based policies

Resource-based policies are JSON policy documents that you attach to a resource. Examples of resource-based policies are IAM  _role trust policies_ and Amazon S3 _bucket policies_. In services that support resource-based policies, service administrators can use them to control access to a specific resource. For the resource where the policy is attached, the policy defines what actions a specified principal can perform on that resource and under what conditions. You must  link:IAM/latest/UserGuide/reference_policies_elements_principal.html[specify a principal,type="documentation"] in a resource-based policy. Principals can include accounts, users, roles, federated users, or {aws} services.

Resource-based policies are inline policies that are located in that service. You can't use {aws} managed policies from IAM in a resource-based policy.

[[security-iam-access-manage-acl,security-iam-access-manage-acl.title]]
=== Access control lists (ACLs)

Access control lists (ACLs) control which principals (account members, users, or roles) have permissions to access a resource. ACLs are similar to resource-based policies, although they do not use the JSON policy document format.

Amazon S3, {aws} WAF, and Amazon VPC are examples of services that support ACLs. To learn more about ACLs, see link:AmazonS3/latest/userguide/acl-overview.html[Access control list (ACL) overview,type="documentation"] in the _Amazon Simple Storage Service Developer Guide_.

[[security-iam-access-manage-other-policies,security-iam-access-manage-other-policies.title]]
=== Other policy types

{aws} supports additional, less-common policy types. These policy types can set the maximum permissions granted to you by the more common policy types.  



* *Permissions boundaries* – A permissions boundary is an advanced feature in which you set the maximum permissions that an identity-based policy can grant to an IAM entity (IAM user or role). You can set a permissions boundary for an entity. The resulting permissions are the intersection of an entity's identity-based policies and its permissions boundaries. Resource-based policies that specify the user or role in the `Principal` field are not limited by the permissions boundary. An explicit deny in any of these policies overrides the allow. For more information about permissions boundaries, see  link:IAM/latest/UserGuide/access_policies_boundaries.html[Permissions boundaries for IAM entities,type="documentation"] in the _IAM User Guide_.
* *Service control policies (SCPs)* – SCPs are JSON policies that specify the maximum permissions for an organization or organizational unit (OU) in {aws} Organizations. {aws} Organizations is a service for grouping and centrally managing multiple {aws} accounts that your business owns. If you enable all features in an organization, then you can apply service control policies (SCPs) to any or all of your accounts. The SCP limits permissions for entities in member accounts, including each {aws} account root user. For more information about Organizations and SCPs, see  link:organizations/latest/userguide/orgs_manage_policies_scps.html[Service control policies,type="documentation"] in the _{aws} Organizations User Guide_.
* *Session policies* – Session policies are advanced policies that you pass as a parameter when you programmatically create a temporary session for a role or federated user. The resulting session's permissions are the intersection of the user or role's identity-based policies and the session policies. Permissions can also come from a resource-based policy. An explicit deny in any of these policies overrides the allow. For more information, see  link:IAM/latest/UserGuide/access_policies.html#policies_session[Session policies,type="documentation"] in the _IAM User Guide_. 


[[security-iam-access-manage-multiple-policies,security-iam-access-manage-multiple-policies.title]]
=== Multiple policy types

When multiple types of policies apply to a request, the resulting permissions are more complicated to understand. To learn how {aws} determines whether to allow a request when multiple policy types are involved, see   link:IAM/latest/UserGuide/reference_policies_evaluation-logic.html[Policy evaluation logic,type="documentation"] in the _IAM User Guide_.


📝 https://github.com/search?q=repo:awsdocs/amazon-eks-user-guide+&#91;&#91;security-iam,&type=code[Edit this page on GitHub]