[.topic]
[#using-service-linked-roles-eks-outpost]
= Using roles for Amazon EKS local clusters on Outpost
:info_titleabbrev: Local cluster role

include::../../attributes.txt[]

[abstract]
--
How to use service-linked roles to give Amazon EKS access to resources in your {aws} account.
--

Amazon Elastic Kubernetes Service uses {aws} Identity and Access Management (IAM) link:IAM/latest/UserGuide/id_roles.html#iam-term-service-linked-role[service-linked roles,type="documentation"]. A service-linked role is a unique type of IAM role that is linked directly to Amazon EKS. Service-linked roles are predefined by Amazon EKS and include all the permissions that the service requires to call other {aws} services on your behalf. 

A service-linked role makes setting up Amazon EKS easier because you don't have to manually add the necessary permissions. Amazon EKS defines the permissions of its service-linked roles, and unless defined otherwise, only Amazon EKS can assume its roles. The defined permissions include the trust policy and the permissions policy, and that permissions policy cannot be attached to any other IAM entity.

You can delete a service-linked role only after first deleting their related resources. This protects your Amazon EKS resources because you can't inadvertently remove permission to access the resources.

For information about other services that support service-linked roles, see  link:IAM/latest/UserGuide/reference_aws-services-that-work-with-iam.html[{aws} services that work with IAM,type="documentation"] and look for the services that have *Yes* in the *Service-linked role* column. Choose a *Yes* with a link to view the service-linked role documentation for that service.

[#service-linked-role-permissions]
== Service-linked role permissions for Amazon EKS

Amazon EKS uses the service-linked role named `AWSServiceRoleForAmazonEKSLocalOutpost`. The role allows Amazon EKS to manage local clusters in your account. The attached policies allow the role to manage the following resources: network interfaces, security groups, logs, and Amazon EC2 instances.

[NOTE]
====

The `AWSServiceRoleForAmazonEKSLocalOutpost` service-linked role is distinct from the role required for cluster creation. For more information, see <<cluster-iam-role>>.

====

The `AWSServiceRoleForAmazonEKSLocalOutpost` service-linked role trusts the following services to assume the role:



* `outposts.eks-local.amazonaws.com`

The role permissions policy allows Amazon EKS to complete the following actions on the specified resources:



* link:aws-managed-policy/latest/reference/AmazonEKSServiceRolePolicy.html[AmazonEKSServiceRolePolicy,type="documentation"]

You must configure permissions to allow an IAM entity (such as a user, group, or role) to create, edit, or delete a service-linked role. For more information, see   link:IAM/latest/UserGuide/using-service-linked-roles.html#service-linked-role-permissions[Service-linked role permissions,type="documentation"] in the _IAM User Guide_.

[#create-service-linked-role-eks-outpost]
== Creating a service-linked role for Amazon EKS

You don't need to manually create a service-linked role. When you create a cluster in the {aws-management-console}, the {aws} CLI, or the {aws} API, Amazon EKS creates the service-linked role for you.  

If you delete this service-linked role, and then need to create it again, you can use the same process to recreate the role in your account. When you create a cluster, Amazon EKS creates the service-linked role for you again. 

[#edit-service-linked-role-eks-outpost]
== Editing a service-linked role for Amazon EKS

Amazon EKS does not allow you to edit the `AWSServiceRoleForAmazonEKSLocalOutpost` service-linked role. After you create a service-linked role, you can't change the name of the role because various entities might reference the role. However, you can edit the description of the role using IAM. For more information, see  link:IAM/latest/UserGuide/using-service-linked-roles.html#edit-service-linked-role[Editing a service-linked role,type="documentation"] in the _IAM User Guide_.

[#delete-service-linked-role-eks-outpost]
== Deleting a service-linked role for Amazon EKS

If you no longer need to use a feature or service that requires a service-linked role, we recommend that you delete that role. That way you don't have an unused entity that is not actively monitored or maintained. However, you must clean up your service-linked role before you can manually delete it.

[#service-linked-role-review-before-delete-eks-outpost]
=== Cleaning up a service-linked role

Before you can use IAM to delete a service-linked role, you must first delete any resources used by the role.

[NOTE]
====

If the Amazon EKS service is using the role when you try to delete the resources, then the deletion might fail. If that happens, wait for a few minutes and try the operation again.

====
. Open the link:eks/home#/clusters[Amazon EKS console,type="console"].
. In the left navigation pane, choose Amazon EKS *Clusters*.
. If your cluster has any node groups or Fargate profiles, you must delete them before you can delete the cluster. For more information, see <<delete-managed-node-group>> and <<delete-fargate-profile>>.
. On the *Clusters* page, choose the cluster that you want to delete and choose  *Delete*.
. Type the name of the cluster in the deletion confirmation window, and then choose *Delete*.
. Repeat this procedure for any other clusters in your account. Wait for all of the delete operations to finish.


[#slr-manual-delete-eks-outpost]
=== Manually delete the service-linked role

Use the IAM console, the {aws} CLI, or the {aws} API to delete the `AWSServiceRoleForAmazonEKSLocalOutpost` service-linked role. For more information, see  link:IAM/latest/UserGuide/using-service-linked-roles.html#delete-service-linked-role[Deleting a service-linked role,type="documentation"] in the _IAM User Guide_.

[#slr-regions-eks-connector]
== Supported regions for Amazon EKS service-linked roles

Amazon EKS supports using service-linked roles in all of the regions where the service is available. For more information, see link:general/latest/gr/eks.html[Amazon EKS endpoints and quotas,type="documentation"].


📝 https://github.com/search?q=repo%3Aawsdocs%2Famazon-eks-user-guide+%5B%23using-service-linked-roles-eks-outpost%5D&type=code[Edit this page on GitHub]