include::../../attributes.txt[]

[.topic]
[#using-service-linked-roles-eks-nodegroups]
= Using roles for Amazon EKS node groups
:info_titleabbrev: Node groups role

[abstract]
--
How to use service-linked roles to give Amazon EKS access to resources in your {aws} account.
--

Amazon EKS uses {aws} Identity and Access Management (IAM) link:IAM/latest/UserGuide/id_roles.html#iam-term-service-linked-role[service-linked roles,type="documentation"]. A service-linked role is a unique type of IAM role that is linked directly to Amazon EKS. Service-linked roles are predefined by Amazon EKS and include all the permissions that the service requires to call other {aws} services on your behalf. 

A service-linked role makes setting up Amazon EKS easier because you don't have to manually add the necessary permissions. Amazon EKS defines the permissions of its service-linked roles, and unless defined otherwise, only Amazon EKS can assume its roles. The defined permissions include the trust policy and the permissions policy, and that permissions policy cannot be attached to any other IAM entity.

You can delete a service-linked role only after first deleting their related resources. This protects your Amazon EKS resources because you can't inadvertently remove permission to access the resources.

For information about other services that support service-linked roles, see link:IAM/latest/UserGuide/reference_aws-services-that-work-with-iam.html[{aws} services that work with IAM,type="documentation"] and look for the services that have *Yes* in the *Service-linked role* column. Choose a *Yes* with a link to view the service-linked role documentation for that service.

[#service-linked-role-permissions-eks-nodegroups]
== Service-linked role permissions for Amazon EKS

Amazon EKS uses the service-linked role named `AWSServiceRoleForAmazonEKSNodegroup`. The role allows Amazon EKS to manage node groups in your account. The attached `AWSServiceRoleForAmazonEKSNodegroup` policy allows the role to manage the following resources: Auto Scaling groups, security groups, launch templates, and IAM instance profiles. For more information, see <<security-iam-awsmanpol-awsserviceroleforamazoneksnodegroup>>.

The `AWSServiceRoleForAmazonEKSNodegroup` service-linked role trusts the following services to assume the role:

* `eks-nodegroup.amazonaws.com`

The role permissions policy allows Amazon EKS to complete the following actions on the specified resources:

* link:aws-managed-policy/latest/reference/AWSServiceRoleForAmazonEKSNodegroup.html[AWSServiceRoleForAmazonEKSNodegroup,type="documentation"]

You must configure permissions to allow an IAM entity (such as a user, group, or role) to create, edit, or delete a service-linked role. For more information, see link:IAM/latest/UserGuide/using-service-linked-roles.html#service-linked-role-permissions[Service-linked role permissions,type="documentation"] in the _IAM User Guide_.

[#create-service-linked-role-eks-nodegroups]
== Creating a service-linked role for Amazon EKS

You don't need to manually create a service-linked role. When you CreateNodegroup in the {aws-management-console}, the {aws} CLI, or the {aws} API, Amazon EKS creates the service-linked role for you.  

[IMPORTANT]
====

This service-linked role can appear in your account if you completed an action in another service that uses the features supported by this role. If you were using the Amazon EKS service before January 1, 2017, when it began supporting service-linked roles, then Amazon EKS created the AWSServiceRoleForAmazonEKSNodegroup role in your account. To learn more, see link:IAM/latest/UserGuide/troubleshoot_roles.html#troubleshoot_roles_new-role-appeared[A new role appeared in my IAM account,type="documentation"].

====

[#create-service-linked-role-service-api-eks-nodegroups]
=== Creating a service-linked role in Amazon EKS ({aws} API)

You don't need to manually create a service-linked role. When you create a managed node group in the {aws-management-console}, the {aws} CLI, or the {aws} API, Amazon EKS creates the service-linked role for you.  

If you delete this service-linked role, and then need to create it again, you can use the same process to recreate the role in your account. When you create another managed node group, Amazon EKS creates the service-linked role for you again.  

[#edit-service-linked-role-eks-nodegroups]
== Editing a service-linked role for Amazon EKS

Amazon EKS does not allow you to edit the `AWSServiceRoleForAmazonEKSNodegroup` service-linked role. After you create a service-linked role, you cannot change the name of the role because various entities might reference the role. However, you can edit the description of the role using IAM. For more information, see link:IAM/latest/UserGuide/using-service-linked-roles.html#edit-service-linked-role[Editing a service-linked role,type="documentation"] in the _IAM User Guide_.

[#delete-service-linked-role-eks-nodegroups]
== Deleting a service-linked role for Amazon EKS

If you no longer need to use a feature or service that requires a service-linked role, we recommend that you delete that role. That way you don't have an unused entity that is not actively monitored or maintained. However, you must clean up your service-linked role before you can manually delete it.

[#service-linked-role-review-before-delete-eks-nodegroups]
=== Cleaning up a service-linked role

Before you can use IAM to delete a service-linked role, you must first delete any resources used by the role.

[NOTE]
====

If the Amazon EKS service is using the role when you try to delete the resources, then the deletion might fail. If that happens, wait for a few minutes and try the operation again.

====
. Open the link:eks/home#/clusters[Amazon EKS console,type="console"].
. In the left navigation pane, choose *Clusters*.
. Select the *Compute* tab.
. In the *Node groups* section, choose the node group to delete.
. Type the name of the node group in the deletion confirmation window, and then choose *Delete*.
. Repeat this procedure for any other node groups in the cluster. Wait for all of the delete operations to finish.


[#slr-manual-delete-eks-nodegroups]
=== Manually delete the service-linked role

Use the IAM console, the {aws} CLI, or the {aws} API to delete the `AWSServiceRoleForAmazonEKSNodegroup` service-linked role. For more information, see link:IAM/latest/UserGuide/using-service-linked-roles.html#delete-service-linked-role[Deleting a service-linked role,type="documentation"] in the _IAM User Guide_.

[#slr-regions-eks-nodegroups]
== Supported regions for Amazon EKS service-linked roles

Amazon EKS supports using service-linked roles in all of the regions where the service is available. For more information, see link:general/latest/gr/eks.html[Amazon EKS endpoints and quotas,type="documentation"].