include::../attributes.txt[]

[.topic]
[#bottlerocket-fips-amis]
= Make your worker nodes FIPS ready with Bottlerocket FIPS AMIs
:info_titleabbrev: Bottlerocket FIPS AMIs

[abstract]
--
Bottlerocket makes it easier to adhere to FIPS by offering AMIs with a FIPS kernel.
--

The Federal Information Processing Standard (FIPS) Publication 140-3 is a United States and Canadian government standard that specifies the security requirements for cryptographic modules that protect sensitive information. Bottlerocket makes it easier to adhere to FIPS by offering AMIs with a FIPS kernel.

These AMIs are preconfigured to use FIPS 140-3 validated cryptographic modules. This includes the Amazon Linux 2023 Kernel Crypto API Cryptographic Module and the {aws}-LC Cryptographic Module.

Using Bottlerocket FIPS AMIs makes your worker nodes "FIPS ready" but not automatically "FIPS-compliant". For more information, see link:compliance/fips/[Federal Information Processing Standard (FIPS) 140-3,type="marketing"].

== Considerations

* If your cluster uses isolated subnets, the Amazon ECR FIPS endpoint may not be accessible. This can cause the node bootstrap to fail. Make sure that your network configuration allows access to the necessary FIPS endpoints. For more information, see link:vpc/latest/privatelink/use-resource-endpoint.html[Access a resource through a resource VPC endpoint,type="documentation"] in the _{aws} PrivateLink Guide_.
* If your cluster uses a subnet with <<vpc-interface-endpoints,PrivateLink>>, image pulls will fail because Amazon ECR FIPS endpoints are not available through PrivateLink.

== Create a managed node group with a Bottlerocket FIPS AMI

The Bottlerocket FIPS AMI comes in two variants to support your workloads:

* `BOTTLEROCKET_x86_64_FIPS`
* `BOTTLEROCKET_ARM_64_FIPS`

To create a managed node group with a Bottlerocket FIPS AMI, choose the applicable AMI type during the creation process. For more information, see <<create-managed-node-group>>.

For more information on selecting FIPS-enabled variants, see <<retrieve-ami-id-bottlerocket>>. 

== Disable the FIPS endpoint for non-supported {aws} Regions

Bottlerocket FIPS AMIs are supported directly in the United States, including {aws} GovCloud (US) Regions. For {aws} Regions where the AMIs are available but not supported directly, you can still use the AMIs by creating a managed node group with a launch template.

The Bottlerocket FIPS AMI relies on the Amazon ECR FIPS endpoint during bootstrap, which are not generally available outside of the United States. To use the AMI for its FIPS kernel in {aws} Regions that don't have the Amazon ECR FIPS endpoint available, do these steps to disable the FIPS endpoint:

. Create a new configuration file with the following content or incorporate the content into your existing configuration file.

[source,bash,subs="verbatim,attributes"]
----
[default]
use_fips_endpoint=false
----

. Encode the file content as Base64 format.
. In your launch template's `UserData`, add the following encoded string using TOML format:

[source,bash,subs="verbatim,attributes"]
----
[settings.aws]
config = "<your-base64-encoded-string>"
----

For other settings, see Bottlerocket's link:https://github.com/bottlerocket-os/bottlerocket?tab=readme-ov-file#description-of-settings[Description of settings] on GitHub.

Here is an example of `UserData` in a launch template:

[source,bash,subs="verbatim,attributes"]
----
[settings]
motd = "Hello from eksctl!"
[settings.aws]
config = "W2RlZmF1bHRdCnVzZV9maXBzX2VuZHBvaW50PWZhbHNlCg==" # Base64-encoded string.
[settings.kubernetes]
api-server = "<api-server-endpoint>"
cluster-certificate = "<cluster-certificate-authority>"
cluster-name = "<cluster-name>"
...<other-settings>
----

For more information on creating a launch template with user data, see <<launch-templates>>.
