include::../attributes.txt[]

[.topic]
[#eks-ami-deprecation-faqs]
= Guide to EKS AL2 & AL2-Accelerated AMIs transition features
:info_titleabbrev: AL2 AMI deprecation

[abstract]
--
This document outlines the End of Support (EOS) information for Amazon EKS AL2-optimized and AL2-accelerated AMIs.
--

{aws} will end support for EKS AL2-optimized and AL2-accelerated AMIs, effective November 26, 2025. While you can continue using EKS AL2 AMIs after the end-of-support (EOS) date (November 26, 2025), EKS will no longer release any new Kubernetes versions or updates to AL2 AMIs, including minor releases, patches, and bug fixes after this date. We recommend upgrading to Amazon Linux 2023 (AL2023) or Bottlerocket AMIs:

* AL2023 enables a secure-by-default approach with preconfigured security policies, SELinux in permissive mode, IMDSv2-only mode enabled by default, optimized boot times, and improved package management for enhanced security and performance, well-suited for infrastructure requiring significant customizations like direct OS-level access or extensive node changes.
* Bottlerocket enables enhanced security, faster boot times, and a smaller attack surface for improved efficiency with its purpose-built, container-optimized design, well-suited for container-native approaches with minimal node customizations.

Alternatively, you can <<eks-ami-build-scripts>> until the EOS date (November 26, 2025), or build a custom AMI with an Amazon Linux 2 base instance until the Amazon Linux 2 EOS date (June 30, 2026). For more information, please visit https://aws.amazon.com/linux/amazon-linux-2023/faqs/[AL2023 FAQs], https://aws.amazon.com/bottlerocket/faqs/[Bottlerocket FAQs] or refer to <<al2023>> or <<eks-optimized-ami-bottlerocket>> documentation for detailed migration guidance. 


== Migration and support FAQs

=== How do I migrate from my AL2 to an AL2023 AMI?

We recommend creating and implementing a migration plan that includes thorough application workload testing and documented rollback procedures, then following the step-by-step instructions in the https://docs.aws.amazon.com/eks/latest/userguide/al2023.html[Upgrade from Amazon Linux 2 to Amazon Linux 2023] in EKS official documentation. 

=== Can I build a custom AL2 AMI past the EKS end-of-support (EOS) date for EKS optimized AL2 AMIs?

While we recommend moving to officially supported and published EKS optimized AMIs for AL2023 or Bottlerocket, you can build custom EKS AL2-optimized and AL2-accelerated AMIs until the AL2 AMI EOS date (November 26, 2025). Alternatively, you can build a custom AMI with an Amazon Linux 2 base instance until the Amazon Linux 2 EOS date (June 30, 2026). For step-by-step instructions to build a custom EKS AL2-optimized and AL2-accelerated AMI, see https://docs.aws.amazon.com/eks/latest/userguide/eks-ami-build-scripts.html[Build a custom Amazon Linux AMI] in EKS official documentation.

=== Does the EKS Kubernetes version support policy apply to Amazon Linux distributions?

No. The EOS date for EKS AL2-optimized and AL2-accelerated AMIs is independent of the standard and extended support timelines for Kubernetes versions by EKS. You need to migrate to AL2023 or Bottlerocket even if you are using EKS extended support.

=== How does the shift from cgroupv1 to cgroupv2 affect my migration?

The https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/4569-cgroup-v1-maintenance-mode/README.md[Kubernetes community] moved `cgroupv1` support (used by AL2) into maintenance mode, meaning no new features will be added and only critical security and major bug fixes will be provided.
To adopt `cgroupv2` in Kubernetes, you need to ensure compatibility across the OS, kernel, container runtime, and Kubernetes components.
This requires a Linux distribution that enables `cgroupv2` by default, such as AL2023, Bottlerocket, Red Hat Enterprise Linux (RHEL) 9+, Ubuntu 22.04+, or Debian 11+.
These distributions ship with kernel versions ≥5.8, which is the minimum requirement for `cgroupv2` support in Kubernetes. To learn more, see https://kubernetes.io/docs/concepts/architecture/cgroups/[About cgroup v2].

=== What do I do if I need Neuron in my custom AL2 AMI?

You cannot run your full Neuron-powered applications natively on an AL2-based AMIs.
To leverage {aws} Neuron on an AL2 AMI, you must containerize you applications using a Neuron-supported container with a non-AL2 Linux distribution (e.g., Ubuntu 22.04, Amazon Linux 2023, etc.) and then deploy those containers on an AL2-based AMI that has the Neuron Driver (`aws-neuronx-dkms`) installed.

== Compatibility and versions

=== Supported Kubernetes versions for AL2 AMIs

Kubernetes version 1.32 is the last version for which Amazon EKS will release AL2 (Amazon Linux 2) AMIs. For https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html[supported] Kubernetes versions up to 1.32, EKS will continue to release AL2 AMIs (AL2_ARM_64, AL2_x86_64) and AL2-accelerated AMIs (AL2_x86_64_GPU) until November 26, 2025. After this date, EKS will stop releasing AL2-optimized and AL2-accelerated AMIs for all Kubernetes versions. Note that the EOS date for EKS AL2-optimized and AL2-accelerated AMIs is independent of the standard and extended support timelines for Kubernetes versions by EKS.

=== NVIDIA drivers comparison for AL2, AL2023, and Bottlerocket AMIs

[%header,cols="5"]
|===
|Driver Branch
|Amazon Linux 2 AMI
|Amazon Linux 2023 AMI
|Bottlerocket AMI
|End-of-Life Date

|R535
|Not Supported
|Not Supported
|Not Supported
|https://docs.nvidia.com/ai-enterprise/index.html#release-documentation[September 2027]

|R550
|Supported
|Supported
|Not Supported
|https://docs.nvidia.com/ai-enterprise/index.html#release-documentation[April 2025]

|R560
|Not Supported
|Supported
|Not Supported
|https://docs.nvidia.com/ai-enterprise/index.html#release-documentation[March 2025]

|R570
|Not Supported
|Supported
|Supported
|https://docs.nvidia.com/ai-enterprise/index.html#release-documentation[February 2026]
|===

To learn more, see https://docs.nvidia.com/ai-enterprise/index.html#release-documentation[Nvidia Release Documentation].

=== NVIDIA CUDA versions comparison for AL2, AL2023, and Bottlerocket AMIs

[%header,cols="4"]
|===
|CUDA Version
|AL2 Support
|AL2023 Support
|Bottlerocket Support

|https://developer.nvidia.com/cuda-toolkit-archive[10.1]
|Supported
|Not supported
|Not Supported

|https://developer.nvidia.com/cuda-toolkit-archive[11.8]
|Supported
|Supported
|Supported

|https://developer.nvidia.com/cuda-toolkit-archive[12.0]
|Not supported
|Supported
|Supported

|https://developer.nvidia.com/cuda-toolkit-archive[12.5]
|Not supported
|Supported
|Supported
|===

To learn more, see https://developer.nvidia.com/cuda-toolkit-archive[CUDA Release Documentation].

=== Supported drivers and Linux kernel versions comparison for AL2, AL2023, and Bottlerocket AMIs

[%header,cols="4"]
|===
|Component
|AL2 AMI Source
|AL2023 AMI Source
|Bottlerocket AMI Source

|Base OS Compatibility
|RHEL7/CentOS 7
|Fedora/CentOS 9
|N/A

|CUDA Toolkit
|https://developer.nvidia.com/cuda-toolkit-archive[CUDA 11.x–12.x]
|https://developer.nvidia.com/cuda-toolkit-archive[CUDA 12.5+]
|CUDA 11.x (12.5 coming soon)

|NVIDIA GPU Driver
|https://docs.nvidia.com/ai-enterprise/index.html#infrastructure-software[R550]
|https://docs.nvidia.com/ai-enterprise/index.html#infrastructure-software[R565]
|https://docs.nvidia.com/ai-enterprise/index.html#infrastructure-software[R570]

|{aws} Neuron Driver
|https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/announcements/neuron2.x/announce-no-support-al2.html[2.19]
|https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/announcements/neuron2.x/announce-no-support-al2.html[2.19+]
|2.20	

|Linux Kernel
|https://docs.aws.amazon.com/linux/al2/ug/aml2-kernel.html[5.10]
|https://docs.aws.amazon.com/linux/al2023/ug/compare-with-al2-kernel.html[6.1], 6.12
|6.1, 6.12
|===

=== {aws} Neuron compatibility with AL2 AMIs

Starting from https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/prev/rn.html#neuron-2-20-0-whatsnew[{aws} Neuron release 2.20], the Neuron Runtime (`aws-neuronx-runtime-lib`) used by EKS AL-based AMIs no longer supports Amazon Linux 2 (AL2).
The Neuron Driver (`aws-neuronx-dkms`) is now the only {aws} Neuron package that supports Amazon Linux 2.
This means you cannot run your Neuron-powered applications natively on an AL2-based AMI.
To setup Neuron on AL2023 AMIs, see the https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/setup/index.html#setup-guide-index[{aws} Neuron Setup] guide.

=== Kubernetes compatibility with AL2 AMIs

The Kubernetes community has moved `cgroupv1` support (used by AL2) to maintenance mode.
This means no new features will be added, and only critical security and major bug fixes will be provided.
Any Kubernetes features relying on cgroupv2, such as MemoryQoS and enhanced resource isolation, are unavailable on AL2.
Furthermore, Amazon EKS Kubernetes version 1.32 was the last version to support AL2 AMIs.
To maintain compatibility with the latest Kubernetes versions, we recommend migrating to AL2023 or Bottlerocket, which enable `cgroupv2` by default.

=== Linux version compatibility with AL2 AMIs

Amazon Linux 2 (AL2) is supported by {aws} until its end-of-support (EOS) date on June 30, 2026.
However, as AL2 has aged, support from the broader Linux community for new applications and functionality has become more limited.
AL2 AMIs are based on https://docs.aws.amazon.com/linux/al2/ug/kernel.html[Linux kernel 5.10], while AL2023 uses https://docs.aws.amazon.com/linux/al2023/ug/compare-with-al2-kernel.html[Linux kernel 6.1].
Unlike AL2023, AL2 has limited support from the broader Linux community.
This means many upstream Linux packages and tools need to be backported to work with AL2's older kernel version, some modern Linux features and security improvements aren't available due to the older kernel, many open source projects have deprecated or limited support for older kernel versions like 5.10.

=== Deprecated packages not included in AL2023

A few of the most common packages that are not included or which changed in AL2023, include:

* Some https://docs.aws.amazon.com/linux/al2023/release-notes/removed-AL2023.6-AL2.html[source binary packages in Amazon Linux 2] are no longer available in Amazon Linux 2023
* Changes in how Amazon Linux supports different versions of packages (e.g., https://repost.aws/questions/QUWGU3VFJMRSGf6MDPWn4tLg/how-to-resolve-amazon-linux-extras-in-al2023[amazon-linux-extras system]) in AL2023
* https://docs.aws.amazon.com/linux/al2023/ug/epel.html[Extra Packages for Enterprise Linux (EPEL)] are not supported in AL2023
* https://docs.aws.amazon.com/linux/al2023/ug/deprecated-al2.html#deprecated-32bit-rpms[32-bit applications] are not supported in AL2023 

To learn more, see https://docs.aws.amazon.com/linux/al2023/ug/compare-with-al2.html[Comparing AL2 and AL2023].

=== FIPS validation comparison across AL2, AL2023, and Bottlerocket

Amazon Linux 2 (AL2), Amazon Linux 2023 (AL2023), and Bottlerocket provide support for Federal Information Processing Standards (FIPS) compliance.

* AL2 is certified under FIPS 140-2 and AL2023 is certified under FIPS 140-3. To enable FIPS mode on AL2023, install the necessary packages on your Amazon EC2 instance and follow the configuration steps using the instructions in https://docs.aws.amazon.com/linux/al2023/ug/fips-mode.html[Enable FIPS Mode on AL2023]. To learn more, see 
https://aws.amazon.com/linux/amazon-linux-2023/faqs[AL2023 FAQs].
* Bottlerocket provides purpose-built variants specifically for FIPS which constrain the kernel and userspace components to the use of cryptographic modules that have been submitted to the FIPS 140-3 Cryptographic Module Validation Program.

=== EKS AMI driver and versions changelog

For a complete list of all EKS AMI components and their versions, see https://github.com/awslabs/amazon-eks-ami/releases[Amazon EKS AMI Release Notes] on GitHub.

