[.topic]
[#hybrid-nodes-security]
= Patch security updates for hybrid nodes
:info_titleabbrev: Patch hybrid nodes
:keywords: security updates for on-premises nodes, security updates for hybrid nodes

include::../attributes.txt[]

[abstract]
--
Perform security updates on your Hybrid nodes
--

This topic describes the procedure to perform in-place patching of security updates for specific packages and dependencies running on your hybrid nodes. As a best practice we recommend you to regularly update your hybrid nodes to receive CVEs and security patches.

== Containerd

`containerd` is the standard Kubernetes container runtime and core dependency for EKS Hybrid Nodes, used for managing container lifecycle, including pulling images and managing container execution. On an hybrid node, you can install `containerd` through the link:eks/latest/userguide/hybrid-nodes-nodeadm.html[nodeadm CLI,type="documentation"] or manually. Depending on the operating system of your node, `nodeadm` will install `containerd` from the OS-distributed package or Docker package.

When a CVE in `containerd` has been published, you have the following options to upgrade to the patched version of `containerd` on your Hybrid nodes.

== Containerd CVE patch published to package managers

You can check whether the `containerd` CVE patch has been published to each respective OS package manager by referring to the corresponding security bulletins:

* https://alas.aws.amazon.com/alas2023.html[Amazon Linux 2023]
* https://access.redhat.com/security/security-updates/security-advisories[RHEL]
* https://ubuntu.com/security/notices?order=newest&release=focal[Ubuntu 20.04]
* https://ubuntu.com/security/notices?order=newest&release=jammy[Ubuntu 22.04]
* https://ubuntu.com/security/notices?order=newest&release=noble[Ubuntu 24.04]

If you use the Docker repo as the source of `containerd`, you can check the https://docs.docker.com/security/security-announcements/[Docker security announcements] to identify the availability of the patched version in the Docker repo.

=== Patching with `nodeadm upgrade`

After you confirm that the `containerd` CVE patch has been published to the OS or Docker repos (either Apt or RPM), you can use the `nodeadm upgrade` command to upgrade to the latest version of `containerd`. Since this isn't a Kubernetes version upgrade, you must pass in your current Kubernetes version to the `nodeadm` upgrade command.

[source,bash,subs="verbatim,attributes,quotes"]
----
nodeadm upgrade [.replaceable]`K8S_VERSION` --config-source file:///root/nodeConfig.yaml
----

=== Patching with operating system package managers

Alternatively you can also update through the respective package manager and use it to upgrade the `containerd` package as follows.

*Amazon Linux 2023*
[source,bash,subs="verbatim,attributes"]
----
sudo yum update -y
sudo yum install -y containerd
----

*RHEL*
[source,bash,subs="verbatim,attributes"]
----
sudo yum install -y yum-utils
sudo yum-config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
sudo yum update -y
sudo yum install -y containerd
----

*Ubuntu*
[source,bash,subs="verbatim,attributes"]
----
sudo mkdir -p /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt update -y
sudo apt install -y --only-upgrade containerd.io
----

== Containerd CVE patch not published in package managers

If the patched `containerd` version is only available by other means instead of in the package manager, for example in GitHub releases, then you can install `containerd` from the official GitHub site.

. If the machine has already joined the cluster as a hybrid node, then you need to run the `nodeadm uninstall` command.
. Install the official `containerd` binaries. You can use the steps https://github.com/containerd/containerd/blob/main/docs/getting-started.md#option-1-from-the-official-binaries[install the official containerd binaries].
. Run the `nodeadm install` command with the `--containerd-source` argument set to `none`, which will skip `containerd` installation through `nodeadm`. You can use the value of `none` in the `containerd` source for any operating system that the node is running.
+
[source,bash,subs="verbatim,attributes,quotes"]
----
nodeadm install [.replaceable]`K8S_VERSION` --credential-provider [.replaceable]`CREDS_PROVIDER` --containerd-source none
----
