include::../attributes.txt[]

[.topic]
[#hybrid-nodes-cluster-update]
= Enable hybrid nodes on an existing Amazon EKS cluster or modify configuration
:info_titleabbrev: Existing cluster

[abstract]
--
Modify hybrid nodes configuration on an existing cluster
--

This topic provides an overview of the available options and describes what to consider when you add, change, or remove the hybrid nodes configuration from an Amazon EKS cluster. If you are not planning to use hybrid nodes, see <<create-cluster>>.

To enable an Amazon EKS cluster to use hybrid nodes, add the IP address CIDR ranges of your on-premises node and optionally pod network in the `RemoteNetworkConfig` configuration. EKS uses this list of CIDRs to enable connectivity between the cluster and your on-premises networks. For a full list of options when updating your cluster configuration, see the link:eks/latest/APIReference/API_UpdateClusterConfig.html[UpdateClusterConfig,type="documentation"] in the _Amazon EKS API Reference_.

You can do any of the following actions to the EKS Hybrid Nodes networking configuration in a cluster:

* Add remote node network configuration to enable EKS Hybrid Nodes in an existing cluster.
* Add, change, or remove the remote node networks. Remove all remote node network CIDR ranges to disable EKS Hybrid Nodes in an existing cluster.
* Add, change, or remove the optional remote pod networks. 
* Remove all of the remote pod networks.

The following examples enable EKS Hybrid Nodes on an existing cluster and include the optional remote pod network.

[#hybrid-nodes-cluster-enable-prep]
== Prerequisites

* The latest version of the {aws} Command Line Interface ({aws} CLI) installed and configured on your device. To check your current version, use `aws --version`. Package managers such yum, apt-get, or Homebrew for macOS are often several versions behind the latest version of the {aws} CLI. To install the latest version, see link:cli/latest/userguide/getting-started-install.html[Installing or updating to the last version of the {aws} CLI,type="documentation"] and link:cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-config[Configuring settings for the {aws} CLI,type="documentation"] in the {aws} Command Line Interface User Guide.
* Before enabling your Amazon EKS cluster for hybrid nodes, ensure your environment meets the requirements outlined at <<hybrid-nodes-prereqs>>, and detailed at <<hybrid-nodes-networking>>, <<hybrid-nodes-os>>, and <<hybrid-nodes-creds>>.
* Your cluster must use either API or API_AND_CONFIG_MAP for the cluster authentication mode.
* Your cluster must use IPv4 address family.
* It is recommended to use either public or private endpoint access for the Amazon EKS Kubernetes API server endpoint. If you choose “Public and Private”, the Amazon EKS Kubernetes API server endpoint will always resolve to the public IPs for hybrid nodes running outside of your VPC, which can prevent your hybrid nodes from joining the cluster. 
* An link:IAM/latest/UserGuide/id_roles#iam-term-principal[IAM principal,type="documentation"] with permission to call link:eks/latest/APIReference/API_UpdateClusterConfig.html[UpdateClusterConfig,type="documentation"] on your Amazon EKS cluster.
* Update add-ons to versions that are compatible with hybrid nodes. For the add-ons versions that are compatible with hybrid nodes, see <<hybrid-nodes-add-ons>>. 
* If you are running add-ons that are not compatible with hybrid nodes, ensure that the add-on https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/[DaemonSet] or https://kubernetes.io/docs/concepts/workloads/controllers/deployment/[Deployment] has the following affinity rule to prevent deployment to hybrid nodes. Add the affinity rule if it is not already present.

[source,yaml]
----
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: eks.amazonaws.com/compute-type
          operator: NotIn
          values:
          - hybrid
----



[#hybrid-nodes-cluster-enable-consider]
== Considerations 
The `remoteNetworkConfig` JSON object has the following behavior during an update:

* Any existing part of the configuration that you don't specify is unchanged. If you don't specify either of the `remoteNodeNetworks` or `remotePodNetworks`, that part will remain the same.
* If you are modifying either the `remoteNodeNetworks` or `remotePodNetworks` lists of CIDRs, you must specify the complete list of CIDRs that you want in your final configuration. When you specify a change to either the `remoteNodeNetworks` or `remotePodNetworks` CIDR list, EKS replaces the original list during the update.


[#hybrid-nodes-cluster-enable-existing]
== Enable hybrid nodes on an existing cluster

You can enable EKS Hybrid Nodes in an existing cluster by using:

* <<hybrid-nodes-cluster-enable-cfn,{aws} CloudFormation>>
* <<hybrid-nodes-cluster-enable-cli,{aws} CLI>>
* <<hybrid-nodes-cluster-enable-console,{aws-management-console}>>


[#hybrid-nodes-cluster-enable-cfn]
=== Enable EKS Hybrid Nodes in an existing cluster - {aws} CloudFormation

. To enable EKS Hybrid Nodes in your cluster, add the `RemoteNodeNetwork` and (optional) `RemotePodNetwork` to your CloudFormation template and update the stack. Note that `RemoteNodeNetwork` is a list with a maximum of one `Cidrs` item and the `Cidrs` is a list of multiple IP CIDR ranges.
+
[source,yaml,subs="verbatim,attributes"]
----
RemoteNetworkConfig:
  RemoteNodeNetworks:
    - Cidrs: [RemoteNodeCIDR]
  RemotePodNetworks:
    - Cidrs: [RemotePodCIDR]
----

. Continue to <<hybrid-nodes-cluster-prep>>.

[#hybrid-nodes-cluster-enable-cli]
=== Enable EKS Hybrid Nodes in an existing cluster - {aws} CLI

. Run the following command to enable `RemoteNetworkConfig` for EKS Hybrid Nodes for your EKS cluster. Before running the command, replace the following with your desired settings. For a full list of settings, see the link:eks/latest/APIReference/API_UpdateClusterConfig.html[UpdateClusterConfig,type="documentation"] in the _Amazon EKS API Reference_.
.. `CLUSTER_NAME`: name of the EKS cluster to update.
.. `AWS_REGION`: {aws} Region where the EKS cluster is running. 
.. `REMOTE_NODE_CIDRS`: the on-premises node CIDR for your hybrid nodes. 
.. `REMOTE_POD_CIDRS` (optional): the on-premises pod CIDR for workloads running on hybrid nodes.
.. Your on-premises node and pod CIDR blocks must meet the following requirements:
... Be within one of the IPv4 RFC-1918 ranges: `10.0.0.0/8`, `172.16.0.0/12`, or `192.168.0.0/16`.
... Not overlap with each other, all CIDRs of the VPC for your Amazon EKS cluster, or your Kubernetes service IPv4 CIDR.
+
[source,bash,subs="verbatim,attributes"]
----
aws eks update-cluster \
    --name CLUSTER_NAME \
    --region AWS_REGION \
    --remote-network-config '{"remoteNodeNetworks":[{"cidrs":["REMOTE_NODE_CIDRS"]}],"remotePodNetworks":[{"cidrs":["REMOTE_POD_CIDRS"]}]}' 
----

. It takes several minutes to update the cluster. You can query the status of your cluster with the following command. Replace `CLUSTER_NAME` with the name of the cluster you are modifying and `AWS_REGION` with the {aws} Region where the cluster is running. Don't proceed to the next step until the output returned is `ACTIVE`.
+
[source,bash,subs="verbatim,attributes"]
----
aws eks describe-cluster \
    --name CLUSTER_NAME \
    --region AWS_REGION \
    --query "cluster.status"
----

. Continue to <<hybrid-nodes-cluster-prep>>.


[#hybrid-nodes-cluster-enable-console]
=== Enable EKS Hybrid Nodes in an existing cluster - {aws-management-console}

. Open the Amazon EKS console at link:eks/home#/clusters[Amazon EKS console,type="console"].
. Choose the name of the cluster to display your cluster information.
. Choose the *Networking* tab and choose *Manage*.
. In the dropdown, choose *Remote networks*.
. *Choose Configure remote networks to enable hybrid nodes* and specify your on-premises node and pod CIDRs for hybrid nodes.
. Choose *Save changes* to finish. Wait for the cluster status to return to *Active*.

. Continue to <<hybrid-nodes-cluster-prep>>.
