include::../attributes.txt[]

[.topic]
[#hybrid-nodes-concepts]
= Concepts for hybrid nodes
:info_titleabbrev: Concepts

[abstract]
--
Learn about EKS Hybrid Nodes technical concepts and how it works
--

*Amazon EKS Hybrid Nodes* lets you join physical or virtual machines running in on-premises or edge environments to Amazon EKS clusters running in {aws} Cloud. This approach brings many benefits, but also introduces new networking concepts and architectures for those familiar with running Kubernetes clusters in a single network environment. 

This section dives deep into the Kubernetes and networking concepts for EKS Hybrid Nodes and details how traffic flows through the hybrid architecture. Basic Kubernetes networking knowledge is assumed, like the concepts of pods, nodes, services, Kubernetes control plane, kubelet and kube-proxy. We recommend traversing these pages in order, starting with the <<hybrid-nodes-concepts-networking>>, then the <<hybrid-nodes-concepts-kubernetes>>, and finally the <<hybrid-nodes-concepts-traffic-flows>>.

include::hybrid-nodes-concepts-networking.adoc[leveloffset=+1]

include::hybrid-nodes-concepts-kubernetes.adoc[leveloffset=+1]

include::hybrid-nodes-concepts-traffic-flows.adoc[leveloffset=+1]