include::../attributes.txt[]

[.topic]
[#hybrid-nodes-cluster-update]
= Enable hybrid nodes on an existing Amazon EKS cluster or modify configuration
:info_titleabbrev: Existing cluster

[abstract]
--
Modify hybrid nodes configuration on an existing cluster
--

This topic provides an overview of the available options and describes what to consider when you add, change, or remove the hybrid nodes configuration from an Amazon EKS cluster. If you are not planning to use hybrid nodes, see <<create-cluster>>.

To enable an Amazon EKS cluster to use hybrid nodes, add the IP address CIDR ranges of your on-premises node and optionally pod network in the `RemoteNetworkConfig` configuration. EKS uses this list of CIDRs to enable connectivity between the cluster and your on-premises networks. For a full list of options when updating your cluster configuration, see the link:eks/latest/APIReference/API_UpdateClusterConfig.html[UpdateClusterConfig,type="documentation"] in the _Amazon EKS API Reference_.

You can do any of the following actions to the EKS Hybrid Nodes networking configuration in a cluster:

* <<hybrid-nodes-cluster-enable-existing,Add remote network configuration to enable EKS Hybrid Nodes in an existing cluster.>>
* <<hybrid-nodes-cluster-update-config,Add, change, or remove the remote node networks or the remote pod networks in an existing cluster.>>
* <<hybrid-nodes-cluster-disable,Remove all remote node network CIDR ranges to disable EKS Hybrid Nodes in an existing cluster.>>

[#hybrid-nodes-cluster-enable-prep]
== Prerequisites

* The latest version of the {aws} Command Line Interface ({aws} CLI) installed and configured on your device. To check your current version, use `aws --version`. Package managers such yum, apt-get, or Homebrew for macOS are often several versions behind the latest version of the {aws} CLI. To install the latest version, see link:cli/latest/userguide/getting-started-install.html[Installing or updating to the latest version of the {aws} CLI,type="documentation"] and link:cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-config[Configuring settings for the {aws} CLI,type="documentation"] in the {aws} Command Line Interface User Guide.
* Before enabling your Amazon EKS cluster for hybrid nodes, ensure your environment meets the requirements outlined at <<hybrid-nodes-prereqs>>, and detailed at <<hybrid-nodes-networking>>, <<hybrid-nodes-os>>, and <<hybrid-nodes-creds>>.
* Your cluster must use IPv4 address family.
* Your cluster must use either API or API_AND_CONFIG_MAP for the cluster authentication mode. The process for modifying the cluster authentication mode is described at <<setting-up-access-entries>>.
* It is recommended to use either public or private endpoint access for the Amazon EKS Kubernetes API server endpoint. If you choose “Public and Private”, the Amazon EKS Kubernetes API server endpoint will always resolve to the public IPs for hybrid nodes running outside of your VPC, which can prevent your hybrid nodes from joining the cluster. The process for modifying network access to your cluster is described at <<cluster-endpoint>>. 
* An link:IAM/latest/UserGuide/id_roles#iam-term-principal[IAM principal,type="documentation"] with permission to call link:eks/latest/APIReference/API_UpdateClusterConfig.html[UpdateClusterConfig,type="documentation"] on your Amazon EKS cluster.
* Update add-ons to versions that are compatible with hybrid nodes. For the add-ons versions that are compatible with hybrid nodes, see <<hybrid-nodes-add-ons>>. 
* If you are running add-ons that are not compatible with hybrid nodes, ensure that the add-on https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/[DaemonSet] or https://kubernetes.io/docs/concepts/workloads/controllers/deployment/[Deployment] has the following affinity rule to prevent deployment to hybrid nodes. Add the following affinity rule if it is not already present.
+
[source,yaml]
----
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: eks.amazonaws.com/compute-type
          operator: NotIn
          values:
          - hybrid
----



[#hybrid-nodes-cluster-enable-consider]
== Considerations 
The `remoteNetworkConfig` JSON object has the following behavior during an update:

* Any existing part of the configuration that you don't specify is unchanged. If you don't specify either of the `remoteNodeNetworks` or `remotePodNetworks`, that part will remain the same.
* If you are modifying either the `remoteNodeNetworks` or `remotePodNetworks` lists of CIDRs, you must specify the complete list of CIDRs that you want in your final configuration. When you specify a change to either the `remoteNodeNetworks` or `remotePodNetworks` CIDR list, EKS replaces the original list during the update.
* Your on-premises node and pod CIDR blocks must meet the following requirements:
. Be within one of the IPv4 RFC-1918 ranges: 10.0.0.0/8, 172.16.0.0/12, or 192.168.0.0/16.
. Not overlap with each other, all CIDRs of the VPC for your Amazon EKS cluster, or your Kubernetes service IPv4 CIDR.


[#hybrid-nodes-cluster-enable-existing]
== Enable hybrid nodes on an existing cluster

You can enable EKS Hybrid Nodes in an existing cluster by using:

* <<hybrid-nodes-cluster-enable-cfn,{aws} CloudFormation>>
* <<hybrid-nodes-cluster-enable-cli,{aws} CLI>>
* <<hybrid-nodes-cluster-enable-console,{aws-management-console}>>


[#hybrid-nodes-cluster-enable-cfn]
=== Enable EKS Hybrid Nodes in an existing cluster - {aws} CloudFormation

. To enable EKS Hybrid Nodes in your cluster, add the `RemoteNodeNetwork` and (optional) `RemotePodNetwork` to your CloudFormation template and update the stack. Note that `RemoteNodeNetwork` is a list with a maximum of one `Cidrs` item and the `Cidrs` is a list of multiple IP CIDR ranges.
+
[source,yaml,subs="verbatim,attributes"]
----
RemoteNetworkConfig:
  RemoteNodeNetworks:
    - Cidrs: [RemoteNodeCIDR]
  RemotePodNetworks:
    - Cidrs: [RemotePodCIDR]
----

. Continue to <<hybrid-nodes-cluster-prep>>.

[#hybrid-nodes-cluster-enable-cli]
=== Enable EKS Hybrid Nodes in an existing cluster - {aws} CLI

. Run the following command to enable `RemoteNetworkConfig` for EKS Hybrid Nodes for your EKS cluster. Before running the command, replace the following with your desired settings. For a full list of settings, see the link:eks/latest/APIReference/API_UpdateClusterConfig.html[UpdateClusterConfig,type="documentation"] in the _Amazon EKS API Reference_.
.. `CLUSTER_NAME`: name of the EKS cluster to update.
.. `AWS_REGION`: {aws} Region where the EKS cluster is running. 
.. `REMOTE_NODE_CIDRS`: the on-premises node CIDR for your hybrid nodes. 
.. `REMOTE_POD_CIDRS` (optional): the on-premises pod CIDR for workloads running on hybrid nodes.
+
[source,bash,subs="verbatim,attributes"]
----
aws eks update-cluster \
    --name CLUSTER_NAME \
    --region AWS_REGION \
    --remote-network-config '{"remoteNodeNetworks":[{"cidrs":["REMOTE_NODE_CIDRS"]}],"remotePodNetworks":[{"cidrs":["REMOTE_POD_CIDRS"]}]}' 
----

. It takes several minutes to update the cluster. You can query the status of your cluster with the following command. Replace `CLUSTER_NAME` with the name of the cluster you are modifying and `AWS_REGION` with the {aws} Region where the cluster is running. Don't proceed to the next step until the output returned is `ACTIVE`.
+
[source,bash,subs="verbatim,attributes"]
----
aws eks describe-cluster \
    --name CLUSTER_NAME \
    --region AWS_REGION \
    --query "cluster.status"
----

. Continue to <<hybrid-nodes-cluster-prep>>.


[#hybrid-nodes-cluster-enable-console]
=== Enable EKS Hybrid Nodes in an existing cluster - {aws-management-console}

. Open the Amazon EKS console at link:eks/home#/clusters[Amazon EKS console,type="console"].
. Choose the name of the cluster to display your cluster information.
. Choose the *Networking* tab and choose *Manage*.
. In the dropdown, choose *Remote networks*.
. *Choose Configure remote networks to enable hybrid nodes* and specify your on-premises node and pod CIDRs for hybrid nodes.
. Choose *Save changes* to finish. Wait for the cluster status to return to *Active*.

. Continue to <<hybrid-nodes-cluster-prep>>.

[#hybrid-nodes-cluster-update-config] 
== Update hybrid nodes configuration in an existing cluster

You can modify `remoteNetworkConfig` in an existing hybrid cluster using:

* <<hybrid-nodes-cluster-update-cfn,{aws} CloudFormation>>
* <<hybrid-nodes-cluster-update-cli,{aws} CLI>>
* <<hybrid-nodes-cluster-update-console,{aws-management-console}>>

[#hybrid-nodes-cluster-update-cfn] 
=== Update hybrid configuration in an existing cluster - {aws} CloudFormation

. Update your CloudFormation template with the new network CIDR values.
+
[source,yaml,subs="verbatim,attributes"]
----
RemoteNetworkConfig:
  RemoteNodeNetworks:
    - Cidrs: [NEW_REMOTE_NODE_CIDRS]
  RemotePodNetworks:
    - Cidrs: [NEW_REMOTE_POD_CIDRS]
----
NOTE: When updating `RemoteNodeNetworks` or `RemotePodNetworks` CIDR lists, include all desired CIDRs (new and existing). EKS replaces the entire list during updates.
Omitting these fields from the update request retains their existing configurations.

. Update your CloudFormation stack with the modified template and wait for the stack update to complete.

[#hybrid-nodes-cluster-update-cli] 
=== Update hybrid configuration in an existing cluster - {aws} CLI

. To modify the remote network CIDRs, run the following command. Replace the values with your desired settings:
+
[source,bash,subs="verbatim,attributes"]
----
aws eks update-cluster
--name CLUSTER_NAME
--region AWS_REGION
--remote-network-config '{"remoteNodeNetworks":[{"cidrs":["NEW_REMOTE_NODE_CIDRS"]}],"remotePodNetworks":[{"cidrs":["NEW_REMOTE_POD_CIDRS"]}]}'
----
NOTE: When updating `remoteNodeNetworks` or `remotePodNetworks` CIDR lists, include all desired CIDRs (new and existing). EKS replaces the entire list during updates.
Omitting these fields from the update request retains their existing configurations.

. Wait for the cluster status to return to ACTIVE before proceeding.

[#hybrid-nodes-cluster-update-console] 
=== Update hybrid configuration in an existing cluster - {aws-management-console}

. Open the Amazon EKS console at link:eks/home#/clusters[Amazon EKS console,type="console"].
. Choose the name of the cluster to display your cluster information.
. Choose the *Networking* tab and choose *Manage*.
. In the dropdown, choose *Remote networks*.
. Update the CIDRs under `Remote node networks` and `Remote pod networks - Optional` as needed.
. Choose *Save changes* and wait for the cluster status to return to *Active*.


[#hybrid-nodes-cluster-disable]
== Disable Hybrid nodes in an existing cluster

You can disable EKS Hybrid Nodes in an existing cluster by using:

* <<hybrid-nodes-cluster-disable-cfn,{aws} CloudFormation>>
* <<hybrid-nodes-cluster-disable-cli,{aws} CLI>>
* <<hybrid-nodes-cluster-disable-console,{aws-management-console}>>

[#hybrid-nodes-cluster-disable-cfn]
=== Disable EKS Hybrid Nodes in an existing cluster - {aws} CloudFormation

. To disable EKS Hybrid Nodes in your cluster, set `RemoteNodeNetworks` and `RemotePodNetworks` to empty arrays in your CloudFormation template and update the stack.
+
[source,yaml,subs="verbatim,attributes"]
----
RemoteNetworkConfig:
  RemoteNodeNetworks: []
  RemotePodNetworks: []
----

[#hybrid-nodes-cluster-disable-cli]
=== Disable EKS Hybrid Nodes in an existing cluster - {aws} CLI
. Run the following command to remove `RemoteNetworkConfig` from your EKS cluster. Before running the command, replace the following with your desired settings. For a full list of settings, see the link:eks/latest/APIReference/API_UpdateClusterConfig.html[UpdateClusterConfig,type="documentation"] in the _Amazon EKS API Reference_.
.. `CLUSTER_NAME`: name of the EKS cluster to update.
.. `AWS_REGION`: {aws} Region where the EKS cluster is running.
+
[source,bash,subs="verbatim,attributes"]
----
aws eks update-cluster \
    --name CLUSTER_NAME \
    --region AWS_REGION \
    --remote-network-config '{"remoteNodeNetworks":[],"remotePodNetworks":[]}' 
----
. It takes several minutes to update the cluster. You can query the status of your cluster with the following command. Replace `CLUSTER_NAME` with the name of the cluster you are modifying and `AWS_REGION` with the {aws} Region where the cluster is running. Don't proceed to the next step until the output returned is `ACTIVE`.
+
[source,bash,subs="verbatim,attributes"]
----
aws eks describe-cluster \
    --name CLUSTER_NAME \
    --region AWS_REGION \
    --query "cluster.status"
----

[#hybrid-nodes-cluster-disable-console]
=== Disable EKS Hybrid Nodes in an existing cluster - {aws-management-console}

. Open the Amazon EKS console at link:eks/home#/clusters[Amazon EKS console,type="console"].
. Choose the name of the cluster to display your cluster information.
. Choose the *Networking* tab and choose *Manage*.
. In the dropdown, choose *Remote networks*.
. Choose *Configure remote networks to enable hybrid nodes* and remove all the CIDRs under `Remote node networks` and `Remote pod networks - Optional`.
. Choose *Save changes* to finish. Wait for the cluster status to return to *Active*.
