include::../attributes.txt[]

[.topic]
[#create-page]
= Create a new page
:info_titleabbrev: Create page

[abstract]
--
This topic includes instructions for creating the initial page metadata and adding the page to the guide table of contents.
--

Learn how to create a new documentation page. This topic includes instructions for creating the initial page metadata and adding the page to the guide table of contents. 

== Create page

. Navigate to the chapter directory. For example, if you want to create a new page in the "Security" section, navigate to the `latest/ug/security` directory. 
. Determine the page ID. By convention, the page ID is all lowercase and segmented with `-`. The ID of this page is `create-page`.
. Create a new file with the page ID and the `adoc` extension. For example, `create-page.adoc`.
. Insert the page metadata using this template:


[source,asciidoc]
----
 include::../attributes.txt[]

 [.topic]
 [#unique-page-id]
 = Page title
 :info_titleabbrev: Short title

 [abstract]
 --
 Brief summary of the page's content.
 --

 Introduction paragraph goes here.
----


== Add page to navigation

. Navigate to the parent page. The parent page of top level sections is `book.adoc`.
. At the bottom of the parent page, include the child page.
+
`include::${filename}[leveloffset=+1]`
+
_For example:_
+
`include::create-page.adoc[leveloffset=+1]`