[.topic]
[#pr-status]
= View the status of your GitHub Pull Request (PR)
:info_titleabbrev: View PR Status


include::../attributes.txt[]

After you create a pull request, you can track it's status. Pull requests have three important statuses: merged, closed, and changes requested. 

If a pull request is merged, the changes were accepted. It may take a few hours for the website to update. If the PR was closed, please understand we appreciate the contribution but could not approve the changes. For example, we may have been unable to replicate the problem. If a pull request has changes requested, review the feedback and update the pull request. 

include::images/contribute-pr.png["View PR feedback"]

== View the pull requests you created
To view pull requests you created:

. Go to the GitHub repository
. Click the "Pull requests" tab
. Select *Filters* and then *Your pull requests*
. Review the list of your open pull requests

== View pull requests assigned to you 
To view pull requests assigned to you for review:

. Go to the GitHub repository
. Click the "Pull requests" tab
. Select *filters* and then *assigned to you*
. Review the list of pull requests awaiting your review

== Review a pull request

Learn how to https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request[review a pull request] in the GitHub Docs.

== Make further changes on a pull request

If changes are requested on a pull request, you can make further changes in the pull request.

{aws} suggests using the GitHub.dev web editor to make further changes to a pull request. This supports viewing PR comments inside the text editor. 

=== Make further changes with a web browser

. Use the `.` (period) key to open the pull request in the GitHub web editor
. Review the comments and make changes in the text editor. You can mark comments as resolved from within the editor. 
. Use the *source control* menu in the left sidebar to commit the changes, which updates the PR. 

=== Make further changes locally

Use the GitHub CLI to pull the changes locally.

==== Setup GitHub CLI

. Install the GitHub CLI if you haven't already:
  * For macOS: `brew install gh`
  * For Windows: `winget install GitHub.cli`
  * For Linux: Follow instructions at https://github.com/cli/cli#installation

. Authenticate with GitHub:
  * Run `gh auth login`
  * Follow the prompts to complete authentication

==== Checkout pull request

. Check out the pull request branch:
  * Run `gh pr checkout <PR-NUMBER>`
  * Replace <PR-NUMBER> with your pull request number
  * The pull request number is visible at the top of the PR
  * This creates a local branch with the PR changes

. Make your changes locally using your preferred text editor

. Commit and push your changes:
  * Stage changes: `git add .` 
  * Commit changes: `git commit -m "your commit message"`
  * Push to GitHub: `git push`

The pull request will automatically update with your new changes. 


📝 https://github.com/search?q=repo%3Aawsdocs%2Famazon-eks-user-guide+%5B%23pr-status%5D&type=code[Edit this page on GitHub]