include::../attributes.txt[]

[.topic]
[#eks-outposts-local-cluster-create]
= Deploy an Amazon EKS cluster on {aws} Outposts
:info_titleabbrev: Deploy a local cluster

[abstract]
--
Learn to create a local Amazon EKS cluster on {aws} Outposts.
--

This topic provides an overview of what to consider when running a local cluster on an Outpost. The topic also provides instructions for how to deploy a local cluster on an Outpost.


[IMPORTANT]
====
* These considerations aren't replicated in related Amazon EKS documentation. If other Amazon EKS documentation topics conflict with the considerations here, follow the considerations here.
* These considerations are subject to change and might change frequently. So, we recommend that you regularly review this topic.
* Many of the considerations are different than the considerations for creating a cluster on the {aws} Cloud.
====

* Local clusters support Outpost racks only. A single local cluster can run across multiple physical Outpost racks that comprise a single logical Outpost. A single local cluster can't run across multiple logical Outposts. Each logical Outpost has a single Outpost ARN.
* Local clusters run and manage the Kubernetes control plane in your account on the Outpost. You can't run workloads on the Kubernetes control plane instances or modify the Kubernetes control plane components. These nodes are managed by the Amazon EKS service. Changes to the Kubernetes control plane don't persist through automatic Amazon EKS management actions, such as patching.
* Local clusters support self-managed add-ons and self-managed Amazon Linux node groups. The <<managing-vpc-cni,Amazon VPC CNI plugin for Kubernetes>>, <<managing-kube-proxy,kube-proxy>>, and <<managing-coredns,CoreDNS>> add-ons are automatically installed on local clusters. 
* Local clusters require the use of Amazon EBS on Outposts. Your Outpost must have Amazon EBS available for the Kubernetes control plane storage. Outposts support Amazon EBS `gp2` volumes only.
* Amazon EBS backed Kubernetes `PersistentVolumes` are supported using the Amazon EBS CSI driver.
* The control plane instances of local clusters are set up in https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/ha-topology/[stacked highly available topology]. Two out of the three control plane instances must be healthy at all times to maintain quorum. If quorum is lost, contact {aws} support, as some service-side actions will be required to enable the new managed instances.

*Prerequisites*

* Familiarity with the <<outposts-overview-comparing-deployment-options,Outposts deployment options>>, <<eks-outposts-capacity-considerations,Select instance types and placement groups for Amazon EKS clusters on {aws} Outposts based on capacity considerations>>, and <<eks-outposts-vpc-subnet-requirements,VPC requirements and considerations>>.
* An existing Outpost. For more information, see link:outposts/latest/userguide/what-is-outposts.html[What is {aws} Outposts,type="documentation"].
* The `kubectl` command line tool is installed on your computer or {aws} CloudShell. The version can be the same as or up to one minor version earlier or later than the Kubernetes version of your cluster. For example, if your cluster version is `1.29`, you can use `kubectl` version `1.28`, `1.29`, or `1.30` with it. To install or upgrade `kubectl`, see <<install-kubectl>>.
* Version `2.12.3` or later or version `1.27.160` or later of the {aws} Command Line Interface ({aws} CLI) installed and configured on your device or {aws} CloudShell. To check your current version, use `aws --version | cut -d / -f2 | cut -d ' ' -f1`. Package managers such `yum`, `apt-get`, or Homebrew for macOS are often several versions behind the latest version of the {aws} CLI. To install the latest version, see link:cli/latest/userguide/cli-chap-install.html[Installing, updating, and uninstalling the {aws} CLI,type="documentation"] and link:cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-config[Quick configuration with aws configure,type="documentation"] in the _{aws} Command Line Interface User Guide_. The {aws} CLI version that is installed in {aws} CloudShell might also be several versions behind the latest version. To update it, see link:cloudshell/latest/userguide/vm-specs.html#install-cli-software[Installing {aws} CLI to your home directory,type="documentation"] in the _{aws} CloudShell User Guide_.
* An IAM principal (user or role) with permissions to `create` and `describe` an Amazon EKS cluster. For more information, see <<policy-create-local-cluster>> and <<policy-example2>>.

When a local Amazon EKS cluster is created, the link:IAM/latest/UserGuide/id_roles.html#iam-term-principal[IAM principal,type="documentation"] that creates the cluster is permanently added. The principal is specifically added to the Kubernetes RBAC authorization table as the administrator. This entity has `system:masters` permissions. The identity of this entity isn't visible in your cluster configuration. So, it's important to note the entity that created the cluster and make sure that you never delete it. Initially, only the principal that created the server can make calls to the Kubernetes API server using `kubectl`. If you use the console to create the cluster, make sure that the same IAM credentials are in the {aws} SDK credential chain when you run `kubectl` commands on your cluster. After your cluster is created, you can grant other IAM principals access to your cluster.

== Create an Amazon EKS local cluster
You can create a local cluster with the following tools described in this page:

* <<eksctl_create_cluster_outpost>>
* <<console_create_cluster_outpost>>

You could also use the link:cli/latest/reference/eks/create-cluster.html[{aws} CLI,type="documentation"], the link:eks/latest/APIReference/API_CreateCluster.html[Amazon EKS API,type="documentation"], the link:developer/tools/[{aws} SDKs,type="marketing"], link:AWSCloudFormation/latest/UserGuide/aws-properties-eks-cluster-outpostconfig.html[{aws} CloudFormation,type="documentation"] or https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest[Terraform] to create clusters on Outposts.

=== `eksctl` [[eksctl_create_cluster_outpost]]

*To create a local cluster with `eksctl`*
 
. Install version `{eksctl-min-version}` or later of the `eksctl` command line tool on your device or {aws} CloudShell. To install or update `eksctl`, see https://eksctl.io/installation[Installation] in the `eksctl` documentation. 

. Copy the contents that follow to your device. Replace the following values and then run the modified command to create the `outpost-control-plane.yaml` file:
+
* Replace [.replaceable]`region-code` with the <<outposts-control-plane-supported-regions,supported {aws} Region>> that you want to create your cluster in.
* Replace [.replaceable]`my-cluster` with a name for your cluster. The name can contain only alphanumeric characters (case-sensitive) and hyphens. It must start with an alphanumeric character and can't be longer than 100 characters. The name must be unique within the {aws} Region and {aws} account that you're creating the cluster in. The name must be unique within the {aws} Region and {aws} account that you're creating the cluster in.
* Replace [.replaceable]`vpc-ExampleID1` and [.replaceable]`subnet-ExampleID1` with the IDs of your existing VPC and subnet. The VPC and subnet must meet the requirements in <<eks-outposts-vpc-subnet-requirements,Create a VPC and subnets for Amazon EKS clusters on {aws} Outposts>>.
* Replace [.replaceable]`uniqueid` with the ID of your Outpost.
* Replace [.replaceable]`m5.large` with an instance type available on your Outpost. Before choosing an instance type, see <<eks-outposts-capacity-considerations>>. Three control plane instances are deployed. You can't change this number.
+
[source,yaml,subs="verbatim,attributes"]
----
cat >outpost-control-plane.yaml <<EOF
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: region-code
  version: "{k8s-n}"

vpc:
  clusterEndpoints:
    privateAccess: true
  id: "vpc-vpc-ExampleID1"
  subnets:
    private:
      outpost-subnet-1:
        id: "subnet-subnet-ExampleID1"

outpost:
  controlPlaneOutpostARN: {arn-aws}outposts:region-code:111122223333:outpost/op-uniqueid
  controlPlaneInstanceType: m5.large
EOF
----
+
For a complete list of all available options and defaults, see https://eksctl.io/usage/outposts/[{aws} Outposts Support] and https://eksctl.io/usage/schema/[Config file schema] in the `eksctl` documentation.
. Create the cluster using the configuration file that you created in the previous step. `eksctl` creates a VPC and one subnet on your Outpost to deploy the cluster in.
+
[source,bash,subs="verbatim,attributes"]
----
eksctl create cluster -f outpost-control-plane.yaml
----
+
Cluster provisioning takes several minutes. While the cluster is being created, several lines of output appear. The last line of output is similar to the following example line.
+
[source,bash,subs="verbatim,attributes"]
----
[✓]  EKS cluster "my-cluster" in "region-code" region is ready
----
+
[TIP]
====
To see the most options that you can specify when creating a cluster with `eksctl`, use the `eksctl create cluster --help` command. To see all the available options, you can use a `config` file. For more information, see https://eksctl.io/usage/creating-and-managing-clusters/#using-config-files[Using config files] and the https://eksctl.io/usage/schema/[config file schema] in the `eksctl` documentation. You can find https://github.com/weaveworks/eksctl/tree/master/examples[config file examples] on GitHub.
====
+
The `eksctl` command automatically created an <<access-entries,access entry>> for the IAM principal (user or role) that created the cluster and granted the IAM principal administrator permissions to Kubernetes objects on the cluster. If you don't want the cluster creator to have administrator access to Kubernetes objects on the cluster, add the following text to the previous configuration file: `bootstrapClusterCreatorAdminPermissions: false` (at the same level as `metadata`, `vpc`, and `outpost`). If you added the option, then after cluster creation, you need to create an access entry for at least one IAM principal, or no IAM principals will have access to Kubernetes objects on the cluster.

=== {aws-management-console} [[console_create_cluster_outpost]]

*To create your cluster with the {aws-management-console}*

. You need an existing VPC and subnet that meet Amazon EKS requirements. For more information, see <<eks-outposts-vpc-subnet-requirements>>.
. If you already have a local cluster IAM role, or you're going to create your cluster with `eksctl`, then you can skip this step. By default, `eksctl` creates a role for you.
.. Run the following command to create an IAM trust policy JSON file. 
+
[source,json,subs="verbatim,attributes"]
----
cat >eks-local-cluster-role-trust-policy.json <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF
----
.. Create the Amazon EKS cluster IAM role. To create an IAM role, the link:IAM/latest/UserGuide/id_roles.html#iam-term-principal[IAM principal,type="documentation"] that is creating the role must be assigned the `iam:CreateRole` action (permission).
+
[source,bash,subs="verbatim,attributes"]
----
aws iam create-role --role-name myAmazonEKSLocalClusterRole --assume-role-policy-document file://"eks-local-cluster-role-trust-policy.json"
----
.. Attach the Amazon EKS managed policy named link:aws-managed-policy/latest/reference/AmazonEKSLocalOutpostClusterPolicy.html[AmazonEKSLocalOutpostClusterPolicy,type="documentation"] to the role. To attach an IAM policy to an link:IAM/latest/UserGuide/id_roles.html#iam-term-principal[IAM principal,type="documentation"], the principal that is attaching the policy must be assigned one of the following IAM actions (permissions): `iam:AttachUserPolicy` or `iam:AttachRolePolicy`.
+
[source,bash,subs="verbatim,attributes"]
----
aws iam attach-role-policy --policy-arn {arn-aws}iam::aws:policy/AmazonEKSLocalOutpostClusterPolicy --role-name myAmazonEKSLocalClusterRole
----
. Open the link:eks/home#/clusters[Amazon EKS console,type="console"].
. At the top of the console screen, make sure that you have selected a <<outposts-control-plane-supported-regions,supported {aws} Region>>.
. Choose *Add cluster* and then choose *Create*.
. On the *Configure cluster* page, enter or select values for the following fields:
+
* *Kubernetes control plane location* – Choose {aws} Outposts.
* *Outpost ID* – Choose the ID of the Outpost that you want to create your control plane on.
* *Instance type* – Select an instance type. Only the instance types available in your Outpost are displayed. In the dropdown list, each instance type describes how many nodes the instance type is recommended for. Before choosing an instance type, see <<eks-outposts-capacity-considerations>>. All replicas are deployed using the same instance type. You can't change the instance type after your cluster is created. Three control plane instances are deployed. You can't change this number.
* *Name* – A name for your cluster. It must be unique in your {aws} account. The name can contain only alphanumeric characters (case-sensitive) and hyphens. It must start with an alphanumeric character and can't be longer than 100 characters. The name must be unique within the {aws} Region and {aws} account that you're creating the cluster in. The name must be unique within the {aws} Region and {aws} account that you're creating the cluster in.
* *Kubernetes version* – Choose the Kubernetes version that you want to use for your cluster. We recommend selecting the latest version, unless you need to use an earlier version.
* *Cluster service role* – Choose the Amazon EKS cluster IAM role that you created in a previous step to allow the Kubernetes control plane to manage {aws} resources.
* *Kubernetes cluster administrator access* – If you want the IAM principal (role or user) that's creating the cluster to have administrator access to the Kubernetes objects on the cluster, accept the default (allow). Amazon EKS creates an access entry for the IAM principal and grants cluster administrator permissions to the access entry. For more information about access entries, see <<access-entries>>.
+
If you want a different IAM principal than the principal creating the cluster to have administrator access to Kubernetes cluster objects, choose the disallow option. After cluster creation, any IAM principal that has IAM permissions to create access entries can add an access entries for any IAM principals that need access to Kubernetes cluster objects. For more information about the required IAM permissions, see link:service-authorization/latest/reference/list_amazonelastickubernetesservice.html#amazonelastickubernetesservice-actions-as-permissions[Actions defined by Amazon Elastic Kubernetes Service,type="documentation"] in the Service Authorization Reference. If you choose the disallow option and don't create any access entries, then no IAM principals will have access to the Kubernetes objects on the cluster.  
* *Tags* – (Optional) Add any tags to your cluster. For more information, see <<eks-using-tags>>. When you're done with this page, choose *Next*.
. On the *Specify networking* page, select values for the following fields:
+
* *VPC* – Choose an existing VPC. The VPC must have a sufficient number of IP addresses available for the cluster, any nodes, and other Kubernetes resources that you want to create. Your VPC must meet the requirements in <<outposts-vpc-requirements,VPC requirements and considerations>>.
* *Subnets* – By default, all available subnets in the VPC specified in the previous field are preselected. The subnets that you choose must meet the requirements in <<outposts-subnet-requirements,Subnet requirements and considerations>>.
* *Security groups* – (Optional) Specify one or more security groups that you want Amazon EKS to associate to the network interfaces that it creates. Amazon EKS automatically creates a security group that enables communication between your cluster and your VPC. Amazon EKS associates this security group, and any that you choose, to the network interfaces that it creates. For more information about the cluster security group that Amazon EKS creates, see <<sec-group-reqs>>. You can modify the rules in the cluster security group that Amazon EKS creates. If you choose to add your own security groups, you can't change the ones that you choose after cluster creation. For on-premises hosts to communicate with the cluster endpoint, you must allow inbound traffic from the cluster security group. For clusters that don't have an ingress and egress internet connection (also knows as private clusters), you must do one of the following:
+
** Add the security group associated with required VPC endpoints. For more information about the required endpoints, see <<vpc-subnet-requirements-vpc-endpoints>> in <<subnet-access-to-services,Subnet access to {aws} services>>.
+
** Modify the security group that Amazon EKS created to allow traffic from the security group associated with the VPC endpoints. When you're done with this page, choose *Next*.
. On the *Configure observability* page, you can optionally choose which *Metrics* and *Control plane logging* options that you want to turn on. By default, each log type is turned off.
+
**** For more information on the Prometheus metrics option, see <<turn-on-prometheus-metrics>>.
**** For more information on the *Control plane logging* options, see <<control-plane-logs>>. When you're done with this page, choose *Next*.
. On the *Review and create* page, review the information that you entered or selected on the previous pages. If you need to make changes, choose *Edit*. When you're satisfied, choose *Create*. The *Status* field shows *CREATING* while the cluster is provisioned.
+
Cluster provisioning takes several minutes.

== View your Amazon EKS local cluster

. After your cluster is created, you can view the Amazon EC2 control plane instances that were created.
+
[source,bash,subs="verbatim,attributes"]
----
aws ec2 describe-instances --query 'Reservations[*].Instances[*].{Name:Tags[?Key==`Name`]|[0].Value}' | grep my-cluster-control-plane
----
+
An example output is as follows.
+
[source,bash,subs="verbatim,attributes"]
----
"Name": "my-cluster-control-plane-id1"
"Name": "my-cluster-control-plane-id2"
"Name": "my-cluster-control-plane-id3"
----
+
Each instance is tainted with `node-role.eks-local.amazonaws.com/control-plane` so that no workloads are ever scheduled on the control plane instances. For more information about taints, see https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/[Taints and Tolerations] in the Kubernetes documentation. Amazon EKS continuously monitors the state of local clusters. We perform automatic management actions, such as security patches and repairing unhealthy instances. When local clusters are disconnected from the cloud, we complete actions to ensure that the cluster is repaired to a healthy state upon reconnect.
. If you created your cluster using `eksctl`, then you can skip this step. `eksctl` completes this step for you. Enable `kubectl` to communicate with your cluster by adding a new context to the `kubectl` `config` file. For instructions on how to create and update the file, see <<create-kubeconfig>>.
+
[source,bash,subs="verbatim,attributes"]
----
aws eks update-kubeconfig --region region-code --name my-cluster
----
+
An example output is as follows.
+
[source,bash,subs="verbatim,attributes"]
----
Added new context {arn-aws}eks:region-code:111122223333:cluster/my-cluster to /home/username/.kube/config
----
. To connect to your local cluster's Kubernetes API server, have access to the local gateway for the subnet, or connect from within the VPC. For more information about connecting an Outpost rack to your on-premises network, see link:outposts/latest/userguide/how-racks-work.html[How local gateways for racks work,type="documentation"] in the {aws} Outposts User Guide. If you use Direct VPC Routing and the Outpost subnet has a route to your local gateway, the private IP addresses of the Kubernetes control plane instances are automatically broadcasted over your local network. The local cluster's Kubernetes API server endpoint is hosted in Amazon Route 53 (Route 53). The API service endpoint can be resolved by public DNS servers to the Kubernetes API servers' private IP addresses.  
+
Local clusters' Kubernetes control plane instances are configured with static elastic network interfaces with fixed private IP addresses that don't change throughout the cluster lifecycle. Machines that interact with the Kubernetes API server might not have connectivity to Route 53 during network disconnects. If this is the case, we recommend configuring `/etc/hosts` with the static private IP addresses for continued operations. We also recommend setting up local DNS servers and connecting them to your Outpost. For more information, see the link:outposts/latest/userguide/how-outposts-works.html#dns[{aws} Outposts documentation,type="documentation"]. Run the following command to confirm that communication's established with your cluster.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl get svc
----
+
An example output is as follows.
+
[source,bash,subs="verbatim,attributes"]
----
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.100.0.1   <none>        443/TCP   28h
----
. (Optional) Test authentication to your local cluster when it's in a disconnected state from the {aws} Cloud. For instructions, see <<eks-outposts-network-disconnects>>.


[#outposts-control-plan-internal-resources]
=== Internal resources

Amazon EKS creates the following resources on your cluster. The resources are for Amazon EKS internal use. For proper functioning of your cluster, don't edit or modify these resources.



* The following https://kubernetes.io/docs/reference/glossary/?all=true#term-mirror-pod[mirror Pods]:
+
** `aws-iam-authenticator-[.replaceable]``node-hostname```
** `eks-certificates-controller-[.replaceable]``node-hostname```
** `etcd-[.replaceable]``node-hostname```
** `kube-apiserver-[.replaceable]``node-hostname```
** `kube-controller-manager-[.replaceable]``node-hostname```
** `kube-scheduler-[.replaceable]``node-hostname```
* The following self-managed add-ons:
+
** `kube-system/coredns`
** `kube-system/` `kube-proxy` (not created until you add your first node)
** `kube-system/aws-node` (not created until you add your first node). Local clusters use the Amazon VPC CNI plugin for Kubernetes plugin for cluster networking. Do not change the configuration for control plane instances (Pods named `aws-node-controlplane-*`). There are configuration variables that you can use to change the default value for when the plugin creates new network interfaces. For more information, see the https://github.com/aws/amazon-vpc-cni-k8s/blob/master/README.md[documentation] on GitHub.
* The following services:
+
** `default/kubernetes`
** `kube-system/kube-dns`
* A `PodSecurityPolicy` named `eks.system`
* A `ClusterRole` named `eks:system:podsecuritypolicy`
* A `ClusterRoleBinding` named `eks:system`
* In addition to the <<sec-group-reqs,cluster security group>>, Amazon EKS creates a security group in your {aws} account that's named `eks-local-internal-do-not-use-or-edit-[.replaceable]``cluster-name``-[.replaceable]``uniqueid```. This security group allows traffic to flow freely between Kubernetes components running on the control plane instances.

Recommended next steps:

* <<view-kubernetes-resources-permissions,Grant the IAM principal that created the cluster the required permissions to view Kubernetes resources in the {aws-management-console}>>
* <<grant-k8s-access,Grant IAM entities access to your cluster>>. If you want the entities to view Kubernetes resources in the Amazon EKS console, grant the <<view-kubernetes-resources-permissions,Required permissions>> to the entities.
* <<control-plane-logs,Configure logging for your cluster>>
* Familiarize yourself with what happens during <<eks-outposts-network-disconnects,network disconnects>>.
* <<eks-outposts-self-managed-nodes,Add nodes to your cluster>>
* Consider setting up a backup plan for your `etcd`. Amazon EKS doesn't support automated backup and restore of `etcd` for local clusters. For more information, see https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#backing-up-an-etcd-cluster[Backing up an etcd cluster] in the Kubernetes documentation. The two main options are using `etcdctl` to automate taking snapshots or using Amazon EBS storage volume backup.
