include::../attributes.txt[]

[.topic]
[#eks-outposts-platform-versions]
= Learn Kubernetes and Amazon EKS platform versions for {aws} Outposts
:info_titleabbrev: EKS platform versions

[abstract]
--
Learn the relationship between Amazon EKS and Kubernetes versions available on {aws} Outposts.
--

Local cluster platform versions represent the capabilities of the Amazon EKS cluster on {aws} Outposts. The versions include the components that run on the Kubernetes control plane, which Kubernetes API server flags are enabled. They also include the current Kubernetes patch version. Each Kubernetes minor version has one or more associated platform versions. The platform versions for different Kubernetes minor versions are independent. The platform versions for local clusters and Amazon EKS clusters in the cloud are independent.

When a new Kubernetes minor version is available for local clusters, such as `1.31`, the initial platform version for that Kubernetes minor version starts at `eks-local-outposts.1`. However, Amazon EKS releases new platform versions periodically to enable new Kubernetes control plane settings and to provide security fixes.

When new local cluster platform versions become available for a minor version:



* The platform version number is incremented (`eks-local-outposts.n+1`).
* Amazon EKS automatically updates all existing local clusters to the latest platform version for their corresponding Kubernetes minor version. Automatic updates of existing platform versions are rolled out incrementally. The roll-out process consists of the replacement of the managed Kubernetes control-plane instances running on the Outpost, one at a time, until all 3 instances get replaced by new ones.
* The Kubernetes control-plane instance replacement process will stop progressing if there is risk of service interruption. Amazon EKS will only attempt to replace an instance in case the other 2 Kubernetes control-plane instances are healthy and passing all readiness conditions as a cluster node. 
* A platform version rollout will typically take less than 30 minutes to complete. If a cluster remains on `UPDATING` state for an extended amount of time, see the <<eks-outposts-troubleshooting>> and seek help from {aws} Support. Never manually terminate Kubernetes control-plane instances unless instructed by {aws} Support.
* Amazon EKS might publish a new node AMI with a corresponding patch version. All patch versions are compatible between the Kubernetes control plane and node AMIs for a single Kubernetes minor version.

New platform versions don't introduce breaking changes or cause service interruptions.

Local clusters are always created with the latest available platform version (`eks-local-outposts.n`) for the specified Kubernetes version.

The current and recent platform versions are described in the following tables.

[#outposts-platform-versions-1-31]
== Kubernetes version `1.31`

The following admission controllers are enabled for all `1.31` platform versions: `CertificateApproval`, `CertificateSigning`, `CertificateSubjectRestriction`, `ClusterTrustBundleAttest`, `DefaultIngressClass`, `DefaultStorageClass`, `DefaultTolerationSeconds`, `ExtendedResourceToleration`, `LimitRanger`, `MutatingAdmissionWebhook`, `NamespaceLifecycle`, `NodeRestriction`, `PersistentVolumeClaimResize`, `PodSecurity`, `Priority`, `ResourceQuota`, `RuntimeClass`, `ServiceAccount`, `StorageObjectInUseProtection`, `TaintNodesByCondition`, `ValidatingAdmissionPolicy`, and `ValidatingAdmissionWebhook`.


[cols="1,1,1,1", options="header"]
|===
|Kubernetes version
|Amazon EKS platform version
|Release notes
|Release date

|`1.31.6`
|`eks-local-outposts.1`
|Initial release of Kubernetes version `v1.31` for local Amazon EKS clusters on Outposts.
|April 9, 2025
|===

[#outposts-platform-versions-1-30]
== Kubernetes version `1.30`

The following admission controllers are enabled for all `1.30` platform versions: `CertificateApproval`, `CertificateSigning`, `CertificateSubjectRestriction`, `ClusterTrustBundleAttest`, `DefaultIngressClass`, `DefaultStorageClass`, `DefaultTolerationSeconds`, `ExtendedResourceToleration`, `LimitRanger`, `MutatingAdmissionWebhook`, `NamespaceLifecycle`, `NodeRestriction`, `PersistentVolumeClaimResize`, `PodSecurity`, `Priority`, `ResourceQuota`, `RuntimeClass`, `ServiceAccount`, `StorageObjectInUseProtection`, `TaintNodesByCondition`, `ValidatingAdmissionPolicy`, and `ValidatingAdmissionWebhook`.

[cols="1,1,1,1", options="header"]
|===
|Kubernetes version
|Amazon EKS platform version
|Release notes
|Release date

|`1.30.10`
|`eks-local-outposts.3`
|New platform version with security fixes and enhancements. kube-proxy updated to `v1.30.10`. {aws} IAM Authenticator updated to `v0.6.29`. Amazon VPC CNI plugin for Kubernetes updated to `v1.19.2`. CoreDNS updated to `v1.11.4`. AWS Cloud Controller Manager updated to `v1.30.8`. Bottlerocket version updated to `v1.34.0`.
|March 27, 2025

|`1.30.7`
|`eks-local-outposts.2`
|New platform version with security fixes and enhancements. kube-proxy updated to `v1.30.7`. {aws} IAM Authenticator updated to `v0.6.28`. Amazon VPC CNI plugin for Kubernetes updated to `v1.19.0`. Updated Bottlerocket version to `v1.29.0`.
|January 10, 2025

|`1.30.5`
|`eks-local-outposts.1`
|Initial release of Kubernetes version `v1.30` for local Amazon EKS clusters on Outposts.
|November 13, 2024
|===

[#outposts-platform-versions-1-29]
== Kubernetes version `1.29`

The following admission controllers are enabled for all `1.29` platform versions: `CertificateApproval`, `CertificateSigning`, `CertificateSubjectRestriction`, `ClusterTrustBundleAttest`, `DefaultIngressClass`, `DefaultStorageClass`, `DefaultTolerationSeconds`, `ExtendedResourceToleration`, `LimitRanger`, `MutatingAdmissionWebhook`, `NamespaceLifecycle`, `NodeRestriction`, `PersistentVolumeClaimResize`, `PodSecurity`, `Priority`, `ResourceQuota`, `RuntimeClass`, `ServiceAccount`, `StorageObjectInUseProtection`, `TaintNodesByCondition`, `ValidatingAdmissionPolicy`, and `ValidatingAdmissionWebhook`.

[cols="1,1,1,1", options="header"]
|===
|Kubernetes version
|Amazon EKS platform version
|Release notes
|Release date

|`v1.29.14`
|`eks-local-outposts.6`
|New platform version with security fixes and enhancements. kube-proxy updated to `v1.29.14`. Amazon VPC CNI plugin for Kubernetes updated to `v1.19.2`. CoreDNS updated to `v1.11.4`. AWS Cloud Controller Manager updated to `v1.29.8`. Bottlerocket version updated to `v1.34.0`.
|March 27, 2025

|`v1.29.11`
|`eks-local-outposts.5`
|New platform version with security fixes and enhancements. kube-proxy updated to `v1.29.11`. Amazon VPC CNI plugin for Kubernetes updated to `v1.19.0`. Updated CoreDNS image to `v1.11.3`. Updated Bottlerocket version to `v1.29.0`.
|January 10, 2025

|`1.29.9`
|`eks-local-outposts.4`
|New platform version with security fixes and enhancements. kube-proxy updated to `v1.29.9`. {aws} IAM Authenticator updated to `v0.6.26`. Updated Bottlerocket version to `v1.26.0`.
|November 8, 2024

|`1.29.6`
|`eks-local-outposts.3`
|New platform version with security fixes and enhancements. Updated Bottlerocket version to `v1.22.0`.
|October 22, 2024

|`1.29.6`
|`eks-local-outposts.2`
|New platform version with security fixes and enhancements. Updated Bottlerocket version to `v1.21.0`.
|August 27, 2024

|`1.29.6`
|`eks-local-outposts.1`
|Initial release of Kubernetes version `v1.29` for local Amazon EKS clusters on Outposts.
|August 20, 2024
|===

[#outposts-platform-versions-1-28]
== Kubernetes version `1.28`

The following admission controllers are enabled for all `1.28` platform versions: `CertificateApproval`, `CertificateSigning`, `CertificateSubjectRestriction`, `ClusterTrustBundleAttest`, `DefaultIngressClass`, `DefaultStorageClass`, `DefaultTolerationSeconds`, `ExtendedResourceToleration`, `LimitRanger`, `MutatingAdmissionWebhook`, `NamespaceLifecycle`, `NodeRestriction`, `PersistentVolumeClaimResize`, `PodSecurity`, `Priority`, `ResourceQuota`, `RuntimeClass`, `ServiceAccount`, `StorageObjectInUseProtection`, `TaintNodesByCondition`, `ValidatingAdmissionPolicy`, and `ValidatingAdmissionWebhook`.

[cols="1,1,1,1", options="header"]
|===
|Kubernetes version
|Amazon EKS platform version
|Release notes
|Release date

|`1.28.15`
|`eks-local-outposts.13`
|New platform version with security fixes and enhancements. kube-proxy `v1.28.15` build updated. Amazon VPC CNI plugin for Kubernetes updated to `v1.19.0`. AWS Cloud Controller Manager updated to `v1.28.11`.
|March 27, 2025

|`1.28.15`
|`eks-local-outposts.12`
|New platform version with security fixes and enhancements. kube-proxy updated to `v1.28.15`. Amazon VPC CNI plugin for Kubernetes updated to `v1.19.0`. Updated Bottlerocket version to `v1.29.0`.
|January 10, 2025

|`1.28.14`
|`eks-local-outposts.11`
|New platform version with security fixes and enhancements. kube-proxy updated to `v1.28.14`. {aws} IAM Authenticator updated to `v0.6.26`. Updated CoreDNS image to `v1.11.1`. Updated Bottlerocket version to `v1.26.0`.
|November 8, 2024

|`1.28.10`
|`eks-local-outposts.10`
|New platform version with security fixes and enhancements. Updated Bottlerocket version to `v1.22.0`.
|October 22, 2024

|`1.28.10`
|`eks-local-outposts.9`
|New platform version with security fixes and enhancements. Updated Bottlerocket version to `v1.21.0`.
|August 27, 2024

|`1.28.10`
|`eks-local-outposts.8`
|New platform version with security fixes and enhancements.
|July 30, 2024

|`1.28.10`
|`eks-local-outposts.6`
|New platform version with security fixes and enhancements. kube-proxy updated to `v1.28.10`. {aws} IAM Authenticator updated to `v0.6.20`. Updated Bottlerocket version to `v1.20.2`.
|June 19, 2024

|`1.28.6`
|`eks-local-outposts.5`
|Updated Bottlerocket version to v1.19.3 containing newest bugfixes to support local boot in Outposts.
|April 18, 2024

|`1.28.6`
|`eks-local-outposts.4`
|New platform version with security fixes and enhancements. Restored support or local boot in Outposts. Downgraded Bottlerocket version to `v1.15.1` for compatibility.
|April 2, 2024

|`1.28.6`
|`eks-local-outposts.3`
|New platform version with security fixes and enhancements.
|March 22, 2024

|`1.28.6`
|`eks-local-outposts.2`
|New platform version with security fixes and enhancements. kube-proxy updated to `v1.28.6`. {aws} IAM Authenticator updated to `v0.6.17`. Amazon VPC CNI plugin for Kubernetes downgraded to `v1.13.2` for compatibility reasons. Updated Bottlerocket version to `v1.19.2`.
|March 8, 2024

|`1.28.1`
|`eks-local-outposts.1`
|Initial release of Kubernetes version `v1.28` for local Amazon EKS clusters on Outposts.
|October 4, 2023
|===

[#outposts-platform-versions-1-27]
== Kubernetes version `1.27`

The following admission controllers are enabled for all `1.27` platform versions: `CertificateApproval`, `CertificateSigning`, `CertificateSubjectRestriction`, `ClusterTrustBundleAttest`, `DefaultIngressClass`, `DefaultStorageClass`, `DefaultTolerationSeconds`, `ExtendedResourceToleration`, `LimitRanger`, `MutatingAdmissionWebhook`, `NamespaceLifecycle`, `NodeRestriction`, `PersistentVolumeClaimResize`, `PodSecurity`, `Priority`, `ResourceQuota`, `RuntimeClass`, `ServiceAccount`, `StorageObjectInUseProtection`, `TaintNodesByCondition`, `ValidatingAdmissionPolicy`, and `ValidatingAdmissionWebhook`.

[cols="1,1,1,1", options="header"]
|===
|Kubernetes version
|Amazon EKS platform version
|Release notes
|Release date

|`1.27.16`
|`eks-local-outposts.13`
|New platform version with security fixes and enhancements. Amazon VPC CNI plugin for Kubernetes updated to `v1.19.2`. Bottlerocket version updated to `v1.34.0`.
|March 27, 2025

|`1.27.16`
|`eks-local-outposts.12`
|New platform version with security fixes and enhancements. Amazon VPC CNI plugin for Kubernetes updated to `v1.19.0`. Updated Bottlerocket version to `v1.29.0`.
|January 10, 2025

|`1.27.16`
|`eks-local-outposts.11`
|New platform version with security fixes and enhancements. kube-proxy updated to `v1.27.16`. {aws} IAM Authenticator updated to `v0.6.26`. Updated CoreDNS image to `v1.11.1`. Updated Bottlerocket version to `v1.26.0`.
|November 8, 2024

|`1.27.14`
|`eks-local-outposts.10`
|New platform version with security fixes and enhancements. Updated Bottlerocket version to `v1.22.0`.
|October 22, 2024

|`1.27.14`
|`eks-local-outposts.9`
|New platform version with security fixes and enhancements. Updated Bottlerocket version to `v1.21.0`.
|August 27, 2024

|`1.27.14`
|`eks-local-outposts.8`
|New platform version with security fixes and enhancements.
|July 30, 2024

|`1.27.14`
|`eks-local-outposts.6`
|New platform version with security fixes and enhancements. kube-proxy updated to `v1.27.14`. {aws} IAM Authenticator updated to `v0.6.20`. Updated Bottlerocket version to `v1.20.2`.
|June 19, 2024

|`1.27.10`
|`eks-local-outposts.5`
|New platform version with security fixes and enhancements.
|April 2, 2024

|`1.27.10`
|`eks-local-outposts.4`
|New platform version with security fixes and enhancements. kube-proxy updated to `v1.27.10`. {aws} IAM Authenticator updated to `v0.6.17`. Updated Bottlerocket version to `v1.19.2`.
|March 22, 2024

|`1.27.3`
|`eks-local-outposts.3`
|New platform version with security fixes and enhancements. kube-proxy updated to `v1.27.3`. Amazon VPC CNI plugin for Kubernetes updated to `v1.13.2`.
|July 14, 2023

|`1.27.1`
|`eks-local-outposts.2`
|Updated CoreDNS image to `v1.10.1`.
|June 22, 2023

|`1.27.1`
|`eks-local-outposts.1`
|Initial release of Kubernetes version `1.27` for local Amazon EKS clusters on Outposts.
|May 30, 2023
|===