
include::../attributes.txt[]

[.topic]
[[eks-outposts-network-disconnects,eks-outposts-network-disconnects.title]]
= Prepare local Amazon EKS clusters on {aws} Outposts for network disconnects
:info_titleabbrev: Prepare for network disconnects

[abstract]
--
Learn how to prepare your Amazon EKS local cluster on {aws} Outposts for network disconnects, including x.509 certificate authentication, monitoring, scaling, and storage options.
--

If your local network has lost connectivity with the {aws} Cloud, you can continue to use your local Amazon EKS cluster on an Outpost. This topic covers how you can prepare your local cluster for network disconnects and related considerations.



* Local clusters enable stability and continued operations during temporary, unplanned network disconnects. {aws} Outposts remains a fully connected offering that acts as an extension of the {aws} Cloud in your data center. In the event of network disconnects between your Outpost and {aws} Cloud, we recommend attempting to restore your connection. For instruction, see link:outposts/latest/userguide/network-troubleshoot.html[{aws} Outposts rack network troubleshooting checklist,type="documentation"] in the _{aws} Outposts User Guide_. For more information about how to troubleshoot issues with local clusters, see <<eks-outposts-troubleshooting>>.
* Outposts emit a `ConnectedStatus` metric that you can use to monitor the connectivity state of your Outpost. For more information, see  link:outposts/latest/userguide/outposts-cloudwatch-metrics.html#outposts-metrics[Outposts Metrics,type="documentation"] in the _{aws} Outposts User Guide_.
* Local clusters use IAM as the default authentication mechanism using the https://github.com/kubernetes-sigs/aws-iam-authenticator[{aws} Identity and Access Management authenticator for Kubernetes]. IAM isn't available during network disconnects. So, local clusters support an alternative authentication mechanism using `x.509` certificates that you can use to connect to your cluster during network disconnects. For information about how to obtain and use an `x.509` certificate for your cluster, see <<outposts-network-disconnects-authentication>>.
* If you can't access Route 53 during network disconnects, consider using local DNS servers in your on-premises environment. The [.noloc]`Kubernetes` control plane instances use static IP addresses. You can configure the hosts that you use to connect to your cluster with the endpoint hostname and IP addresses as an alternative to using local DNS servers. For more information, see   link:outposts/latest/userguide/how-outposts-works.html#dns[DNS,type="documentation"] in the _{aws} Outposts User Guide_.
* If you expect increases in application traffic during network disconnects, you can provision spare compute capacity in your cluster when connected to the cloud. Amazon EC2 instances are included in the price of {aws} Outposts. So, running spare instances doesn't impact your {aws} usage cost.
* During network disconnects to enable create, update, and scale operations for workloads, your application's container images must be accessible over the local network and your cluster must have enough capacity. Local clusters don't host a container registry for you. If the [.noloc]`Pods` have previously run on those nodes, container images are cached on the nodes. If you typically pull your application's container images from Amazon ECR in the cloud, consider running a local cache or registry. A local cache or registry is helpful if you require create, update, and scale operations for workload resources during network disconnects.
* Local clusters use Amazon EBS as the default storage class for persistent volumes and the Amazon EBS CSI driver to manage the lifecycle of Amazon EBS persistent volumes. During network disconnects, [.noloc]`Pods` that are backed by Amazon EBS can't be created, updated, or scaled. This is because these operations require calls to the Amazon EBS API in the cloud. If you're deploying stateful workloads on local clusters and require create, update, or scale operations during network disconnects, consider using an alternative storage mechanism.
* Amazon EBS snapshots can't be created or deleted if {aws} Outposts can't access the relevant {aws} in-region APIs (such as the APIs for Amazon EBS or Amazon S3).
* When integrating ALB (Ingress) with {aws} Certificate Manager (ACM), certificates are pushed and stored in memory of the {aws} Outposts ALB Compute instance. Current TLS termination will continue to operate in the event of a disconnect from the {aws} Region. Mutating operations in this context will fail (such as new ingress definitions, new ACM based certificates API operations, ALB compute scale, or certificate rotation). For more information, see link:acm/latest/userguide/troubleshooting-renewal.html[Troubleshooting managed certificate renewal,type="documentation"] in the _{aws} Certificate Manager User Guide_.
* The Amazon EKS control plane logs are cached locally on the [.noloc]`Kubernetes` control plane instances during network disconnects. Upon reconnect, the logs are sent to CloudWatch Logs in the parent {aws} Region. You can use https://prometheus.io/[Prometheus], https://grafana.com/[Grafana], or Amazon EKS partner solutions to monitor the cluster locally using the [.noloc]`Kubernetes` API server's metrics endpoint or using [.noloc]`Fluent Bit` for logs.
* If you're using the [.noloc]`{aws} Load Balancer Controller` on Outposts for application traffic, existing [.noloc]`Pods` fronted by the [.noloc]`{aws} Load Balancer Controller` continue to receive traffic during network disconnects. New [.noloc]`Pods` created during network disconnects don't receive traffic until the Outpost is reconnected to the {aws} Cloud. Consider setting the replica count for your applications while connected to the {aws} Cloud to accommodate your scaling needs during network disconnects.
* The [.noloc]`Amazon VPC CNI plugin for Kubernetes` defaults to https://aws.github.io/aws-eks-best-practices/networking/vpc-cni/#overview[secondary IP mode]. It's configured with `WARM_ENI_TARGET`=``1``, which allows the plugin to keep "a full elastic network interface" of available IP addresses available. Consider changing `WARM_ENI_TARGET`, `WARM_IP_TARGET`, and `MINIMUM_IP_TARGET` values according to your scaling needs during a disconnected state. For more information, see the https://github.com/aws/amazon-vpc-cni-k8s/blob/master/README.md[readme] file for the plugin on GitHub. For a list of the maximum number of [.noloc]`Pods` that's supported by each instance type, see the https://github.com/aws/amazon-vpc-cni-k8s/blob/master/misc/eni-max-pods.txt[eni-max-pods.txt] file on GitHub.


[[outposts-network-disconnects-authentication,outposts-network-disconnects-authentication.title]]
== Authenticating to your local cluster during a network disconnect

[abstract]
--
Learn how to work with your cluster during a network disconnect.
--

{aws} Identity and Access Management (IAM) isn't available during network disconnects. You can't authenticate to your local cluster using IAM credentials while disconnected. However, you can connect to your cluster over your local network using `x509` certificates when disconnected. You need to download and store a client `X509` certificate to use during disconnects. In this topic, you learn how to create and use the certificate to authenticate to your cluster when it's in a disconnected state.

. Create a certificate signing request.
+
.. Generate a certificate signing request.
+
[source,bash,subs="verbatim,attributes"]
----
openssl req -new -newkey rsa:4096 -nodes -days 365 \
    -keyout admin.key -out admin.csr -subj "/CN=admin"
----
.. Create a certificate signing request in [.noloc]`Kubernetes`.
+
[source,bash,subs="verbatim,attributes"]
----
BASE64_CSR=$(cat admin.csr | base64 -w 0)
cat << EOF > admin-csr.yaml
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: admin-csr
spec:
  signerName: kubernetes.io/kube-apiserver-client
  request: ${BASE64_CSR}
  usages:
  - client auth
EOF
----
. Create a certificate signing request using `kubectl`.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl create -f admin-csr.yaml
----
. Check the status of the certificate signing request.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl get csr admin-csr
----
+
An example output is as follows.
+
[source,bash,subs="verbatim,attributes"]
----
NAME       AGE   REQUESTOR                       CONDITION
admin-csr  11m   kubernetes-admin                Pending
----
+
[.noloc]`Kubernetes` created the certificate signing request.
. Approve the certificate signing request.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl certificate approve admin-csr
----
. Recheck the certificate signing request status for approval.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl get csr admin-csr
----
+
An example output is as follows.
+
[source,bash,subs="verbatim,attributes"]
----
NAME       AGE   REQUESTOR                     CONDITION
admin-csr  11m   kubernetes-admin              Approved
----
. Retrieve and verify the certificate.
+
.. Retrieve the certificate.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl get csr admin-csr -o jsonpath='{.status.certificate}' | base64 --decode > admin.crt
----
.. Verify the certificate.
+
[source,bash,subs="verbatim,attributes"]
----
cat admin.crt
----
. Create a cluster role binding for an `admin` user.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl create clusterrolebinding admin --clusterrole=cluster-admin \
    --user=admin --group=system:masters
----
. Generate a user-scoped kubeconfig for a disconnected state. 
+
You can generate a `kubeconfig` file using the downloaded `admin` certificates. Replace [.replaceable]`my-cluster` and [.replaceable]`apiserver-endpoint` in the following commands.
+
[source,bash,subs="verbatim,attributes"]
----
aws eks describe-cluster --name my-cluster \
    --query "cluster.certificateAuthority" \
    --output text | base64 --decode > ca.crt
----
+
[source,bash,subs="verbatim,attributes"]
----
kubectl config --kubeconfig admin.kubeconfig set-cluster my-cluster \
    --certificate-authority=ca.crt --server apiserver-endpoint --embed-certs
----
+
[source,bash,subs="verbatim,attributes"]
----
kubectl config --kubeconfig admin.kubeconfig set-credentials admin \
    --client-certificate=admin.crt --client-key=admin.key --embed-certs
----
+
[source,bash,subs="verbatim,attributes"]
----
kubectl config --kubeconfig admin.kubeconfig set-context admin@my-cluster \
    --cluster my-cluster --user admin
----
+
[source,bash,subs="verbatim,attributes"]
----
kubectl config --kubeconfig admin.kubeconfig use-context admin@my-cluster
----
. View your `kubeconfig` file.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl get nodes --kubeconfig admin.kubeconfig
----
. If you have services already in production on your Outpost, skip this step. If Amazon EKS is the only service running on your Outpost and the Outpost isn't currently in production, you can simulate a network disconnect. Before you go into production with your local cluster, simulate a disconnect to make sure that you can access your cluster when it's in a disconnected state. 
+
.. Apply firewall rules on the networking devices that connect your Outpost to the {aws} Region. This disconnects the service link of the Outpost. You can't create any new instances. Currently running instances lose connectivity to the {aws} Region and the internet.
.. You can test the connection to your local cluster while disconnected using the `x509` certificate. Make sure to change your `kubeconfig` to the `admin.kubeconfig` that you created in a previous step. Replace [.replaceable]`my-cluster` with the name of your local cluster.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl config use-context admin@my-cluster --kubeconfig admin.kubeconfig
----

+
If you notice any issues with your local clusters while they're in a disconnected state, we recommend opening a support ticket.
