include::../../attributes.txt[]

[.topic]
[#associate-service-account-role]
= Assign IAM roles to Kubernetes service accounts
:info_titleabbrev: Assign IAM role

[abstract]
--
Discover how to configure a Kubernetes service account to assume an IAM role, enabling Pods to securely access {aws} services with granular permissions. 
--

This topic covers how to configure a Kubernetes service account to assume an {aws} Identity and Access Management (IAM) role. Any Pods that are configured to use the service account can then access any {aws} service that the role has permissions to access.

== Prerequisites

* An existing cluster. If you don't have one, you can create one by following one of the guides in <<getting-started>>.
* An existing IAM OpenID Connect (OIDC) provider for your cluster. To learn if you already have one or how to create one, see <<enable-iam-roles-for-service-accounts>>.
* Version `2.12.3` or later or version `1.27.160` or later of the {aws} Command Line Interface ({aws} CLI) installed and configured on your device or {aws} CloudShell. To check your current version, use `aws --version | cut -d / -f2 | cut -d ' ' -f1`. Package managers such `yum`, `apt-get`, or Homebrew for macOS are often several versions behind the latest version of the {aws} CLI. To install the latest version, see link:cli/latest/userguide/cli-chap-install.html[Installing, updating, and uninstalling the {aws} CLI,type="documentation"] and link:cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-config[Quick configuration with aws configure,type="documentation"] in the _{aws} Command Line Interface User Guide_. The {aws} CLI version that is installed in {aws} CloudShell might also be several versions behind the latest version. To update it, see link:cloudshell/latest/userguide/vm-specs.html#install-cli-software[Installing {aws} CLI to your home directory,type="documentation"] in the _{aws} CloudShell User Guide_.
* The `kubectl` command line tool is installed on your device or {aws} CloudShell. The version can be the same as or up to one minor version earlier or later than the Kubernetes version of your cluster. For example, if your cluster version is `1.29`, you can use `kubectl` version `1.28`, `1.29`, or `1.30` with it. To install or upgrade `kubectl`, see <<install-kubectl>>.
* An existing `kubectl` `config` file that contains your cluster configuration. To create a `kubectl` `config` file, see <<create-kubeconfig>>.


[#irsa-associate-role-procedure]
== Step 1: Create IAM Policy

If you want to associate an existing IAM policy to your IAM role, skip to the next step.


. Create an IAM policy. You can create your own policy, or copy an {aws} managed policy that already grants some of the permissions that you need and customize it to your specific requirements. For more information, see link:IAM/latest/UserGuide/access_policies_create.html[Creating IAM policies,type="documentation"] in the _IAM User Guide_.
+
. Create a file that includes the permissions for the {aws} services that you want your Pods to access. For a list of all actions for all {aws} services, see the link:service-authorization/latest/reference/[Service Authorization Reference,type="documentation"].
+
You can run the following command to create an example policy file that allows read-only access to an Amazon S3 bucket. You can optionally store configuration information or a bootstrap script in this bucket, and the containers in your Pod can read the file from the bucket and load it into your application. If you want to create this example policy, copy the following contents to your device. Replace [.replaceable]`my-pod-secrets-bucket` with your bucket name and run the command. 
+
[source,json,subs="verbatim,attributes"]
----
cat >my-policy.json <<EOF
{
    "Version": "2012-10-17",&TCX5-2025-waiver;{tcx5-waiver}
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:GetObject",
            "Resource": "{arn-aws}s3:::my-pod-secrets-bucket"
        }
    ]
}
EOF
----
. Create the IAM policy.
+
[source,bash,subs="verbatim,attributes"]
----
aws iam create-policy --policy-name my-policy --policy-document file://my-policy.json
----

== Step 2: Create and associate IAM Role

Create an IAM role and associate it with a Kubernetes service account. You can use either `eksctl` or the {aws} CLI.

=== Create and associate role (eksctl)

This `eksctl` command creates a Kubernetes service account in the specified namespace, creates an IAM role (if it doesn't exist) with the specified name, attaches an existing IAM policy ARN to the role, and annotates the service account with the IAM role ARN. Be sure to replace the sample placeholder values in this command with your specific values. To install or update `eksctl`, see https://eksctl.io/installation[Installation] in the `eksctl` documentation.

[source,bash,subs="verbatim,attributes"]
----
eksctl create iamserviceaccount --name my-service-account --namespace default --cluster my-cluster --role-name my-role \
    --attach-policy-arn {arn-aws}iam::111122223333:policy/my-policy --approve
----

IMPORTANT: If the role or service account already exist, the previous command might fail. `eksctl` has different options that you can provide in those situations. For more information run `eksctl create iamserviceaccount --help`.


=== Create and associate role ({aws} CLI)

If you have an existing Kubernetes service account that you want to assume an IAM role, then you can skip this step.

. Create a Kubernetes service account. Copy the following contents to your device. Replace [.replaceable]`my-service-account` with your desired name and [.replaceable]`default` with a different namespace, if necessary. If you change [.replaceable]`default`, the namespace must already exist.
+
[source,yaml,subs="verbatim,attributes"]
----
cat >my-service-account.yaml <<EOF
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: default
EOF
kubectl apply -f my-service-account.yaml
----
. Set your {aws} account ID to an environment variable with the following command.
+
[source,bash,subs="verbatim,attributes"]
----
account_id=$(aws sts get-caller-identity --query "Account" --output text)
----
. Set your cluster's OIDC identity provider to an environment variable with the following command. Replace [.replaceable]`my-cluster` with the name of your cluster.
+
[source,bash,subs="verbatim,attributes"]
----
oidc_provider=$(aws eks describe-cluster --name my-cluster --region $AWS_REGION --query "cluster.identity.oidc.issuer" --output text | sed -e "s/^https:\/\///")
----
. Set variables for the namespace and name of the service account. Replace [.replaceable]`my-service-account` with the Kubernetes service account that you want to assume the role. Replace [.replaceable]`default` with the namespace of the service account.
+
[source,bash,subs="verbatim,attributes"]
----
export namespace=default
export service_account=my-service-account
----
. Run the following command to create a trust policy file for the IAM role. If you want to allow all service accounts within a namespace to use the role, then copy the following contents to your device. Replace [.replaceable]`StringEquals` with `StringLike` and replace [.replaceable]`$service_account` with `{asterisk}`. You can add multiple entries in the `StringEquals` or `StringLike` conditions to allow multiple service accounts or namespaces to assume the role. To allow roles from a different {aws} account than the account that your cluster is in to assume the role, see <<cross-account-access>> for more information.
+
[source,json,subs="verbatim,attributes"]
----
cat >trust-relationship.json <<EOF
{
  "Version": "2012-10-17",&TCX5-2025-waiver;{tcx5-waiver}
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "{arn-aws}iam::$account_id:oidc-provider/$oidc_provider"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "$oidc_provider:aud": "sts.amazonaws.com",
          "$oidc_provider:sub": "system:serviceaccount:$namespace:$service_account"
        }
      }
    }
  ]
}
EOF
----
. Create the role. Replace [.replaceable]`my-role` with a name for your IAM role, and [.replaceable]`my-role-description` with a description for your role.
+
[source,bash,subs="verbatim,attributes"]
----
aws iam create-role --role-name my-role --assume-role-policy-document file://trust-relationship.json --description "my-role-description"
----
. Attach an IAM policy to your role. Replace [.replaceable]`my-role` with the name of your IAM role and [.replaceable]`my-policy` with the name of an existing policy that you created.
+
[source,bash,subs="verbatim,attributes"]
----
aws iam attach-role-policy --role-name my-role --policy-arn={arn-aws}iam::$account_id:policy/my-policy
----
. Annotate your service account with the Amazon Resource Name (ARN) of the IAM role that you want the service account to assume. Replace [.replaceable]`my-role` with the name of your existing IAM role. Suppose that you allowed a role from a different {aws} account than the account that your cluster is in to assume the role in a previous step. Then, make sure to specify the {aws} account and role from the other account. For more information, see <<cross-account-access>>.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl annotate serviceaccount -n $namespace $service_account eks.amazonaws.com/role-arn={arn-aws}iam::$account_id:role/my-role
----
. (Optional) <<configure-sts-endpoint,Configure the {aws} Security Token Service endpoint for a service account>>. {aws} recommends using a regional {aws} STS endpoint instead of the global endpoint. This reduces latency, provides built-in redundancy, and increases session token validity.


[#irsa-confirm-role-configuration]
== Step 3: Confirm configuration
. Confirm that the IAM role's trust policy is configured correctly.
+
[source,bash,subs="verbatim,attributes"]
----
aws iam get-role --role-name my-role --query Role.AssumeRolePolicyDocument
----
+
An example output is as follows.
+
[source,json,subs="verbatim,attributes",role="nocopy"]
----
{
    "Version": "2012-10-17",&TCX5-2025-waiver;{tcx5-waiver}
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "{arn-aws}iam::111122223333:oidc-provider/oidc.eks.region-code.amazonaws.com/id/EXAMPLED539D4633E53DE1B71EXAMPLE"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.region-code.amazonaws.com/id/EXAMPLED539D4633E53DE1B71EXAMPLE:sub": "system:serviceaccount:default:my-service-account",
                    "oidc.eks.region-code.amazonaws.com/id/EXAMPLED539D4633E53DE1B71EXAMPLE:aud": "sts.amazonaws.com"
                }
            }
        }
    ]
}
----
. Confirm that the policy that you attached to your role in a previous step is attached to the role.
+
[source,bash,subs="verbatim,attributes"]
----
aws iam list-attached-role-policies --role-name my-role --query "AttachedPolicies[].PolicyArn" --output text
----
+
An example output is as follows.
+
[source,bash,subs="verbatim,attributes",role="nocopy"]
----
{arn-aws}iam::111122223333:policy/my-policy
----
. Set a variable to store the Amazon Resource Name (ARN) of the policy that you want to use. Replace [.replaceable]`my-policy` with the name of the policy that you want to confirm permissions for.
+
[source,bash,subs="verbatim,attributes"]
----
export policy_arn={arn-aws}iam::111122223333:policy/my-policy
----
. View the default version of the policy.
+
[source,bash,subs="verbatim,attributes"]
----
aws iam get-policy --policy-arn $policy_arn
----
+
An example output is as follows.
+
[source,json,subs="verbatim,attributes",role="nocopy"]
----
{
    "Policy": {
        "PolicyName": "my-policy",
        "PolicyId": "EXAMPLEBIOWGLDEXAMPLE",
        "Arn": "{arn-aws}iam::111122223333:policy/my-policy",
        "Path": "/",
        "DefaultVersionId": "v1",
        [...]
    }
}
----
. View the policy contents to make sure that the policy includes all the permissions that your Pod needs. If necessary, replace [.replaceable]`1` in the following command with the version that's returned in the previous output.
+
[source,bash,subs="verbatim,attributes"]
----
aws iam get-policy-version --policy-arn $policy_arn --version-id v1
----
+
An example output is as follows.
+
[source,json,subs="verbatim,attributes",role="nocopy"]
----
{
    "Version": "2012-10-17",&TCX5-2025-waiver;{tcx5-waiver}
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:GetObject",
            "Resource": "{arn-aws}s3:::my-pod-secrets-bucket"
        }
    ]
}
----
+
If you created the example policy in a previous step, then your output is the same. If you created a different policy, then the [.replaceable]`example` content is different.
. Confirm that the Kubernetes service account is annotated with the role.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl describe serviceaccount my-service-account -n default
----
+
An example output is as follows.
+
[source,bash,subs="verbatim,attributes",role="nocopy"]
----
Name:                my-service-account
Namespace:           default
Annotations:         eks.amazonaws.com/role-arn: {arn-aws}iam::111122223333:role/my-role
Image pull secrets:  <none>
Mountable secrets:   my-service-account-token-qqjfl
Tokens:              my-service-account-token-qqjfl
[...]
----


== Next steps

* <<pod-configuration>>
