include::../../attributes.txt[]

[.topic]
[#cross-account-access]
= Authenticate to another account with IRSA
:info_titleabbrev: Cross-account IAM

[abstract]
--
Learn how to configure cross-account IAM permissions for Amazon EKS clusters by creating an identity provider from another account's cluster or using chained AssumeRole operations, enabling secure access to {aws} resources across multiple accounts.
--

You can configure cross-account IAM permissions either by creating an identity provider from another account's cluster or by using chained `AssumeRole` operations. In the following examples, _Account A_ owns an Amazon EKS cluster that supports IAM roles for service accounts. Pods that are running on that cluster must assume IAM permissions from _Account B_.

.Create an identity provider from another account's cluster
====

====

====

In this example, Account A provides Account B with the OpenID Connect (OIDC) issuer URL from their cluster. Account B follows the instructions in <<enable-iam-roles-for-service-accounts,Create an IAM OIDC provider for your cluster>> and <<associate-service-account-role>> using the OIDC issuer URL from Account A's cluster. Then, a cluster administrator annotates the service account in Account A's cluster to use the role from Account B ([.replaceable]`444455556666`).

[source,yaml,subs="verbatim,attributes"]
----
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {arn-aws}iam::444455556666:role/account-b-role
----

====

.Use chained `AssumeRole` operations
====

====

====

In this example, Account B creates an IAM policy with the permissions to give to Pods in Account A's cluster. Account B ([.replaceable]`444455556666`) attaches that policy to an IAM role with a trust relationship that allows `AssumeRole` permissions to Account A ([.replaceable]`111122223333`).

[source,json,subs="verbatim,attributes"]
----
include::iam_snippet:539114bb-b8e0-44ba-b4cc-2dd62108ef64[]
----

Account A creates a role with a trust policy that gets credentials from the identity provider created with the cluster's OIDC issuer address.

[source,json,subs="verbatim,attributes"]
----
include::iam_snippet:0436d765-c970-4491-887b-65c0f585250e[]
----

Account A attaches a policy to that role with the following permissions to assume the role that Account B created.

[source,json,subs="verbatim,attributes"]
----
include::iam_snippet:01ba2728-97d1-4049-a0eb-fa44b1f63ca6[]
----

The application code for Pods to assume Account B's role uses two profiles: `account_b_role` and `account_a_role`. The `account_b_role` profile uses the `account_a_role` profile as its source. For the {aws} CLI, the `~/.aws/config` file is similar to the following.

[source,none,subs="verbatim,attributes"]
----
[profile account_b_role]
source_profile = account_a_role
role_arn={arn-aws}iam::444455556666:role/account-b-role

[profile account_a_role]
web_identity_token_file = /var/run/secrets/eks.amazonaws.com/serviceaccount/token 
role_arn={arn-aws}iam::111122223333:role/account-a-role
----

To specify chained profiles for other {aws} SDKs, consult the documentation for the SDK that you're using. For more information, see link:developer/tools/[Tools to Build on {aws},type="marketing"].

====
