[.topic]
[#enable-iam-roles-for-service-accounts]
= Create an IAM [.noloc]`OIDC` provider for your cluster
:info_titleabbrev: IAM OIDC provider

include::../../attributes.txt[]

[abstract]
--
Learn how to create an {aws} Identity and Access Management [.noloc]`OpenID Connect` provider for your cluster.
--

Your cluster has an https://openid.net/connect/[OpenID Connect] ([.noloc]`OIDC`) issuer URL associated with it. To use {aws} Identity and Access Management (IAM) roles for service accounts, an IAM [.noloc]`OIDC` provider must exist for your cluster's [.noloc]`OIDC` issuer URL.



* An existing Amazon EKS cluster. To deploy one, see <<getting-started>>.
* Version `2.12.3` or later or version `1.27.160` or later of the {aws} Command Line Interface ({aws} CLI) installed and configured on your device or {aws} CloudShell. To check your current version, use `aws --version | cut -d / -f2 | cut -d ' ' -f1`. Package managers such `yum`, `apt-get`, or [.noloc]`Homebrew` for [.noloc]`macOS` are often several versions behind the latest version of the {aws} CLI. To install the latest version, see link:cli/latest/userguide/cli-chap-install.html[Installing, updating, and uninstalling the {aws} CLI,type="documentation"] and  link:cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-config[Quick configuration with aws configure,type="documentation"] in the _{aws} Command Line Interface User Guide_. The {aws} CLI version that is installed in {aws} CloudShell might also be several versions behind the latest version. To update it, see  link:cloudshell/latest/userguide/vm-specs.html#install-cli-software[Installing {aws} CLI to your home directory,type="documentation"] in the _{aws} CloudShell User Guide_.
* The `kubectl` command line tool is installed on your device or {aws} CloudShell. The version can be the same as or up to one minor version earlier or later than the [.noloc]`Kubernetes` version of your cluster. For example, if your cluster version is `1.29`, you can use `kubectl` version `1.28`, `1.29`, or `1.30` with it. To install or upgrade `kubectl`, see <<install-kubectl>>.
* An existing `kubectl` `config` file that contains your cluster configuration. To create a `kubectl` `config` file, see <<create-kubeconfig>>.

You can create an IAM [.noloc]`OIDC` provider for your cluster using `eksctl` or the {aws-management-console}.

== Create OIDC provider (eksctl)

. Version `{eksctl-min-version}` or later of the `eksctl` command line tool installed on your device or {aws} CloudShell. To install or update `eksctl`, see https://eksctl.io/installation[Installation] in the `eksctl` documentation.
+
. Determine the [.noloc]`OIDC` issuer ID for your cluster.
+
Retrieve your cluster's [.noloc]`OIDC` issuer ID and store it in a variable. Replace [.replaceable]`my-cluster` with your own value.
+
[source,bash,subs="verbatim,attributes"]
----
cluster_name=my-cluster
----
[source,bash,subs="verbatim,attributes"]
----
oidc_id=$(aws eks describe-cluster --name $cluster_name --query "cluster.identity.oidc.issuer" --output text | cut -d '/' -f 5)
----
[source,bash,subs="verbatim,attributes"]
----
echo $oidc_id
----
. Determine whether an IAM [.noloc]`OIDC` provider with your cluster's issuer ID is already in your account.
+
[source,bash,subs="verbatim,attributes"]
----
aws iam list-open-id-connect-providers | grep $oidc_id | cut -d "/" -f4
----
+
If output is returned, then you already have an IAM [.noloc]`OIDC` provider for your cluster and you can skip the next step. If no output is returned, then you must create an IAM [.noloc]`OIDC` provider for your cluster.
. Create an IAM [.noloc]`OIDC` identity provider for your cluster with the following command.
+
[source,bash,subs="verbatim,attributes"]
----
eksctl utils associate-iam-oidc-provider --cluster $cluster_name --approve
----
+
NOTE: If you enabled the EKS VPC endpoint, the EKS OIDC service endpoint couldn't be accessed from inside that VPC. Consequently, your operations such as creating an OIDC provider with `eksctl` in the VPC will not work and will result in a timeout when attempting to request `https://oidc.eks.[.replaceable]``region``.amazonaws.com`. An example error message follows:

[source,bash,subs="verbatim,attributes"]
----
** server cant find oidc.eks.region.amazonaws.com: NXDOMAIN
----

To complete this step, you can run the command outside the VPC, for example in {aws} CloudShell or on a computer connected to the internet. Alternatively, you can create a split-horizon conditional resolver in the VPC, such as Route 53 Resolver to use a different resolver for the OIDC Issuer URL and not use the VPC DNS for it. For an example of conditional forwarding in [.noloc]`CoreDNS`, see the https://github.com/aws/containers-roadmap/issues/2038[Amazon EKS feature request] on [.noloc]`GitHub`.


== Create OIDC provider ({aws} Console)

. Open the link:eks/home#/clusters[Amazon EKS console,type="console"].
. In the left pane, select *Clusters*, and then select the name of your cluster on the  *Clusters* page.
. In the *Details* section on the  *Overview* tab, note the value of the  *OpenID Connect provider URL*.
. Open the IAM console at https://console.aws.amazon.com/iam/.
. In the left navigation pane, choose *Identity Providers* under  *Access management*. If a  *Provider* is listed that matches the URL for your cluster, then you already have a provider for your cluster. If a provider isn't listed that matches the URL for your cluster, then you must create one.
. To create a provider, choose *Add provider*.
. For *Provider type*, select  *[.noloc]`OpenID Connect`*.
. For *Provider URL*, enter the [.noloc]`OIDC` provider URL for your cluster.
. For *Audience*, enter `sts.amazonaws.com`.
. (Optional) Add any tags, for example a tag to identify which cluster is for this provider.
. Choose *Add provider*.


Next step: 
<<associate-service-account-role>>


📝 https://github.com/search?q=repo:awsdocs/amazon-eks-user-guide+&#91;&#91;enable-iam-roles-for-service-accounts,&type=code[Edit this page on GitHub]