include::../../attributes.txt[]

[.topic]
[#iam-roles-for-service-accounts-minimum-sdk]
= Use IRSA with the {aws} SDK
:info_titleabbrev: Supported SDKs

.Using the credentials
To use the credentials from IAM roles for service accounts (IRSA), your code can use any {aws} SDK to create a client for an {aws} service with an SDK, and by default the SDK searches in a chain of locations for {aws} Identity and Access Management credentials to use. The IAM roles for service accounts credentials will be used if you don't specify a credential provider when you create the client or otherwise initialized the SDK.

This works because IAM roles for service accounts have been added as a step in the default credential chain. If your workloads currently use credentials that are earlier in the chain of credentials, those credentials will continue to be used even if you configure an IAM roles for service accounts for the same workload.

The SDK automatically exchanges the service account OIDC token for temporary credentials from {aws} Security Token Service by using the `AssumeRoleWithWebIdentity` action. Amazon EKS and this SDK action continue to rotate the temporary credentials by renewing them before they expire.

When using <<iam-roles-for-service-accounts,IAM roles for service accounts>>, the containers in your Pods must use an {aws} SDK version that supports assuming an IAM role through an OpenID Connect web identity token file. Make sure that you're using the following versions, or later, for your {aws} SDK:



* Java (Version 2) – https://github.com/aws/aws-sdk-java-v2/releases/tag/2.10.11[2.10.11]
* Java – https://github.com/aws/aws-sdk-java/releases/tag/1.11.704[1.11.704]
* Go – https://github.com/aws/aws-sdk-go/releases/tag/v1.23.13[1.23.13]
* Python (Boto3) – https://github.com/boto/boto3/releases/tag/1.9.220[1.9.220]
* Python (botocore) – https://github.com/boto/botocore/releases/tag/1.12.200[1.12.200]
* {aws} CLI – https://github.com/aws/aws-cli/releases/tag/1.16.232[1.16.232]
* Node – https://github.com/aws/aws-sdk-js/releases/tag/v2.525.0[2.525.0] and https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.27.0[3.27.0]
* Ruby – https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-core/CHANGELOG.md#3580-2019-07-01[3.58.0]
* {cpp} – https://github.com/aws/aws-sdk-cpp/releases/tag/1.7.174[1.7.174]
* .NET – https://github.com/aws/aws-sdk-net/releases/tag/3.3.659.1[3.3.659.1] – You must also include `AWSSDK.SecurityToken`.
* PHP – https://github.com/aws/aws-sdk-php/releases/tag/3.110.7[3.110.7]

Many popular Kubernetes add-ons, such as the https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler[Cluster Autoscaler], the <<aws-load-balancer-controller,Route internet traffic with {aws} Load Balancer Controller>>, and the <<cni-iam-role,Amazon VPC CNI plugin for Kubernetes>> support IAM roles for service accounts.

To ensure that you're using a supported SDK, follow the installation instructions for your preferred SDK at link:tools/[Tools to Build on {aws},type="marketing"] when you build your containers. 