include::../../attributes.txt[]

[.topic]
[#iam-roles-for-service-accounts]
= IAM roles for service accounts
:info_titleabbrev: Credentials with IRSA

[abstract]
--
Learn how applications in your Pods can access {aws} services.
--

Applications in a Pod's containers can use an {aws} SDK or the {aws} CLI to make API requests to {aws} services using {aws} Identity and Access Management (IAM) permissions. Applications must sign their {aws} API requests with {aws} credentials. *IAM roles for service accounts (IRSA)* provide the ability to manage credentials for your applications, similar to the way that Amazon EC2 instance profiles provide credentials to Amazon EC2 instances. Instead of creating and distributing your {aws} credentials to the containers or using the Amazon EC2 instance's role, you associate an IAM role with a Kubernetes service account and configure your Pods to use the service account. You can't use IAM roles for service accounts with <<eks-outposts-local-cluster-overview,local clusters for Amazon EKS on {aws} Outposts>>.

IAM roles for service accounts provide the following benefits:

* *Least privilege*
 – You can scope IAM permissions to a service account, and only Pods that use that service account have access to those permissions. This feature also eliminates the need for third-party solutions such as `kiam` or `kube2iam`.
* *Credential isolation*
 – When access to the link:AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html[Amazon EC2 Instance Metadata Service (IMDS),type="documentation"] is restricted, a Pod's containers can only retrieve credentials for the IAM role that's associated with the service account that the container uses. A container never has access to credentials that are used by other containers in other Pods. If IMDS is not restricted, the Pod's containers also have access to the <<create-node-role,Amazon EKS node IAM role>> and the containers may be able to gain access to credentials of IAM roles of other Pods on the same node. For more information, see link:eks/latest/best-practices/identity-and-access-management.html#_identities_and_credentials_for_eks_pods_recommendations[Restrict access to the instance profile assigned to the worker node,type="documentation"].

[NOTE]
====
Pods configured with `hostNetwork: true` will always have IMDS access, but the AWS SDKs and CLI will use IRSA credentials when enabled.
====

* *Auditability*
  – Access and event logging is available through {aws} CloudTrail to help ensure retrospective auditing.

IMPORTANT: Containers are not a security boundary, and the use of IAM roles for service accounts does not change this. Pods assigned to the same node will share a kernel and potentially other resources depending on your Pod configuration. While Pods running on separate nodes will be isolated at the compute layer, there are node applications that have additional permissions in the Kubernetes API beyond the scope of an individual instance. Some examples are `kubelet`, `kube-proxy`, CSI storage drivers, or your own Kubernetes applications.

Enable IAM roles for service accounts by completing the following procedures:

. <<enable-iam-roles-for-service-accounts,Create an IAM OIDC provider for your cluster>> – You only complete this procedure once for each cluster.
+
[NOTE]
====
If you enabled the EKS VPC endpoint, the EKS OIDC service endpoint couldn't be accessed from inside that VPC. Consequently, your operations such as creating an OIDC provider with `eksctl` in the VPC will not work and will result in a timeout when attempting to request `https://oidc.eks.[.replaceable]``region``.amazonaws.com`. An example error message follows:

[source,bash,subs="verbatim,attributes"]
----
server cant find oidc.eks.region.amazonaws.com: NXDOMAIN
----

To complete this step, you can run the command outside the VPC, for example in {aws} CloudShell or on a computer connected to the internet. Alternatively, you can create a split-horizon conditional resolver in the VPC, such as Route 53 Resolver to use a different resolver for the OIDC Issuer URL and not use the VPC DNS for it. For an example of conditional forwarding in CoreDNS, see the https://github.com/aws/containers-roadmap/issues/2038[Amazon EKS feature request] on GitHub.
====

. <<associate-service-account-role,Assign IAM roles to Kubernetes service accounts>> – Complete this procedure for each unique set of permissions that you want an application to have.

. <<pod-configuration,Configure Pods to use a Kubernetes service account>> – Complete this procedure for each Pod that needs access to {aws} services.

. <<iam-roles-for-service-accounts-minimum-sdk,Use IRSA with the {aws} SDK>> – Confirm that the workload uses an {aws} SDK of a supported version and that the workload uses the default credential chain.


[#irsa-oidc-background]
== IAM, Kubernetes, and OpenID Connect (OIDC) background information

In 2014, {aws} Identity and Access Management added support for federated identities using OpenID Connect (OIDC). This feature allows you to authenticate {aws} API calls with supported identity providers and receive a valid OIDC JSON web token (JWT). You can pass this token to the {aws} STS `AssumeRoleWithWebIdentity` API operation and receive IAM temporary role credentials. You can use these credentials to interact with any {aws} service, including Amazon S3 and DynamoDB. 

Each JWT token is signed by a signing key pair. The keys are served on the OIDC provider managed by Amazon EKS and the private key rotates every 7 days. Amazon EKS keeps the public keys until they expire. If you connect external OIDC clients, be aware that you need to refresh the signing keys before the public key expires. Learn how to <<irsa-fetch-keys,Fetch signing keys to validate OIDC tokens>>.

Kubernetes has long used service accounts as its own internal identity system. Pods can authenticate with the Kubernetes API server using an auto-mounted token (which was a non-OIDC JWT) that only the Kubernetes API server could validate. These legacy service account tokens don't expire, and rotating the signing key is a difficult process. In Kubernetes version `1.12`, support was added for a new `ProjectedServiceAccountToken` feature. This feature is an OIDC JSON web token that also contains the service account identity and supports a configurable audience.

Amazon EKS hosts a public OIDC discovery endpoint for each cluster that contains the signing keys for the `ProjectedServiceAccountToken` JSON web tokens so external systems, such as IAM, can validate and accept the OIDC tokens that are issued by Kubernetes.

include::enable-iam-roles-for-service-accounts.adoc[leveloffset=+1]

include::associate-service-account-role.adoc[leveloffset=+1]

include::pod-configuration.adoc[leveloffset=+1]

include::configure-sts-endpoint.adoc[leveloffset=+1]

include::cross-account-access.adoc[leveloffset=+1]

include::iam-roles-for-service-accounts-minimum-sdk.adoc[leveloffset=+1]

include::irsa-fetch-keys.adoc[leveloffset=+1]
