[.topic]
[#iam-roles-for-service-accounts]
= IAM roles for service accounts
:info_titleabbrev: Credentials with IRSA

include::../../attributes.txt[]

[abstract]
--
Learn how applications in your [.noloc]`Pods` can access {aws} services.
--

Applications in a [.noloc]`Pod's` containers can use an {aws} SDK or the {aws} CLI to make API requests to {aws} services using {aws} Identity and Access Management (IAM) permissions. Applications must sign their {aws} API requests with {aws} credentials. IAM roles for service accounts (IRSA) provide the ability to manage credentials for your applications, similar to the way that Amazon EC2 instance profiles provide credentials to Amazon EC2 instances. Instead of creating and distributing your {aws} credentials to the containers or using the Amazon EC2 instance's role, you associate an IAM role with a [.noloc]`Kubernetes` service account and configure your [.noloc]`Pods` to use the service account. You can't use IAM roles for service accounts with <<eks-outposts-local-cluster-overview,local clusters for Amazon EKS on {aws} Outposts>>.

IAM roles for service accounts provide the following benefits:

* *Least privilege*
 – You can scope IAM permissions to a service account, and only [.noloc]`Pods` that use that service account have access to those permissions. This feature also eliminates the need for third-party solutions such as `kiam` or `kube2iam`.
* *Credential isolation*
 – A [.noloc]`Pod's` containers can only retrieve credentials for the IAM role that's associated with the service account that the container uses. A container never has access to credentials that are used by other containers in other [.noloc]`Pods`. When using IAM roles for service accounts, the [.noloc]`Pod's` containers also have the permissions assigned to the  <<create-node-role,Amazon EKS node IAM role>>, unless you block [.noloc]`Pod` access to the link:AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html[Amazon EC2 Instance Metadata Service (IMDS),type="documentation"]. For more information, see https://aws.github.io/aws-eks-best-practices/security/docs/iam/#restrict-access-to-the-instance-profile-assigned-to-the-worker-node[Restrict access to the instance profile assigned to the worker node].
* *Auditability*
  – Access and event logging is available through {aws} CloudTrail to help ensure retrospective auditing.

Enable IAM roles for service accounts by completing the following procedures:

. <<enable-iam-roles-for-service-accounts,Create an IAM OIDC provider for your cluster>> – You only complete this procedure once for each cluster.
+
[NOTE]
====
If you enabled the EKS VPC endpoint, the EKS OIDC service endpoint couldn't be accessed from inside that VPC. Consequently, your operations such as creating an OIDC provider with `eksctl` in the VPC will not work and will result in a timeout when attempting to request `https://oidc.eks.[.replaceable]``region``.amazonaws.com`. An example error message follows:

[source,bash,subs="verbatim,attributes"]
----
server cant find oidc.eks.region.amazonaws.com: NXDOMAIN
----

To complete this step, you can run the command outside the VPC, for example in {aws} CloudShell or on a computer connected to the internet. Alternatively, you can create a split-horizon conditional resolver in the VPC, such as Route 53 Resolver to use a different resolver for the OIDC Issuer URL and not use the VPC DNS for it. For an example of conditional forwarding in [.noloc]`CoreDNS`, see the https://github.com/aws/containers-roadmap/issues/2038[Amazon EKS feature request] on [.noloc]`GitHub`.
====

. <<associate-service-account-role,Assign IAM roles to Kubernetes service accounts>> – Complete this procedure for each unique set of permissions that you want an application to have.

. <<pod-configuration,Configure Pods to use a Kubernetes service account>> – Complete this procedure for each [.noloc]`Pod` that needs access to {aws} services.

. <<iam-roles-for-service-accounts-minimum-sdk,Use IRSA with the {aws} SDK>> – Confirm that the workload uses an {aws} SDK of a supported version and that the workload uses the default credential chain.


[#irsa-oidc-background]
== IAM, [.noloc]`Kubernetes`, and [.noloc]`OpenID Connect` ([.noloc]`OIDC`) background information

In 2014, {aws} Identity and Access Management added support for federated identities using [.noloc]`OpenID Connect` ([.noloc]`OIDC`). This feature allows you to authenticate {aws} API calls with supported identity providers and receive a valid [.noloc]`OIDC` [.noloc]`JSON` web token ([.noloc]`JWT`). You can pass this token to the {aws} STS `AssumeRoleWithWebIdentity` API operation and receive IAM temporary role credentials. You can use these credentials to interact with any {aws} service, including Amazon S3 and DynamoDB. 

Each JWT token is signed by a signing key pair. The keys are served on the OIDC provider managed by Amazon EKS and the private key rotates every 7 days. Amazon EKS keeps the public keys until they expire. If you connect external OIDC clients, be aware that you need to refresh the signing keys before the public key expires. Learn how to <<irsa-fetch-keys,Fetch signing keys to validate OIDC tokens>>.

[.noloc]`Kubernetes` has long used service accounts as its own internal identity system. [.noloc]`Pods` can authenticate with the [.noloc]`Kubernetes` API server using an auto-mounted token (which was a non-[.noloc]`OIDC` [.noloc]`JWT`) that only the [.noloc]`Kubernetes` API server could validate. These legacy service account tokens don't expire, and rotating the signing key is a difficult process. In [.noloc]`Kubernetes` version `1.12`, support was added for a new `ProjectedServiceAccountToken` feature. This feature is an [.noloc]`OIDC` [.noloc]`JSON` web token that also contains the service account identity and supports a configurable audience.

Amazon EKS hosts a public [.noloc]`OIDC` discovery endpoint for each cluster that contains the signing keys for the `ProjectedServiceAccountToken` [.noloc]`JSON` web tokens so external systems, such as IAM, can validate and accept the [.noloc]`OIDC` tokens that are issued by [.noloc]`Kubernetes`.

include::enable-iam-roles-for-service-accounts.adoc[leveloffset=+1]

include::associate-service-account-role.adoc[leveloffset=+1]

include::pod-configuration.adoc[leveloffset=+1]

include::configure-sts-endpoint.adoc[leveloffset=+1]

include::cross-account-access.adoc[leveloffset=+1]

include::iam-roles-for-service-accounts-minimum-sdk.adoc[leveloffset=+1]

include::irsa-fetch-keys.adoc[leveloffset=+1]


📝 https://github.com/search?q=repo%3Aawsdocs%2Famazon-eks-user-guide+%5B%23iam-roles-for-service-accounts%5D&type=code[Edit this page on GitHub]