include::../../attributes.txt[]

[.topic]
[#pod-identities]
= Learn how EKS Pod Identity grants pods access to {aws} services
:info_titleabbrev: Pod Identity

include::pod-id-how-it-works.adoc[leveloffset=+1]

include::pod-id-agent-setup.adoc[leveloffset=+1]

include::pod-id-association.adoc[leveloffset=+1]

include::pod-id-assign-target-role.adoc[leveloffset=+1]

include::pod-id-configure-pods.adoc[leveloffset=+1]

include::pod-id-abac.adoc[leveloffset=+1]

include::pod-id-minimum-sdk.adoc[leveloffset=+1]

include::pod-id-agent-config-ipv6.adoc[leveloffset=+1]

include::pod-id-role.adoc[leveloffset=+1]

[abstract]
--
Learn how to provide {aws} service access to your Kubernetes workloads with Amazon EKS Pod Identities, offering least privilege access, credential isolation, and auditability for enhanced security. Discover the benefits and considerations of this identity management solution for your Amazon EKS clusters.
--

Applications in a Pod's containers can use an {aws} SDK or the {aws} CLI to make API requests to {aws} services using {aws} Identity and Access Management (IAM) permissions. Applications must sign their {aws} API requests with {aws} credentials.

_EKS Pod Identities_ provide the ability to manage credentials for your applications, similar to the way that Amazon EC2 instance profiles provide credentials to Amazon EC2 instances. Instead of creating and distributing your {aws} credentials to the containers or using the Amazon EC2 instance's role, you associate an IAM role with a Kubernetes service account and configure your Pods to use the service account.

video::aUjJSorBE70[youtube,align = center,height = 405,fileref = https://www.youtube.com/embed/aUjJSorBE70,width = 720]

Each EKS Pod Identity association maps a role to a service account in a namespace in the specified cluster. If you have the same application in multiple clusters, you can make identical associations in each cluster without modifying the trust policy of the role.

If a pod uses a service account that has an association, Amazon EKS sets environment variables in the containers of the pod. The environment variables configure the {aws} SDKs, including the {aws} CLI, to use the EKS Pod Identity credentials.

[#pod-id-benefits]
== Benefits of EKS Pod Identities

EKS Pod Identities provide the following benefits:



* *Least privilege*
 – You can scope IAM permissions to a service account, and only Pods that use that service account have access to those permissions. This feature also eliminates the need for third-party solutions such as `kiam` or `kube2iam`.
* *Credential isolation*
 – A Pod's containers can only retrieve credentials for the IAM role that's associated with the service account that the container uses. A container never has access to credentials that are used by other containers in other Pods. When using Pod Identities, the Pod's containers also have the permissions assigned to the <<create-node-role>>, unless you block Pod access to the link:AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html["Amazon EC2 Instance Metadata Service (IMDS)", type="documentation"]. For more information, see https://aws.github.io/aws-eks-best-practices/security/docs/iam/#restrict-access-to-the-instance-profile-assigned-to-the-worker-node[Restrict access to the instance profile assigned to the worker node].
* *Auditability*
 – Access and event logging is available through {aws} CloudTrail to help facilitate retrospective auditing.

EKS Pod Identity is a simpler method than <<iam-roles-for-service-accounts>>, as this method doesn't use OIDC identity providers. EKS Pod Identity has the following enhancements:



* *Independent operations*
 – In many organizations, creating OIDC identity providers is a responsibility of different teams than administering the Kubernetes clusters. EKS Pod Identity has clean separation of duties, where all configuration of EKS Pod Identity associations is done in Amazon EKS and all configuration of the IAM permissions is done in IAM.
* *Reusability*
 – EKS Pod Identity uses a single IAM principal instead of the separate principals for each cluster that IAM roles for service accounts use. Your IAM administrator adds the following principal to the trust policy of any role to make it usable by EKS Pod Identities.
+
[source,json,subs="verbatim,attributes"]
----
            "Principal": {
                "Service": "pods.eks.amazonaws.com"
            }
----
* *Scalability*
 -- Each set of temporary credentials are assumed by the EKS Auth service in EKS Pod Identity, instead of each {aws} SDK that you run in each pod. Then, the Amazon EKS Pod Identity Agent that runs on each node issues the credentials to the SDKs. Thus the load is reduced to once for each node and isn't duplicated in each pod. For more details of the process, see <<pod-id-how-it-works>>.

For more information to compare the two alternatives, see <<service-accounts>>.

[#pod-id-setup-overview]
== Overview of setting up EKS Pod Identities

Turn on EKS Pod Identities by completing the following procedures:

. <<pod-id-agent-setup>> -- You only complete this procedure once for each cluster. You do not need to complete this step if EKS Auto Mode is enabled on your cluster. 
. <<pod-id-association>> -- Complete this procedure for each unique set of permissions that you want an application to have.
+
. <<pod-id-configure-pods>> -- Complete this procedure for each Pod that needs access to {aws} services.
. <<pod-id-minimum-sdk>> -- Confirm that the workload uses an {aws} SDK of a supported version and that the workload uses the default credential chain.


[#pod-id-considerations]
== EKS Pod Identity considerations

* *IAM Role Association*: Each Kubernetes service account in a cluster can be associated with one IAM role from the same {aws} account as the cluster. To change the role, edit the EKS Pod Identity association. For cross-account access, delegate access to the role using IAM roles. To learn more, see link:https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html[Delegate access across {aws} accounts using IAM roles] in the _IAM User Guide_.
* *EKS Pod Identity Agent*: The Pod Identity Agent is required to use EKS Pod Identity. The agent runs as a Kubernetes `DaemonSet` on cluster nodes, providing credentials only to pods on the same node. It uses the node’s `hostNetwork`, occupying port `80` and `2703` on the link-local address (`169.254.170.23` for IPv4, `[fd00:ec2::23]` for IPv6). If IPv6 is disabled in your cluster, disable IPv6 for the Pod Identity Agent. To learn more, see link:https://docs.aws.amazon.com/eks/latest/userguide/pod-id-agent-config-ipv6.html[Disable IPv6 in the EKS Pod Identity Agent].
* *Eventual Consistency*: EKS Pod Identity associations are eventually consistent, with potential delays of several seconds after API calls. Avoid creating or updating associations in critical, high-availability code paths. Instead, perform these actions in separate, less frequent initialization or setup routines. To learn more, see link:https://docs.aws.amazon.com/eks/latest/best-practices/sgpp.html[Security Groups Per Pod] in the _EKS Best Practices Guide_.
* *Proxy and Security Group Considerations*: For pods using a proxy, add `169.254.170.23` (IPv4) and `[fd00:ec2::23]` (IPv6) to the `no_proxy/NO_PROXY` environment variables to prevent failed requests to the EKS Pod Identity Agent. If using Security Groups for Pods with the {aws} VPC CNI, set the `ENABLE_POD_ENI` flag to ‘true’ and the `POD_SECURITY_GROUP_ENFORCING_MODE` flag to ‘standard’. To learn more, see link:https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html[Assign security groups to individual Pods].

[#pod-id-cluster-versions]
=== EKS Pod Identity cluster versions

To use EKS Pod Identity, the cluster must have a platform version that is the same or later than the version listed in the following table, or a Kubernetes version that is later than the versions listed in the table. To find the suggested version of the Amazon EKS Pod Identity Agent for a Kubernetes version, see <<addon-compat>>. 

[%header,cols="2"]
|===
|Kubernetes version
|Platform version

|Kubernetes versions not listed
|All platform versions support

|`1.28`
|`eks.4`

|`1.27`
|`eks.8`

|`1.26`
|`eks.9`

|===

[#pod-id-restrictions]
=== EKS Pod Identity restrictions

EKS Pod Identities are available on the following:



* Amazon EKS cluster versions listed in the previous topic <<pod-id-cluster-versions>>.
* Worker nodes in the cluster that are Linux Amazon EC2 instances.

EKS Pod Identities aren't available on the following:



* {aws} Outposts.
* Amazon EKS Anywhere.
* Kubernetes clusters that you create and run on Amazon EC2. The EKS Pod Identity components are only available on Amazon EKS.

You can't use EKS Pod Identities with:


* Pods that run anywhere except Linux Amazon EC2 instances. Linux and Windows pods that run on {aws} Fargate (Fargate) aren't supported. Pods that run on Windows Amazon EC2 instances aren't supported.

