include::../../attributes.txt[]
[.topic]
[#pod-id-minimum-sdk]
= Use pod identity with the {aws} SDK
:info_titleabbrev: Supported SDKs

[#pod-id-using-creds]
== Using EKS Pod Identity credentials

To use the credentials from a EKS Pod Identity association, your code can use any {aws} SDK to create a client for an {aws} service with an SDK, and by default the SDK searches in a chain of locations for {aws} Identity and Access Management credentials to use. The EKS Pod Identity credentials will be used if you don't specify a credential provider when you create the client or otherwise initialized the SDK.

This works because EKS Pod Identities have been added to the _Container credential provider_ which is searched in a step in the default credential chain. If your workloads currently use credentials that are earlier in the chain of credentials, those credentials will continue to be used even if you configure an EKS Pod Identity association for the same workload.

For more information about how EKS Pod Identities work, see <<pod-id-how-it-works>>.

When using <<pod-identities,Learn how EKS Pod Identity grants pods access to {aws} services>>, the containers in your [.noloc]`Pods` must use an {aws} SDK version that supports assuming an IAM role from the EKS Pod Identity Agent. Make sure that you're using the following versions, or later, for your {aws} SDK:



* Java (Version 2) – https://github.com/aws/aws-sdk-java-v2/releases/tag/2.21.30[2.21.30]
* Java – https://github.com/aws/aws-sdk-java/releases/tag/1.12.746[1.12.746]
* Go v1 – https://github.com/aws/aws-sdk-go/releases/tag/v1.47.11[v1.47.11]
* Go v2 – https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2023-11-14[release-2023-11-14]
* Python (Boto3) – https://github.com/boto/boto3/releases/tag/1.34.41[1.34.41]
* Python (botocore) – https://github.com/boto/botocore/releases/tag/1.34.41[1.34.41]
* {aws} CLI – https://github.com/aws/aws-cli/releases/tag/1.30.0[1.30.0]
+
{aws} CLI – https://github.com/aws/aws-cli/releases/tag/2.15.0[2.15.0]
* JavaScript v2 – https://github.com/aws/aws-sdk-js/releases/tag/v2.1550.0[2.1550.0]
* JavaScript v3 – https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.458.0[v3.458.0]
* Kotlin – https://github.com/awslabs/aws-sdk-kotlin/releases/tag/v1.0.1[v1.0.1]
* Ruby – https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-core/CHANGELOG.md#31880-2023-11-22[3.188.0]
* Rust – https://github.com/awslabs/aws-sdk-rust/releases/tag/release-2024-03-13[release-2024-03-13]
* {cpp} – https://github.com/aws/aws-sdk-cpp/releases/tag/1.11.263[1.11.263]
* .NET – https://github.com/aws/aws-sdk-net/releases/tag/3.7.734.0[3.7.734.0]
* PowerShell – https://www.powershellgallery.com/packages/AWS.Tools.Common/4.1.502[4.1.502]
* PHP – https://github.com/aws/aws-sdk-php/releases/tag/3.287.1[3.287.1]

To ensure that you're using a supported SDK, follow the installation instructions for your preferred SDK at link:tools/[Tools to Build on {aws},type="marketing"] when you build your containers.

For a list of add-ons that support EKS Pod Identity, see <<pod-id-add-on-versions>>.


📝 https://github.com/search?q=repo%3Aawsdocs%2Famazon-eks-user-guide+%5B%23pod-id-minimum-sdk%5D&type=code[Edit this page on GitHub]