include::../../attributes.txt[]
[.topic]
[#pod-id-configure-pods]
= Configure [.noloc]`Pods` to access {aws} services with service accounts
:info_titleabbrev: Pod service account

[abstract]
--
Learn how to configure Pods to use a Kubernetes service account with an associated IAM role for accessing {aws} services on Amazon EKS.
--

If a [.noloc]`Pod` needs to access {aws} services, then you must configure it to use a [.noloc]`Kubernetes` service account. The service account must be associated to an {aws} Identity and Access Management (IAM) role that has permissions to access the {aws} services.

* An existing cluster. If you don't have one, you can create one using one of the guides in <<getting-started>>.
* An existing [.noloc]`Kubernetes` service account and an EKS Pod Identity association that associates the service account with an IAM role. The role must have an associated IAM policy that contains the permissions that you want your [.noloc]`Pods` to have to use {aws} services. For more information about how to create the service account and role, and configure them, see <<pod-id-association>>.
* The latest version of the {aws} CLI installed and configured on your device or {aws} CloudShell. You can check your current version with `aws --version | cut -d / -f2 | cut -d ' ' -f1`. Package managers such `yum`, `apt-get`, or [.noloc]`Homebrew` for [.noloc]`macOS` are often several versions behind the latest version of the {aws} CLI. To install the latest version, see link:cli/latest/userguide/cli-chap-install.html[Installing, updating, and uninstalling the {aws} CLI,type="documentation"] and  link:cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-config[Quick configuration with aws configure,type="documentation"] in the {aws} Command Line Interface User Guide. The {aws} CLI version installed in the {aws} CloudShell may also be several versions behind the latest version. To update it, see  link:cloudshell/latest/userguide/vm-specs.html#install-cli-software[Installing {aws} CLI to your home directory,type="documentation"] in the {aws} CloudShell User Guide.
* The `kubectl` command line tool is installed on your device or {aws} CloudShell. The version can be the same as or up to one minor version earlier or later than the [.noloc]`Kubernetes` version of your cluster. For example, if your cluster version is `1.29`, you can use `kubectl` version `1.28`, `1.29`, or `1.30` with it. To install or upgrade `kubectl`, see <<install-kubectl>>.
* An existing `kubectl` `config` file that contains your cluster configuration. To create a `kubectl` `config` file, see <<create-kubeconfig>>.
. Use the following command to create a deployment manifest that you can deploy a [.noloc]`Pod` to confirm configuration with. Replace the [.replaceable]`example values` with your own values.
+
[source,yaml,subs="verbatim,attributes"]
----
cat >my-deployment.yaml <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: my-service-account
      containers:
      - name: my-app
        image: public.ecr.aws/nginx/nginx:X.XX
EOF
----
. Deploy the manifest to your cluster.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl apply -f my-deployment.yaml
----
. Confirm that the required environment variables exist for your [.noloc]`Pod`.
+
.. View the [.noloc]`Pods` that were deployed with the deployment in the previous step.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl get pods | grep my-app
----
+
An example output is as follows.
+
[source,bash,subs="verbatim,attributes"]
----
my-app-6f4dfff6cb-76cv9   1/1     Running   0          3m28s
----
.. Confirm that the [.noloc]`Pod` has a service account token file mount.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl describe pod my-app-6f4dfff6cb-76cv9 | grep AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE:
----
+
An example output is as follows.
+
[source,bash,subs="verbatim,attributes"]
----
AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE:  /var/run/secrets/pods.eks.amazonaws.com/serviceaccount/eks-pod-identity-token
----
. Confirm that your [.noloc]`Pods` can interact with the {aws} services using the permissions that you assigned in the IAM policy attached to your role.
+
NOTE: When a [.noloc]`Pod` uses {aws} credentials from an IAM role that's associated with a service account, the {aws} CLI or other SDKs in the containers for that [.noloc]`Pod` use the credentials that are provided by that role. If you don't restrict access to the credentials that are provided to the  <<create-node-role,Amazon EKS node IAM role>>, the [.noloc]`Pod` still has access to these credentials. For more information, see https://aws.github.io/aws-eks-best-practices/security/docs/iam/#restrict-access-to-the-instance-profile-assigned-to-the-worker-node[Restrict access to the instance profile assigned to the worker node].
+
If your [.noloc]`Pods` can't interact with the services as you expected, complete the following steps to confirm that everything is properly configured.
+
.. Confirm that your [.noloc]`Pods` use an {aws} SDK version that supports assuming an IAM role through an EKS Pod Identity association. For more information, see <<pod-id-minimum-sdk>>.
.. Confirm that the deployment is using the service account.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl describe deployment my-app | grep "Service Account"
----
+
An example output is as follows.
+
[source,bash,subs="verbatim,attributes"]
----
Service Account:  my-service-account
----


📝 https://github.com/search?q=repo%3Aawsdocs%2Famazon-eks-user-guide+%5B%23pod-id-configure-pods%5D&type=code[Edit this page on GitHub]