include::../attributes.txt[]

[.topic]
[#community-addons]
= Community add-ons 

You can use {aws} APIs to install community add-ons, such as the Kubernetes Metrics Server. You may choose to install community add-ons as Amazon EKS Add-ons to reduce the complexity of maintaining the software on multiple clusters. 

For example, you can use the {aws} API, CLI, or Management Console to install community add-ons. You can install a community add-on during cluster creation. 

You manage community add-ons just like existing Amazon EKS Add-ons. Community add-ons are different from existing add-ons in that they have a unique scope of support. 

NOTE: Using community add-ons is at your discretion. As part of the xref:security[shared responsibility model] between you and {aws}, you are expected to understand what you are installing into your workspace for these third party plugins. You are also responsible for the community add-ons meeting your security needs.

Community add-ons are built by {aws}. {aws} only validates community add-ons for version compatibility. For example, if you install a community add-on on a cluster, {aws} checks if it is compatible with the Kubernetes version of your cluster. 

Importantly, {aws} does not provide full support for community add-ons. {aws} supports only lifecycle operations done using {aws} APIs, such as installing add-ons or deleting add-ons. 

If you require support for a community add-on, utilize the existing project resources. For example, you may create a GitHub issue on the repo for the project.

== Determine add-on type

You can use the {aws} CLI to determine the type of an Amazon EKS Add-on. 

Use the following CLI command to retrieve information about an add-on. You can replace `metrics-server` with the name of any add-on. 

```bash
aws eks describe-addon-versions --addon-name metrics-server
```

Review the CLI output for the `owner` field.

```
{
    "addons": [
        {
            "addonName": "metrics-server",
            "type": "observability",
            "owner": "community", 
            "addonVersions": [
```

If the value of `owner` is `community`, then the add-on is a community add-on. {aws} only provides support for installing, updating, and removing the add-on. If you have questions about the functionality and operation of the add-on itself, use community resources like GitHub issues. 


== Install or update community add-on

You install or update community add-ons in the same way as other Amazon EKS Add-ons. 

* <<creating-an-add-on>>
* <<updating-an-add-on>>
* <<removing-an-add-on>>

== Available community add-ons

The following community add-ons are availalbe from Amazon EKS. 

=== Kubernetes Metrics Server

The Kubernetes Metrics Server is a scalable and efficient source of container resource metrics for Kubernetes built-in autoscaling pipelines. It collects resource metrics from Kubelets and exposes them in Kubernetes apiserver through Metrics API for use by Horizontal Pod Autoscaler and Vertical Pod Autoscaler.

|===
|Property | Value

|Add-on name | `metrics-server`

|Namespace | `kube-system`

|Documentation | https://github.com/kubernetes-sigs/metrics-server[GitHub Readme]

|Service account name | None

|Managed IAM policy | None

|Custom IAM permissions | None
|===


=== `kube-state-metrics`

Add-on agent to generate and expose cluster-level metrics.

The state of Kubernetes objects in the Kubernetes API can be exposed as metrics. An add-on agent called kube-state-metrics can connect to the Kubernetes API server and expose a HTTP endpoint with metrics generated from the state of individual objects in the cluster. It exposes various information about the state of objects like labels and annotations, startup and termination times, status or the phase the object currently is in. 

|===
|Property | Value

|Add-on name | `kube-state-metrics`

|Namespace | `kube-state-metrics`

|Documentation | https://kubernetes.io/docs/concepts/cluster-administration/kube-state-metrics/[Metrics for Kubernetes Object States] in Kubernetes Docs

|Service account name | None

|Managed IAM policy | None

|Custom IAM permissions | None
|===


=== Prometheus Node Exporter

Prometheus exporter for hardware and OS metrics exposed by *NIX kernels, written in Go with pluggable metric collectors. The Prometheus Node Exporter exposes a wide variety of hardware- and kernel-related metrics.

|===
|Property | Value

|Add-on name | `prometheus-node-exporter`

|Namespace | `prometheus-node-exporter`

|Documentation | https://prometheus.io/docs/guides/node-exporter/#monitoring-linux-host-metrics-with-the-node-exporter[Monitoring Linux host metrics with the Node Exporter] in Prometheus Docs

|Service account name | None

|Managed IAM policy | None

|Custom IAM permissions | None
|===

== View Attributions

You can download the open source attribtions and license information for community add-ons.

. Determine the name and version of the add-on you want to download attributions for. 
. Update the following command with the name and version:
+
[source,cli]
----
curl -O https://amazon-eks-docs.s3.amazonaws.com/attributions/<add-on-name>/<add-on-version>/attributions.zip
----
+
For example:
+
[source,cli]
----
curl -O https://amazon-eks-docs.s3.amazonaws.com/attributions/kube-state-metrics/v2.14.0-eksbuild.1/attributions.zip
----
. Use the command to download the file. 

Use this zip file to view information about the license attributions. 
