[.topic]
[#removing-an-add-on]
= Remove an Amazon EKS add-on from a cluster
:info_titleabbrev: Remove an add-on

include::../attributes.txt[]


[abstract]
--
Learn how to remove an Amazon EKS add-on.
--

You can remove an Amazon EKS add-on from your cluster using `eksctl`, the {aws-management-console}, or the {aws} CLI.

When you remove an Amazon EKS add-on from a cluster:



* There is no downtime for the functionality that the add-on provides.
* If you are using IAM Roles for Service Accounts (IRSA) and the add-on has an IAM role associated with it, the IAM role isn't removed.
* If you are using Pod Identities, any Pod Identity Associations owned by the add-on are removed. If you specify the `--preserve` option to the {aws} CLI, the associations are preserved.
* Amazon EKS stops managing settings for the add-on.
* The console stops notifying you when new versions are available.
* You can't update the add-on using any {aws} tools or APIs.
* You can choose to leave the add-on software on your cluster so that you can self-manage it, or you can remove the add-on software from your cluster. You should only remove the add-on software from your cluster if there are no resources on your cluster are dependent on the functionality that the add-on provides.


[#removing-an-add-on-prereq]
== Prerequisites

Complete the following before you create an add-on:



* An existing Amazon EKS cluster. To deploy one, see <<getting-started>>.
* Check if your add-on requires an IAM role. For more information, see 
* Version `{eksctl-min-version}` or later of the `eksctl` command line tool installed on your device or {aws} CloudShell. To install or update `eksctl`, see https://eksctl.io/installation[Installation] in the `eksctl` documentation..


[#removing-an-add-on-procedure]
== Procedure

You have two options when removing an Amazon EKS add-on.

* *Preserve add-on software on your cluster* – This option removes Amazon EKS management of any settings. It also removes the ability for Amazon EKS to notify you of updates and automatically update the Amazon EKS add-on after you initiate an update. However, it preserves the add-on software on your cluster. This option makes the add-on a self-managed installation, rather than an Amazon EKS add-on. With this option, there's no downtime for the add-on.
* *Remove add-on software entirely from your cluster* – We recommend that you remove the Amazon EKS add-on from your cluster only if there are no resources on your cluster that are dependent on it.

You can remove an Amazon EKS add-on using `eksctl`, the {aws-management-console}, or the {aws} CLI. 

=== Remove add-on (eksctl)

. Determine the current add-ons installed on your cluster. Replace [.replaceable]`my-cluster` with the name of your cluster.
+
[source,bash,subs="verbatim,attributes"]
----
eksctl get addon --cluster my-cluster
----
+
An example output is as follows.
+
[source,bash,subs="verbatim,attributes"]
----
NAME        VERSION              STATUS  ISSUES  IAMROLE  UPDATE AVAILABLE
coredns     v1.8.7-eksbuild.2    ACTIVE  0
kube-proxy  v1.23.7-eksbuild.1   ACTIVE  0                
vpc-cni     v1.10.4-eksbuild.1   ACTIVE  0
[...]
----
+
Your output might look different, depending on which add-ons and versions that you have on your cluster.
. Remove the add-on. Replace [.replaceable]`my-cluster` with the name of your cluster and [.replaceable]`name-of-add-on` with the name of the add-on returned in the output of the previous step that you want to remove. If you remove the [.replaceable]`--preserve` option, in addition to Amazon EKS no longer managing the add-on, the add-on software is deleted from your cluster.
+
[source,bash,subs="verbatim,attributes"]
----
eksctl delete addon --cluster my-cluster --name name-of-addon --preserve
----

+
For more information about removing add-ons, see https://eksctl.io/usage/addons/#deleting-addons[Deleting addons] in the `eksctl` documentation.


=== Remove add-on ({aws} Console)

. Open the link:eks/home#/clusters[Amazon EKS console,type="console"].
. In the left navigation pane, choose *Clusters*.
. Choose the name of the cluster that you want to remove the Amazon EKS add-on for.
. Choose the *Add-ons* tab.
. Choose the add-on that you want to remove.
. Choose *Remove*.
. In the *Remove: [.replaceable]`name of addon`* confirmation dialog box, do the following:
+
.. If you want Amazon EKS to stop managing settings for the add-on, select *Preserve on cluster*. Do this if you want to retain the add-on software on your cluster. This is so that you can manage all of the settings of the add-on on your own.
.. Enter the add-on name.
.. Choose *Remove*.


=== Remove add-on ({aws} CLI)

. You need version `{eksctl-min-version}` or later of the `eksctl` command line tool installed on your device or {aws} CloudShell. To install or update `eksctl`, see https://eksctl.io/installation[Installation] in the `eksctl` documentation.
+
. See a list of installed add-ons. Replace [.replaceable]`my-cluster` with the name of your cluster.
+
[source,bash,subs="verbatim,attributes"]
----
aws eks list-addons --cluster-name my-cluster
----
+
An example output is as follows.
+
[source,json,subs="verbatim,attributes"]
----
{
    "addons": [
        "coredns",
        "kube-proxy",
        "vpc-cni",
        "name-of-addon"
    ]
}
----
. Remove the installed add-on. Replace [.replaceable]`my-cluster` with the name of your cluster and [.replaceable]`name-of-add-on` with the name of the add-on that you want to remove. Removing [.replaceable]`--preserve` deletes the add-on software from your cluster.
+
[source,bash,subs="verbatim,attributes"]
----
aws eks delete-addon --cluster-name my-cluster --addon-name name-of-addon --preserve
----
+
The abbreviated example output is as follows.
+
[source,json,subs="verbatim,attributes"]
----
{
    "addon": {
        "addonName": "name-of-add-on",
        "clusterName": "my-cluster",
        "status": "DELETING",
    }
}
----
. Check the status of the removal. Replace [.replaceable]`my-cluster` with the name of your cluster and [.replaceable]`name-of-addon` with the name of the add-on that you're removing.
+
[source,bash,subs="verbatim,attributes"]
----
aws eks describe-addon --cluster-name my-cluster --addon-name name-of-addon
----
+
After the add-on is removed, the example output is as follows.
+
[source,bash,subs="verbatim,attributes"]
----
An error occurred (ResourceNotFoundException) when calling the DescribeAddon operation: No addon: name-of-addon found in cluster: my-cluster
----