[.topic]
[[retreive-iam-info,retreive-iam-info.title]]
= Retrieve IAM information about an Amazon EKS add-on
:info_titleabbrev: Retrieve IAM information

include::../attributes.txt[]

[abstract]
--
Learn how to determine the role and policy to use for an Amazon EKS add-on.
--

Before you create an add-on, use the {aws} CLI to determine:

* If the add-on requires IAM permissions 
* The suggested IAM policy to use

== Procedure

. Determine the name of the add-on you want to install, and the [.noloc]`Kubernetes` version of your cluster. For more information about add-ons, see <<eks-add-ons>>. 
. Use the {aws} CLI to determine if the add-on requires IAM permissions. 
+
[source,shell,subs="verbatim,attributes"]
----
aws eks describe-addon-versions \
--addon-name <addon-name> \
--kubernetes-version <kubernetes-version>
----
+
For example:
+
[source,shell,subs="verbatim,attributes"]
----
aws eks describe-addon-versions \
--addon-name aws-ebs-csi-driver \
--kubernetes-version 1.30
----
+
Review the following sample output. Note that `requiresIamPermissions` is `true`, and the default add-on version. You need to specify the add-on version when retrieving the recommended IAM policy.
+
[source,text,subs="verbatim,attributes"]
----
{
    "addons": [
        {
            "addonName": "aws-ebs-csi-driver",
            "type": "storage",
            "addonVersions": [
                {
                    "addonVersion": "v1.31.0-eksbuild.1",
                    "architecture": [
                        "amd64",
                        "arm64"
                    ],
                    "compatibilities": [
                        {
                            "clusterVersion": "1.30",
                            "platformVersions": [
                                "*"
                            ],
                            "defaultVersion": true
                        }
                    ],
                    "requiresConfiguration": false,
                    "requiresIamPermissions": true
                },
[...]
----
. If the add-on requires IAM permissions, use the {aws} CLI to retrieve a recommended IAM policy. 
+
[source,shell,subs="verbatim,attributes"]
----
aws eks describe-addon-configuration \
--query podIdentityConfiguration \
--addon-name <addon-name> \
--addon-version <addon-version>
----
+
For example:
+
[source,shell,subs="verbatim,attributes"]
----
aws eks describe-addon-configuration \
--query podIdentityConfiguration \
--addon-name aws-ebs-csi-driver \
--addon-version v1.31.0-eksbuild.1
----
+
Review the following output. Note the `recommendedManagedPolicies`.
+
[source,json,subs="verbatim,attributes"]
----
[
    {
        "serviceAccount": "ebs-csi-controller-sa",
        "recommendedManagedPolicies": [
            "{arn-aws}iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"
        ]
    }
]
----
. Create an IAM role and attach the recommended Managed Policy. Alternatively, review the managed policy and scope down the permissions as appropriate. For more information see <<pod-id-association-create>>. 

[[pod-id-add-on-versions,pod-id-add-on-versions.title]]
== Pod Identity Support Reference

The following table indicates if certain Amazon EKS add-ons support EKS Pod Identity.

[cols="2,1,2"]
|=== 
| Add-on Name | Pod Identity Support | Minimum Version Required

| xref:add-ons-aws-ebs-csi-driver[Amazon EBS CSI Driver] 
| Yes 
| v1.26.0-eksbuild.1

| xref:add-ons-vpc-cni[Amazon VPC CNI] 
| Yes 
| v1.15.5-eksbuild.1

| xref:add-ons-aws-efs-csi-driver[Amazon EFS CSI Driver] 
| Yes 
| v2.0.5-eksbuild.1

| xref:add-ons-adot[{aws} Distro for OpenTelemetry] 
| Yes 
| v0.94.1-eksbuild.1

| xref:mountpoint-for-s3-add-on[Mountpoint for Amazon S3 CSI Driver] 
| No 
| N/A

| xref:amazon-cloudwatch-observability[Amazon CloudWatch Observability agent] 
| Yes 
| v3.1.0-eksbuild.1

|===

This table was last updated on October 28, 2024.
