include::../attributes.txt[]

[.topic]
[[workloads-add-ons-available-vendors,workloads-add-ons-available-vendors.title]]
= {aws} Marketplace add-ons
:info_titleabbrev: Marketplace add-ons

[abstract]
--
Learn about the Amazon EKS add-ons from independent software vendors.
--

In addition to the previous list of Amazon EKS add-ons, you can also add a wide selection of operational software Amazon EKS add-ons from independent software vendors. Choose an add-on to learn more about it and its installation requirements.



video::IIPj119mspc[youtube,align = center,height = 405,fileref = https://www.youtube.com/embed/IIPj119mspc,width = 720]


[[add-on-accuknox,add-on-accuknox.title]]
== [.noloc]`Accuknox`

[abstract]
--
Learn about the [.noloc]`Accuknox` Amazon EKS add-on.
--

The add-on name is `accuknox_kubearmor` and the namespace is `kubearmor`. [.noloc]`Accuknox` publishes the add-on.

For information about the add-on, see https://docs.kubearmor.io/kubearmor/quick-links/deployment_guide[Getting Started with KubeArmor] in the KubeArmor documentation.

[[add-on-accuknox-service-account-name,add-on-accuknox-service-account-name.title]]
=== Service account name

A service account isn't used with this add-on.

[[add-on-accuknox-managed-policy,add-on-accuknox-managed-policy.title]]
=== {aws} managed IAM policy

A managed policy isn't used with this add-on.

[[add-on-accuknox-custom-permissions,add-on-accuknox-custom-permissions.title]]
=== Custom IAM permissions

Custom permissions aren't used with this add-on.

[[add-on-akuity,add-on-akuity.title]]
== [.noloc]`Akuity`

[abstract]
--
Learn about the [.noloc]`Akuity` Amazon EKS add-on.
--

The add-on name is `akuity_agent` and the namespace is `akuity`. [.noloc]`Akuity` publishes the add-on.

For information about how the add-on, see https://docs.akuity.io/tutorials/eks-addon-agent-install/[Installing the Akuity Agent on Amazon EKS with the Akuity EKS add-on] in the Akuity Platform documentation.

[[add-on-akuity-service-account-name,add-on-akuity-service-account-name.title]]
=== Service account name

A service account isn't used with this add-on.

[[add-on-akuity-managed-policy,add-on-akuity-managed-policy.title]]
=== {aws} managed IAM policy

A managed policy isn't used with this add-on.

[[add-on-akuity-custom-permissions,add-on-akuity-custom-permissions.title]]
=== Custom IAM permissions

Custom permissions aren't used with this add-on.

[[add-on-calyptia,add-on-calyptia.title]]
== [.noloc]`Calyptia`

[abstract]
--
Learn about the [.noloc]`Calyptia` Amazon EKS add-on.
--

The add-on name is `calyptia_fluent-bit` and the namespace is `calytia-fluentbit`. [.noloc]`Calyptia` publishes the add-on.

For information about the add-on, see https://docs.akuity.io/tutorials/eks-addon-agent-install/[Getting Started with Calyptia Core Agent] on the Calyptia documentation website.

[[add-on-calyptia-service-account-name,add-on-calyptia-service-account-name.title]]
=== Service account name

The service account name is  `clyptia-fluentbit`.

[[add-on-calyptia-managed-policy,add-on-calyptia-managed-policy.title]]
=== {aws} managed IAM policy

This add-on uses the `AWSMarketplaceMeteringRegisterUsage` managed policy. For more information, see link:aws-managed-policy/latest/reference/AWSMarketplaceMeteringRegisterUsage.html[AWSMarketplaceMeteringRegisterUsage,type="documentation"] in the {aws} Managed Policy Reference Guide.

[[add-on-calyptia-custom-permissions,add-on-calyptia-custom-permissions.title]]
=== Command to create required IAM role

The following command requires that you have an IAM [.noloc]`OpenID Connect` ([.noloc]`OIDC`) provider for your cluster. To determine whether you have one, or to create one, see <<enable-iam-roles-for-service-accounts>>. Replace [.replaceable]`my-cluster` with the name of your cluster and [.replaceable]`my-calyptia-role` with the name for your role. This command requires that you have https://eksctl.io[eksctl] installed on your device. If you need to use a different tool to create the role and annotate the [.noloc]`Kubernetes` service account, see <<associate-service-account-role>>.

[source,bash,subs="verbatim,attributes"]
----
eksctl create iamserviceaccount --name service-account-name  --namespace calyptia-fluentbit --cluster my-cluster --role-name my-calyptia-role \
    --role-only --attach-policy-arn {arn-aws}iam::aws:policy/AWSMarketplaceMeteringRegisterUsage --approve
----


[[add-on-cisco-collector,add-on-cisco-collector.title]]
== [.noloc]`Cisco Observability Collector`

[abstract]
--
Learn about the [.noloc]`Cisco Observability Collector` Amazon EKS add-on.
--

The add-on name is `cisco_cisco-cloud-observability-collectors` and the namespace is `appdynamics`. [.noloc]`Cisco` pubishes the add-on.

For information about the add-on, see https://docs.appdynamics.com/observability/cisco-cloud-observability/en/kubernetes-and-app-service-monitoring/install-kubernetes-and-app-service-monitoring-with-amazon-elastic-kubernetes-service/use-the-cisco-cloud-observability-aws-marketplace-add-ons[Use the Cisco Cloud Observability {aws} Marketplace Add-Ons] in the Cisco AppDynamics documentation.

[[add-on-cisco-collector-service-account-name,add-on-cisco-collector-service-account-name.title]]
=== Service account name

A service account isn't used with this add-on.

[[add-on-cisco-collector-managed-policy,add-on-cisco-collector-managed-policy.title]]
=== {aws} managed IAM policy

A managed policy isn't used with this add-on.

[[add-on-cisco-collector-custom-permissions,add-on-cisco-collector-custom-permissions.title]]
=== Custom IAM permissions

Custom permissions aren't used with this add-on.

[[add-on-cisco-operator,add-on-cisco-operator.title]]
== [.noloc]`Cisco Observability Operator`

[abstract]
--
Learn about the [.noloc]`Cisco Observability Operator` Amazon EKS add-on.
--

The add-on name is `cisco_cisco-cloud-observability-operators` and the namespace is `appdynamics`. [.noloc]`Cisco` publishes the add-on.

For information about the add-on, see https://docs.appdynamics.com/observability/cisco-cloud-observability/en/kubernetes-and-app-service-monitoring/install-kubernetes-and-app-service-monitoring-with-amazon-elastic-kubernetes-service/use-the-cisco-cloud-observability-aws-marketplace-add-ons[Use the Cisco Cloud Observability {aws} Marketplace Add-Ons] in the Cisco AppDynamics documentation.

[[add-on-cisco-operator-service-account-name,add-on-cisco-operator-service-account-name.title]]
=== Service account name

A service account isn't used with this add-on.

[[add-on-cisco-operator-managed-policy,add-on-cisco-operator-managed-policy.title]]
=== {aws} managed IAM policy

A managed policy isn't used with this add-on.

[[add-on-cisco-operator-custom-permissions,add-on-cisco-operator-custom-permissions.title]]
=== Custom IAM permissions

Custom permissions aren't used with this add-on.

[[add-on-cloudsoft,add-on-cloudsoft.title]]
== [.noloc]`CLOUDSOFT`

[abstract]
--
Learn about the [.noloc]`CLOUDSOFT` Amazon EKS add-on.
--

The add-on name is `cloudsoft_cloudsoft-amp` and the namespace is `cloudsoft-amp`. [.noloc]`CLOUDSOFT` publishes the add-on.

For information about the add-on, see https://docs.cloudsoft.io/operations/configuration/aws-eks-addon.html[Amazon EKS ADDON] in the CLOUDSOFT documentation.

[[add-on-cloudsoft-service-account-name,add-on-cloudsoft-service-account-name.title]]
=== Service account name

A service account isn't used with this add-on.

[[add-on-cloudsoft-managed-policy,add-on-cloudsoft-managed-policy.title]]
=== {aws} managed IAM policy

A managed policy isn't used with this add-on.

[[add-on-cloudsoft-custom-permissions,add-on-cloudsoft-custom-permissions.title]]
=== Custom IAM permissions

Custom permissions aren't used with this add-on.

[[add-on-cribl,add-on-cribl.title]]
== [.noloc]`Cribl`

[abstract]
--
Learn about the [.noloc]`Cribl` Amazon EKS add-on.
--

The add-on name is `cribl_cribledge` and the namespace is `cribledge`. [.noloc]`Cribl` publishes the add-on.

For information about the add-on, see https://docs.cribl.io/edge/usecase-edge-aws-eks/[Installing the Cribl Amazon EKS Add-on for Edge] in the Cribl documentation

[[add-on-cribl-service-account-name,add-on-cribl-service-account-name.title]]
=== Service account name

A service account isn't used with this add-on.

[[add-on-cribl-managed-policy,add-on-cribl-managed-policy.title]]
=== {aws} managed IAM policy

A managed policy isn't used with this add-on.

[[add-on-cribl-custom-permissions,add-on-cribl-custom-permissions.title]]
=== Custom IAM permissions

Custom permissions aren't used with this add-on.

[[add-on-dynatrace,add-on-dynatrace.title]]
== [.noloc]`Dynatrace`

[abstract]
--
Learn about the [.noloc]`Dynatrace` Amazon EKS add-on.
--

The add-on name is `dynatrace_dynatrace-operator` and the namespace is `dynatrace`. [.noloc]`Dynatrace` publishes the add-on.

For information about the add-on, see https://www.dynatrace.com/technologies/kubernetes-monitoring/[Kubernetes monitoring] in the [.noloc]`dynatrace` documentation.

[[add-on-dynatrace-service-account-name,add-on-dynatrace-service-account-name.title]]
=== Service account name

A service account isn't used with this add-on.

[[add-on-dynatrace-managed-policy,add-on-dynatrace-managed-policy.title]]
=== {aws} managed IAM policy

A managed policy isn't used with this add-on.

[[add-on-dynatrace-custom-permissions,add-on-dynatrace-custom-permissions.title]]
=== Custom IAM permissions

Custom permissions aren't used with this add-on.

[[add-on-datree-pro,add-on-datree-pro.title]]
== [.noloc]`Datree`

[abstract]
--
Learn about the [.noloc]`Datree` Amazon EKS add-on.
--

The add-on name is `datree_engine-pro` and the namespace is `datree`. [.noloc]`Datree` publishes the add-on.

For information about the add-on, see https://hub.datree.io/integrations/eks-integration[Amazon EKS-intergration] in the Datree documentation.

[[add-on-datree-pro-service-account-name,add-on-datree-pro-service-account-name.title]]
=== Service account name

The service account name is datree-webhook-server-awsmp.

[[add-on-datree-pro-managed-policy,add-on-datree-pro-managed-policy.title]]
=== {aws} managed IAM policy

The managed policy is AWSLicenseManagerConsumptionPolicy. For more information, see link:aws-managed-policy/latest/reference/AWSLicenseManagerConsumptionPolicy.html[AWSLicenseManagerConsumptionPolicy,type="documentation"] in the {aws} Managed Policy Reference Guide..

[[add-on-datree-pro-iam-command,add-on-datree-pro-iam-command.title]]
=== Command to create required IAM role

The following command requires that you have an IAM [.noloc]`OpenID Connect` ([.noloc]`OIDC`) provider for your cluster. To determine whether you have one, or to create one, see <<enable-iam-roles-for-service-accounts>>. Replace [.replaceable]`my-cluster` with the name of your cluster and [.replaceable]`my-datree-role` with the name for your role. This command requires that you have https://eksctl.io[eksctl] installed on your device. If you need to use a different tool to create the role and annotate the [.noloc]`Kubernetes` service account, see <<associate-service-account-role>>.

[source,bash,subs="verbatim,attributes"]
----
eksctl create iamserviceaccount --name datree-webhook-server-awsmp --namespace datree --cluster my-cluster --role-name my-datree-role \
    --role-only --attach-policy-arn {arn-aws}iam::aws:policy/service-role/AWSLicenseManagerConsumptionPolicy --approve
----


[[add-on-datree-pro-custom-permissions,add-on-datree-pro-custom-permissions.title]]
=== Custom permissions

Custom permissions aren't used with this add-on.

[[add-on-datadog,add-on-datadog.title]]
== [.noloc]`Datadog`

[abstract]
--
Learn about the [.noloc]`Datadog` Amazon EKS add-on.
--

The add-on name is `datadog_operator` and the namespace is `datadog-agent`. [.noloc]`Datadog` publishes the add-on.

For information about the add-on, see https://docs.datadoghq.com/containers/guide/operator-eks-addon/?tab=console[Installing the Datadog Agent on Amazon EKS with the Datadog Operator Add-on] in the Datadog documentation.

[[add-on-datadog-service-account-name,add-on-datadog-service-account-name.title]]
=== Service account name

A service account isn't used with this add-on.

[[add-on-datadog-managed-policy,add-on-datadog-managed-policy.title]]
=== {aws} managed IAM policy

A managed policy isn't used with this add-on.

[[add-on-datadog-custom-permissions,add-on-datadog-custom-permissions.title]]
=== Custom IAM permissions

Custom permissions aren't used with this add-on.

[[add-on-groundcover,add-on-groundcover.title]]
== [.noloc]`Groundcover`

[abstract]
--
Learn about the [.noloc]`Groundcover` Amazon EKS add-on.
--

The add-on name is `groundcover_agent` and the namespace is `groundcover`. [.noloc]`groundcover` publishes the add-on.

For information about the add-on, see https://docs.groundcover.com/docs/~/changes/VhDDAl1gy1VIO3RIcgxD/configuration/customization-guide/customize-deployment/eks-add-on[Installing the groundcover Amazon EKS Add-on] in the groundcover documentation.

[[add-on-groundcover-service-account-name,add-on-groundcover-service-account-name.title]]
=== Service account name

A service account isn't used with this add-on.

[[add-on-groundcover-managed-policy,add-on-groundcover-managed-policy.title]]
=== {aws} managed IAM policy

A managed policy isn't used with this add-on.

[[add-on-groundcover-custom-permissions,add-on-groundcover-custom-permissions.title]]
=== Custom IAM permissions

Custom permissions aren't used with this add-on.

[[add-on-grafana,add-on-grafana.title]]
== [.noloc]`Grafana Labs`

[abstract]
--
Learn about the [.noloc]`Grafana Labs` Amazon EKS add-on.
--

The add-on name is `grafana-labs_kubernetes-monitoring` and the namespace is `monitoring`. [.noloc]`Grafana Labs` publishes the add-on.

For information about the add-on, see https://grafana.com/docs/grafana-cloud/monitor-infrastructure/kubernetes-monitoring/configuration/config-aws-eks/[Configure Kubernetes Monitoring as an Add-on with Amazon EKS] in the Grafana Labs documentation.

[[add-on-grafana-service-account-name,add-on-grafana-service-account-name.title]]
=== Service account name

A service account isn't used with this add-on.

[[add-on-grafana-managed-policy,add-on-grafana-managed-policy.title]]
=== {aws} managed IAM policy

A managed policy isn't used with this add-on.

[[add-on-grafana-custom-permissions,add-on-grafana-custom-permissions.title]]
=== Custom IAM permissions

Custom permissions aren't used with this add-on.

[[add-on-guance,add-on-guance.title]]
== [.noloc]`Guance`

* *Publisher* – [.noloc]`GUANCE`
* *Name* – `guance_datakit`
* *Namespace* – `datakit`
* *Service account name* – A service account isn't used with this add-on.
* *{aws} managed IAM policy* – A managed policy isn't used with this add-on.
* *Custom IAM permissions* – Custom permissions aren't used with this add-on.
* *Setup and usage instructions* – See https://docs.guance.com/en/datakit/datakit-eks-deploy/#add-on-install[Using Amazon EKS add-on] in the Guance documentation.


[[add-on-ha-proxy,add-on-ha-proxy.title]]
== [.noloc]`HA Proxy`

[abstract]
--
Learn about the [.noloc]`HA Proxy` Amazon EKS add-on.
--

The name is `haproxy-technologies_kubernetes-ingress-ee` and the namespace is `haproxy-controller`. [.noloc]`HA Proxy` publishes the add-on.

For information about the add-on, see https://hub.datree.io/integrations/eks-integration[Amazon EKS-intergration] in the Datree documentation.

[[add-on-ha-proxy-service-account-name,add-on-ha-proxy-service-account-name.title]]
=== Service account name

The service account name is `customer defined`.

[[add-on-ha-proxy-managed-policy,add-on-ha-proxy-managed-policy.title]]
=== {aws} managed IAM policy

The managed policy is AWSLicenseManagerConsumptionPolicy. For more information, see link:aws-managed-policy/latest/reference/AWSLicenseManagerConsumptionPolicy.html[AWSLicenseManagerConsumptionPolicy,type="documentation"] in the {aws} Managed Policy Reference Guide..

[[add-on-ha-proxy-iam-command,add-on-ha-proxy-iam-command.title]]
=== Command to create required IAM role

The following command requires that you have an IAM [.noloc]`OpenID Connect` ([.noloc]`OIDC`) provider for your cluster. To determine whether you have one, or to create one, see <<enable-iam-roles-for-service-accounts>>. Replace [.replaceable]`my-cluster` with the name of your cluster and [.replaceable]`my-haproxy-role` with the name for your role. This command requires that you have https://eksctl.io[eksctl] installed on your device. If you need to use a different tool to create the role and annotate the [.noloc]`Kubernetes` service account, see <<associate-service-account-role>>.

[source,bash,subs="verbatim,attributes"]
----
eksctl create iamserviceaccount --name service-account-name  --namespace haproxy-controller --cluster my-cluster --role-name my-haproxy-role \
    --role-only --attach-policy-arn {arn-aws}iam::aws:policy/service-role/AWSLicenseManagerConsumptionPolicy --approve
----


[[add-on-ha-proxy-custom-permissions,add-on-ha-proxy-custom-permissions.title]]
=== Custom permissions

Custom permissions aren't used with this add-on.

[[add-on-kpow,add-on-kpow.title]]
== [.noloc]`Kpow`

[abstract]
--
Learn about the [.noloc]`Kpow` Amazon EKS add-on.
--

The add-on name is `factorhouse_kpow` and the namespace is `factorhouse`. [.noloc]`Factorhouse` publishes the add-on.

For information about the add-on, see https://docs.kpow.io/installation/aws-marketplace-lm/[{aws} Marketplace LM] in the [.noloc]`Kpow` documentation.

[[add-on-kpow-service-account-name,add-on-kpow-service-account-name.title]]
=== Service account name

The service account name is `kpow`.

[[add-on-kpow-managed-policy,add-on-kpow-managed-policy.title]]
=== {aws} managed IAM policy

The managed policy is AWSLicenseManagerConsumptionPolicy. For more information, see link:aws-managed-policy/latest/reference/AWSLicenseManagerConsumptionPolicy.html[AWSLicenseManagerConsumptionPolicy,type="documentation"] in the {aws} Managed Policy Reference Guide..

[[add-on-kpow-iam-command,add-on-kpow-iam-command.title]]
=== Command to create required IAM role

The following command requires that you have an IAM [.noloc]`OpenID Connect` ([.noloc]`OIDC`) provider for your cluster. To determine whether you have one, or to create one, see <<enable-iam-roles-for-service-accounts>>. Replace [.replaceable]`my-cluster` with the name of your cluster and [.replaceable]`my-kpow-role` with the name for your role. This command requires that you have https://eksctl.io[eksctl] installed on your device. If you need to use a different tool to create the role and annotate the [.noloc]`Kubernetes` service account, see <<associate-service-account-role>>.

[source,bash,subs="verbatim,attributes"]
----
eksctl create iamserviceaccount --name kpow --namespace factorhouse --cluster my-cluster --role-name my-kpow-role \
    --role-only --attach-policy-arn {arn-aws}iam::aws:policy/service-role/AWSLicenseManagerConsumptionPolicy --approve
----


[[add-on-kpow-custom-permissions,add-on-kpow-custom-permissions.title]]
=== Custom permissions

Custom permissions aren't used with this add-on.

[[add-on-kubecost,add-on-kubecost.title]]
== [.noloc]`Kubecost`

[abstract]
--
Learn about the [.noloc]`Kubecost` Amazon EKS add-on.
--

The add-on name is `kubecost_kubecost` and the namespace is `kubecost`. [.noloc]`Kubecost` publishes the add-on.

For information about the add-on, see https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations[{aws} Cloud Billing Integration] in the [.noloc]`Kubecost` documentation.

If your cluster is version `1.23` or later, you must have the <<ebs-csi,Store Kubernetes volumes with Amazon EBS>> installed on your cluster. otherwise you will receive an error.

[[add-on-kubecost-service-account-name,add-on-kubecost-service-account-name.title]]
=== Service account name

A service account isn't used with this add-on.

[[add-on-kubecost-managed-policy,add-on-kubecost-managed-policy.title]]
=== {aws} managed IAM policy

A managed policy isn't used with this add-on.

[[add-on-kubecost-custom-permissions,add-on-kubecost-custom-permissions.title]]
=== Custom IAM permissions

Custom permissions aren't used with this add-on.

[[add-on-kasten,add-on-kasten.title]]
== [.noloc]`Kasten`

[abstract]
--
Learn about the [.noloc]`Kasten` Amazon EKS add-on.
--

The add-on name is `kasten_k10` and the namespace is `kasten-io`. [.noloc]`Kasten by Veeam` publishes the add-on.

For information about the add-on, see https://docs.kasten.io/latest/install/aws-eks-addon/aws-eks-addon.html[Installing K10 on {aws} using Amazon EKS Add-on] in the Kasten documentation.

If your Amazon EKS cluster is version [.noloc]`Kubernetes` `1.23` or later, you must have the Amazon EBS CSI driver installed on your cluster with a default `StorageClass`.

[[add-on-kasten-service-account-name,add-on-kasten-service-account-name.title]]
=== Service account name

The service account name is  `k10-k10`.

[[add-on-kasten-managed-policy,add-on-kasten-managed-policy.title]]
=== {aws} managed IAM policy

The managed policy is AWSLicenseManagerConsumptionPolicy. For more information, see link:aws-managed-policy/latest/reference/AWSLicenseManagerConsumptionPolicy.html[AWSLicenseManagerConsumptionPolicy,type="documentation"] in the {aws} Managed Policy Reference Guide..

[[add-on-kasten-iam-command,add-on-kasten-iam-command.title]]
=== Command to create required IAM role

The following command requires that you have an IAM [.noloc]`OpenID Connect` ([.noloc]`OIDC`) provider for your cluster. To determine whether you have one, or to create one, see <<enable-iam-roles-for-service-accounts>>. Replace [.replaceable]`my-cluster` with the name of your cluster and [.replaceable]`my-kasten-role` with the name for your role. This command requires that you have https://eksctl.io[eksctl] installed on your device. If you need to use a different tool to create the role and annotate the [.noloc]`Kubernetes` service account, see <<associate-service-account-role>>.

[source,bash,subs="verbatim,attributes"]
----
eksctl create iamserviceaccount --name k10-k10 --namespace kasten-io --cluster my-cluster --role-name my-kasten-role \
    --role-only --attach-policy-arn {arn-aws}iam::aws:policy/service-role/AWSLicenseManagerConsumptionPolicy --approve
----


[[add-on-kasten-custom-permissions,add-on-kasten-custom-permissions.title]]
=== Custom permissions

Custom permissions aren't used with this add-on.

[[add-on-kong,add-on-kong.title]]
== [.noloc]`Kong`

[abstract]
--
Learn about the [.noloc]`Kong` Amazon EKS add-on.
--

The add-on name is `kong_konnect-ri` and the namespace is `kong`. [.noloc]`Kong` publishes the add-on.

For information about the add-on, see https://kong.github.io/aws-marketplace-addon-kong-gateway/[Installing the Kong Gateway EKS Add-on] in the Kong documentation.

If your cluster is version `1.23` or later, you must have the <<ebs-csi,Store Kubernetes volumes with Amazon EBS>> installed on your cluster. otherwise you will receive an error.

[[add-on-kong-service-account-name,add-on-kong-service-account-name.title]]
=== Service account name

A service account isn't used with this add-on.

[[add-on-kong-managed-policy,add-on-kong-managed-policy.title]]
=== {aws} managed IAM policy

A managed policy isn't used with this add-on.

[[add-on-kong-custom-permissions,add-on-kong-custom-permissions.title]]
=== Custom IAM permissions

Custom permissions aren't used with this add-on.

[[add-on-leaksignal,add-on-leaksignal.title]]
== [.noloc]`LeakSignal`

[abstract]
--
Learn about the [.noloc]`LeakSignal` Amazon EKS add-on.
--

The add-on name is `leaksignal_leakagent` and the namespace is `leakagent`. [.noloc]`LeakSignal` publishes the add-on.

For information about the add-on, see https://www.leaksignal.com/docs/LeakAgent/Deployment/{aws}%20EKS%20Addon/[Install the LeakAgent add-on] in the LeakSignal documentation

If your cluster is version `1.23` or later, you must have the <<ebs-csi,Store Kubernetes volumes with Amazon EBS>> installed on your cluster. otherwise you will receive an error.

[[add-on-leaksignal-service-account-name,add-on-leaksignal-service-account-name.title]]
=== Service account name

A service account isn't used with this add-on.

[[add-on-leaksignal-managed-policy,add-on-leaksignal-managed-policy.title]]
=== {aws} managed IAM policy

A managed policy isn't used with this add-on.

[[add-on-leaksignal-custom-permissions,add-on-leaksignal-custom-permissions.title]]
=== Custom IAM permissions

Custom permissions aren't used with this add-on.

[[add-on-netapp,add-on-netapp.title]]
== [.noloc]`NetApp`

[abstract]
--
Learn about the [.noloc]`NetApp` Amazon EKS add-on.
--

The add-on name is `netapp_trident-operator` and the namespace is `trident`. [.noloc]`NetApp` publishes the add-on.

For information about the add-on, see https://docs.netapp.com/us-en/trident/trident-use/trident-aws-addon.html[Configure the Trident EKS add-on] in the NetApp documentation.

[[add-on-netapp-service-account-name,add-on-netapp-service-account-name.title]]
=== Service account name

A service account isn't used with this add-on.

[[add-on-netapp-managed-policy,add-on-netapp-managed-policy.title]]
=== {aws} managed IAM policy

A managed policy isn't used with this add-on.

[[add-on-netapp-custom-permissions,add-on-netapp-custom-permissions.title]]
=== Custom IAM permissions

Custom permissions aren't used with this add-on.

[[add-on-new-relic,add-on-new-relic.title]]
== [.noloc]`New Relic`

[abstract]
--
Learn about the [.noloc]`New Relic` Amazon EKS add-on.
--

The add-on name is `new-relic_kubernetes-operator` and the namespace is `newrelic`. [.noloc]`New Relic` publishes the add-on.

For information about the add-on, see https://docs.newrelic.com/docs/infrastructure/amazon-integrations/connect/eks-add-on[Installing the New Relic Add-on for EKS] in the New Relic documentation.

[[add-on-new-relic-service-account-name,add-on-new-relic-service-account-name.title]]
=== Service account name

A service account isn't used with this add-on.

[[add-on-new-relic-managed-policy,add-on-new-relic-managed-policy.title]]
=== {aws} managed IAM policy

A managed policy isn't used with this add-on.

[[add-on-new-relic-custom-permissions,add-on-new-relic-custom-permissions.title]]
=== Custom IAM permissions

Custom permissions aren't used with this add-on.

[[add-on-rafay,add-on-rafay.title]]
== [.noloc]`Rafay`

[abstract]
--
Learn about the [.noloc]`Rafay` Amazon EKS add-on.
--

The add-on name is `rafay-systems_rafay-operator` and the namespace is `rafay-system`. [.noloc]`Rafay` publishes the add-on.

For information about the add-on, see https://docs.rafay.co/clusters/import/eksaddon/[Installing the Rafay Amazon EKS Add-on] in the Rafay documentation.

[[add-on-rafay-service-account-name,add-on-rafay-service-account-name.title]]
=== Service account name

A service account isn't used with this add-on.

[[add-on-rafay-managed-policy,add-on-rafay-managed-policy.title]]
=== {aws} managed IAM policy

A managed policy isn't used with this add-on.

[[add-on-rafay-custom-permissions,add-on-rafay-custom-permissions.title]]
=== Custom IAM permissions

Custom permissions aren't used with this add-on.

[[add-on-rad,add-on-rad.title]]
== [.noloc]`Rad Security`

* *Publisher* – [.noloc]`RAD SECURITY`
* *Name* – `rad-security_rad-security`
* *Namespace* – `ksoc`
* *Service account name* – A service account isn't used with this add-on.
* *{aws} managed IAM policy* – A managed policy isn't used with this add-on.
* *Custom IAM permissions* – Custom permissions aren't used with this add-on.
* *Setup and usage instructions* – See https://docs.rad.security/docs/installing-ksoc-in-the-aws-marketplace[Installing Rad Through The {aws} Marketplace] in the Rad Security documentation.


[[add-on-solarwinds,add-on-solarwinds.title]]
== [.noloc]`SolarWinds`

* *Publisher* – [.noloc]`SOLARWINDS`
* *Name* – `solarwinds_swo-k8s-collector-addon`
* *Namespace* – `solarwinds`
* *Service account name* – A service account isn't used with this add-on.
* *{aws} managed IAM policy* – A managed policy isn't used with this add-on.
* *Custom IAM permissions* – Custom permissions aren't used with this add-on.
* *Setup and usage instructions* – See https://documentation.solarwinds.com/en/success_center/observability/content/configure/configure-kubernetes.htm#MonitorAmazonEKS[Monitor an Amazon EKS cluster] in the SolarWinds documentation.


[[add-on-solo,add-on-solo.title]]
== [.noloc]`Solo`

[abstract]
--
Learn about the [.noloc]`Solo` Amazon EKS add-on.
--

The add-on name is `solo-io_istio-distro` and the namespace is `istio-system`. [.noloc]`Solo` publishes the add-on.

For information about the add-on, see https://docs.solo.io/gloo-mesh-enterprise/main/setup/install/eks_addon/[Installing Istio] in the Solo.io documentation..

[[add-on-solo-service-account-name,add-on-solo-service-account-name.title]]
=== Service account name

A service account isn't used with this add-on.

[[add-on-solo-managed-policy,add-on-solo-managed-policy.title]]
=== {aws} managed IAM policy

A managed policy isn't used with this add-on.

[[add-on-solo-custom-permissions,add-on-solo-custom-permissions.title]]
=== Custom IAM permissions

Custom permissions aren't used with this add-on.

[[add-on-snyk,add-on-snyk.title]]
== [.noloc]`Snyk`

* *Publisher* – [.noloc]`SNYK`
* *Name* – `snyk_runtime-sensor`
* *Namespace* – `snyk_runtime-sensor`
* *Service account name* – A service account isn't used with this add-on.
* *{aws} managed IAM policy* – A managed policy isn't used with this add-on.
* *Custom IAM permissions* – Custom permissions aren't used with this add-on.
* *Setup and usage instructions* – See https://docs.snyk.io/integrate-with-snyk/snyk-runtime-sensor[Snyk runtime sensor] in the Snyk user docs.


[[add-on-stormforge,add-on-stormforge.title]]
== [.noloc]`Stormforge`

[abstract]
--
Learn about the [.noloc]`Stormforge` Amazon EKS add-on.
--

The add-on name is `stormforge_optimize-Live` and the namespace is `stormforge-system`. [.noloc]`Stormforge` publishes the add-on.

For information about the add-on, see https://docs.stormforge.io/optimize-live/getting-started/install-v2/[Installing the StormForge Agent] in the StormForge documentation.

[[add-on-stormforge-service-account-name,add-on-stormforge-service-account-name.title]]
=== Service account name

A service account isn't used with this add-on.

[[add-on-stormforge-managed-policy,add-on-stormforge-managed-policy.title]]
=== {aws} managed IAM policy

A managed policy isn't used with this add-on.

[[add-on-stormforge-custom-permissions,add-on-stormforge-custom-permissions.title]]
=== Custom IAM permissions

Custom permissions aren't used with this add-on.

[[add-on-splunk,add-on-splunk.title]]
== [.noloc]`Splunk`

[abstract]
--
Learn about the [.noloc]`Splunk` Amazon EKS add-on.
--

The add-on name is `splunk_splunk-otel-collector-chart` and the namespace is `splunk-monitoring`. [.noloc]`Splunk` publishes the add-on.

For information about the add-on, see https://docs.splunk.com/observability/en/gdi/opentelemetry/install-k8s-addon-eks.html[Install the Splunk add-on for Amazon EKS] in the Splunk documentation.

[[add-on-splunk-service-account-name,add-on-splunk-service-account-name.title]]
=== Service account name

A service account isn't used with this add-on.

[[add-on-splunk-managed-policy,add-on-splunk-managed-policy.title]]
=== {aws} managed IAM policy

A managed policy isn't used with this add-on.

[[add-on-splunk-custom-permissions,add-on-splunk-custom-permissions.title]]
=== Custom IAM permissions

Custom permissions aren't used with this add-on.

[[add-on-teleport,add-on-teleport.title]]
== [.noloc]`Teleport`

[abstract]
--
Learn about the [.noloc]`Teleport` Amazon EKS add-on.
--

The add-on name is `teleport_teleport` and the namespace is `teleport`. [.noloc]`Teleport` publishes the add-on.

For information about the add-on, see https://goteleport.com/how-it-works/[How Teleport Works] in the [.noloc]`Teleport` documentation.

[[add-on-teleport-service-account-name,add-on-teleport-service-account-name.title]]
=== Service account name

A service account isn't used with this add-on.

[[add-on-teleport-managed-policy,add-on-teleport-managed-policy.title]]
=== {aws} managed IAM policy

A managed policy isn't used with this add-on.

[[add-on-teleport-custom-permissions,add-on-teleport-custom-permissions.title]]
=== Custom IAM permissions

Custom permissions aren't used with this add-on.

[[add-on-tetrate,add-on-tetrate.title]]
== [.noloc]`Tetrate`

[abstract]
--
Learn about the [.noloc]`Tetrate` Amazon EKS add-on.
--

The add-on name is `tetrate-io_istio-distro` and the namespace is `istio-system`. [.noloc]`Tetrate Io` publishes the add-on.

For information about the add-on, see the https://tetratelabs.io/[Tetrate Istio Distro] website.

[[add-on-tetrate-service-account-name,add-on-tetrate-service-account-name.title]]
=== Service account name

A service account isn't used with this add-on.

[[add-on-tetrate-managed-policy,add-on-tetrate-managed-policy.title]]
=== {aws} managed IAM policy

A managed policy isn't used with this add-on.

[[add-on-tetrate-custom-permissions,add-on-tetrate-custom-permissions.title]]
=== Custom IAM permissions

Custom permissions aren't used with this add-on.

[[add-on-upbound,add-on-upbound.title]]
== [.noloc]`Upbound Universal Crossplane`

[abstract]
--
Learn about the [.noloc]`Upbound Universal Crossplane` Amazon EKS add-on.
--

The add-on name is `upbound_universal-crossplane` and the namespace is `upbound-system`. [.noloc]`Upbound` publishes the add-on.

For information about the add-on, see https://docs.upbound.io/uxp/[Upbound Universal Crossplane (UXP)] in the Upbound documentation.

[[add-on-upbound-service-account-name,add-on-upbound-service-account-name.title]]
=== Service account name

A service account isn't used with this add-on.

[[add-on-upbound-managed-policy,add-on-upbound-managed-policy.title]]
=== {aws} managed IAM policy

A managed policy isn't used with this add-on.

[[add-on-upbound-custom-permissions,add-on-upbound-custom-permissions.title]]
=== Custom IAM permissions

Custom permissions aren't used with this add-on.

[[add-on-upwind,add-on-upwind.title]]
== [.noloc]`Upwind`

[abstract]
--
Learn about the [.noloc]`Upwind` Amazon EKS add-on.
--

The add-on name is `upwind` and the namespace is `upwind`. [.noloc]`Upwind` publishes the add-on.

For information about the add-on, see https://docs.upwind.io/install-sensor/kubernetes/install?installation-method=amazon-eks-addon[Upwind documentation].

[[add-on-upwind-service-account-name,add-on-upwind-service-account-name.title]]
=== Service account name

A service account isn't used with this add-on.

[[add-on-upwind-managed-policy,add-on-upwind-managed-policy.title]]
=== {aws} managed IAM policy

A managed policy isn't used with this add-on.

[[add-on-upwind-custom-permissions,add-on-upwind-custom-permissions.title]]
=== Custom IAM permissions

Custom permissions aren't used with this add-on.


