include::../attributes.txt[]

[.topic]
[#getting-started-automode]
= Get started with Amazon EKS – EKS Auto Mode
:info_titleabbrev: Create cluster (EKS Auto Mode)

Like other EKS getting started experiences, creating your first cluster with EKS Auto Mode delegates the management of the cluster itself to {aws}.
However, EKS Auto Mode extends EKS automation by handing responsibility of many essential services needed to set up workload infrastructure (nodes, networks, and various services), making it easier to manage nodes and scale up to meet workload demands.

Choose from one of the following ways to create a cluster with EKS Auto Mode:

* <<automode-get-started-cli>>: Use the `aws` command line interface to create a cluster.
* <<automode-get-started-console>>: Use the {aws-management-console} to create a cluster.
* <<automode-get-started-eksctl>>: Use the `eksctl` command line interface to create a cluster.

If you are comparing different approaches to creating your first EKS cluster,
you should know that EKS Auto Mode has {aws} take over additional cluster management responsibilities 
that include setting up components to:

* Start up and scale nodes as workload demand increases and decreases.
* Regularly upgrade the cluster itself (control plane), node operating systems, and services running on nodes.
* Choose default settings that determine things like the size and speed of node storage and Pod network configuration.

For details on what you get with EKS Auto Mode clusters, see <<automode>>.