include::../attributes.txt[]

[.topic]
[#install-kubectl]
= Set up `kubectl` and `eksctl`
:info_titleabbrev: Set up kubectl and eksctl

[abstract]
--
Learn how to install or update the `kubectl` and `eksctl` command line tools to work with Kubernetes and Amazon EKS features.
--

Once the {aws} CLI is installed, there are two other tools you should install to create and manage your Kubernetes clusters:

* `kubectl`: The `kubectl` command line tool is the main tool you will use to manage resources within your Kubernetes cluster. This page describes how to download and set up the `kubectl` binary that matches the version of your Kubernetes cluster. See <<kubectl-install-update,Install or update kubectl>>.

* `eksctl`: The `eksctl` command line tool is made for creating EKS clusters in the {aws} cloud or on-premises (with EKS Anywhere), as well as modifying and deleting those clusters. See <<eksctl-install-update,Install eksctl>>.


[#kubectl-install-update]
== Install or update `kubectl`

This topic helps you to download and install, or update, the `kubectl` binary on your device. The binary is identical to the https://kubernetes.io/docs/tasks/tools/#kubectl[upstream community versions]. The binary is not unique to Amazon EKS or {aws}. Use the steps below to get the specific version of `kubectl` that you need, although many builders simply run `brew install kubectl` to install it.

[NOTE]
====

You must use a `kubectl` version that is within one minor version difference of your Amazon EKS cluster control plane. For example, a `{k8s-n-1}` `kubectl` client works with Kubernetes `{k8s-n-2}`, `{k8s-n-1}`, and `{k8s-n}` clusters.

====

== Step 1: Check if `kubectl` is installed

Determine whether you already have `kubectl` installed on your device.

[source,bash,subs="verbatim,attributes"]
----
kubectl version --client
----

If you have `kubectl` installed in the path of your device, the example output includes information similar to the following. If you want to update the version that you currently have installed with a later version, complete the next step, making sure to install the new version in the same location that your current version is in.

[source,bash,subs="verbatim,attributes"]
----
Client Version: v1.31.X-eks-1234567
----

If you receive no output, then you either don't have `kubectl` installed, or it's not installed in a location that's in your device's path.

== Step 2: Install or update `kubectl`

Install or update `kubectl` on one of the following operating systems:

* <<macos_kubectl>>
* <<linux_amd64_kubectl>>
* <<linux_arm64_kubectl>>
* <<windows_kubectl>>

[NOTE]
====

If downloads are slow to your {aws} Region from the {aws} Regions used in this section,
consider setting up CloudFront to front the content.
For further information, see link:AmazonCloudFront/latest/DeveloperGuide/GettingStartedSimpleDistributon.html[Get started with a basic CloudFront distribution,type="documentation"].

====


=== macOS [[macos_kubectl]]

Follow the steps below to install `kubectl` on macOS. The steps include:

* Choosing and downloading the binary for the Kubernetes version you want.
* Optionally checking the binary's checksum.
* Adding execute to the binary's permissions.
* Copying the binary to a folder in your PATH.
* Optionally adding the binary's directory to your PATH.

Procedure:

. Download the binary for your cluster's Kubernetes version from Amazon S3.
+
**** Kubernetes `1.33`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.33.0/2025-05-01/bin/darwin/amd64/kubectl
----
**** Kubernetes `1.32`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.32.3/2025-04-17/bin/darwin/amd64/kubectl
----
**** Kubernetes `1.31`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.31.7/2025-04-17/bin/darwin/amd64/kubectl
----
**** Kubernetes `1.30`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.30.11/2025-04-17/bin/darwin/amd64/kubectl
----
**** Kubernetes `1.29`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.15/2025-04-17/bin/darwin/amd64/kubectl
----
**** Kubernetes `1.28`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.28.15/2025-04-17/bin/darwin/amd64/kubectl
----
**** Kubernetes `1.27`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.16/2025-01-10/bin/darwin/amd64/kubectl
----
**** Kubernetes `1.26`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.26.15/2024-12-12/bin/darwin/amd64/kubectl
----
. (Optional) Verify the downloaded binary with the `SHA-256` checksum for your binary.
+
.. Download the `SHA-256` checksum for your cluster's Kubernetes version.
+
***** Kubernetes `1.33`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.33.0/2025-05-01/bin/darwin/amd64/kubectl.sha256
----
***** Kubernetes `1.32`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.32.3/2025-04-17/bin/darwin/amd64/kubectl.sha256
----
***** Kubernetes `1.31`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.31.7/2025-04-17/bin/darwin/amd64/kubectl.sha256
----
***** Kubernetes `1.30`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.30.11/2025-04-17/bin/darwin/amd64/kubectl.sha256
----
***** Kubernetes `1.29`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.15/2025-04-17/bin/darwin/amd64/kubectl.sha256
----
***** Kubernetes `1.28`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.28.15/2025-04-17/bin/darwin/amd64/kubectl.sha256
----
***** Kubernetes `1.27`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.16/2025-01-10/bin/darwin/amd64/kubectl.sha256
----
***** Kubernetes `1.26`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.26.15/2024-12-12/bin/darwin/amd64/kubectl.sha256
----
.. Check the `SHA-256` checksum for your downloaded binary.
+
[source,bash,subs="verbatim,attributes"]
----
openssl sha1 -sha256 kubectl
----
.. Make sure that the generated checksum in the output matches in the checksum in the downloaded `kubectl.sha256` file.
. Apply execute permissions to the binary.
+
[source,bash,subs="verbatim,attributes"]
----
chmod +x ./kubectl
----
. Copy the binary to a folder in your `PATH`. If you have already installed a version of `kubectl`, then we recommend creating a `$HOME/bin/kubectl` and ensuring that `$HOME/bin` comes first in your `$PATH`.
+
[source,bash,subs="verbatim,attributes"]
----
mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
----
. (Optional) Add the `$HOME/bin` path to your shell initialization file so that it is configured when you open a shell.
+
[source,bash,subs="verbatim,attributes"]
----
echo 'export PATH=$HOME/bin:$PATH' >> ~/.bash_profile
----

=== Linux (amd64) [[linux_amd64_kubectl]]

Follow the steps below to install `kubectl` on Linux (amd64). The steps include:

* Choosing and downloading the binary for the Kubernetes version you want.
* Optionally checking the binary's checksum.
* Adding execute to the binary's permissions.
* Copying the binary to a folder in your PATH.
* Optionally adding the binary's directory to your PATH.

Procedure:

. Download the `kubectl` binary for your cluster's Kubernetes version from Amazon S3.
+
**** Kubernetes `1.33`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.33.0/2025-05-01/bin/linux/amd64/kubectl
----
**** Kubernetes `1.32`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.32.3/2025-04-17/bin/linux/amd64/kubectl
----
**** Kubernetes `1.31`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.31.7/2025-04-17/bin/linux/amd64/kubectl
----
**** Kubernetes `1.30`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.30.11/2025-04-17/bin/linux/amd64/kubectl
----
**** Kubernetes `1.29`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.15/2025-04-17/bin/linux/amd64/kubectl
----
**** Kubernetes `1.28`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.28.15/2025-04-17/bin/linux/amd64/kubectl
----
**** Kubernetes `1.27`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.16/2024-12-12/bin/linux/amd64/kubectl
----
**** Kubernetes `1.26`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.26.15/2024-12-12/bin/linux/amd64/kubectl
----
. (Optional) Verify the downloaded binary with the `SHA-256` checksum for your binary.
+
.. Download the `SHA-256` checksum for your cluster's Kubernetes version from Amazon S3using the command for your device's hardware platform.
+
***** Kubernetes `1.33`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.33.0/2025-05-01/bin/linux/amd64/kubectl.sha256
----
***** Kubernetes `1.32`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.32.3/2025-04-17/bin/linux/amd64/kubectl.sha256
----
***** Kubernetes `1.31`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.31.7/2025-04-17/bin/linux/amd64/kubectl.sha256
----
***** Kubernetes `1.30`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.30.11/2025-04-17/bin/linux/amd64/kubectl.sha256
----
***** Kubernetes `1.29`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.15/2025-04-17/bin/linux/amd64/kubectl.sha256
----
***** Kubernetes `1.28`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.28.15/2025-04-17/bin/linux/amd64/kubectl.sha256
----
***** Kubernetes `1.27`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.16/2024-12-12/bin/linux/amd64/kubectl.sha256
----
***** Kubernetes `1.26`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.26.15/2024-12-12/bin/linux/amd64/kubectl.sha256
----
.. Check the `SHA-256` checksum for your downloaded binary with one of the following commands.
+ 
[source,bash,subs="verbatim,attributes"]
----
sha256sum -c kubectl.sha256
----
or
+
----
openssl sha1 -sha256 kubectl
----
.. For the first, you should see `kubectl: OK`, for the second, you can check that the generated checksum in the output matches in the checksum in the downloaded `kubectl.sha256` file.
. Apply execute permissions to the binary.
+
[source,bash,subs="verbatim,attributes"]
----
chmod +x ./kubectl
----
. Copy the binary to a folder in your `PATH`. If you have already installed a version of `kubectl`, then we recommend creating a `$HOME/bin/kubectl` and ensuring that `$HOME/bin` comes first in your `$PATH`.
+
[source,bash,subs="verbatim,attributes"]
----
mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
----
. (Optional) Add the `$HOME/bin` path to your shell initialization file so that it is configured when you open a shell.
+
NOTE: This step assumes you are using the Bash shell; if you are using another shell, change the command to use your specific shell initialization file.
+
[source,bash,subs="verbatim,attributes"]
----
echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc
----

=== Linux (arm64) [[linux_arm64_kubectl]]

Follow the steps below to install `kubectl` on Linux (arm64). The steps include:

* Choosing and downloading the binary for the Kubernetes version you want.
* Optionally checking the binary's checksum.
* Adding execute to the binary's permissions.
* Copying the binary to a folder in your PATH.
* Optionally adding the binary's directory to your PATH.

Procedure:

. Download the `kubectl` binary for your cluster's Kubernetes version from Amazon S3.
+
**** Kubernetes `1.33`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.33.0/2025-05-01/bin/linux/arm64/kubectl
----
**** Kubernetes `1.32`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.32.3/2025-04-17/bin/linux/arm64/kubectl
----
**** Kubernetes `1.31`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.31.7/2025-04-17/bin/linux/arm64/kubectl
----
**** Kubernetes `1.30`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.30.11/2025-04-17/bin/linux/arm64/kubectl
----
**** Kubernetes `1.29`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.15/2025-04-17/bin/linux/arm64/kubectl
----
**** Kubernetes `1.28`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.28.15/2025-04-17/bin/linux/arm64/kubectl
----
**** Kubernetes `1.27`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.16/2024-12-12/bin/linux/arm64/kubectl
----
**** Kubernetes `1.26`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.26.15/2024-12-12/bin/linux/arm64/kubectl
----
. (Optional) Verify the downloaded binary with the `SHA-256` checksum for your binary.
+
.. Download the `SHA-256` checksum for your cluster's Kubernetes version from Amazon S3using the command for your device's hardware platform.
+
***** Kubernetes `1.33`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.33.0/2025-05-01/bin/linux/arm64/kubectl.sha256
----
***** Kubernetes `1.32`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.32.3/2025-04-17/bin/linux/arm64/kubectl.sha256
----
***** Kubernetes `1.31`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.31.7/2025-04-17/bin/linux/arm64/kubectl.sha256
----
***** Kubernetes `1.30`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.30.11/2025-04-17/bin/linux/arm64/kubectl.sha256
----
***** Kubernetes `1.29`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.15/2025-04-17/bin/linux/arm64/kubectl.sha256
----
***** Kubernetes `1.28`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.28.15/2025-04-17/bin/linux/arm64/kubectl.sha256
----
***** Kubernetes `1.27`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.16/2024-12-12/bin/linux/arm64/kubectl.sha256
----
***** Kubernetes `1.26`
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.26.15/2024-12-12/bin/linux/arm64/kubectl.sha256
----
.. Check the `SHA-256` checksum for your downloaded binary with one of the following commands.
+ 
[source,bash,subs="verbatim,attributes"]
----
sha256sum -c kubectl.sha256
----
or
+
[source,bash,subs="verbatim,attributes"]
----
openssl sha1 -sha256 kubectl
----
.. For the first, you should see `kubectl: OK`, for the second, you can check that the generated checksum in the output matches in the checksum in the downloaded `kubectl.sha256` file.
. Apply execute permissions to the binary.
+
[source,bash,subs="verbatim,attributes"]
----
chmod +x ./kubectl
----
. Copy the binary to a folder in your `PATH`. If you have already installed a version of `kubectl`, then we recommend creating a `$HOME/bin/kubectl` and ensuring that `$HOME/bin` comes first in your `$PATH`.
+
[source,bash,subs="verbatim,attributes"]
----
mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
----
. (Optional) Add the `$HOME/bin` path to your shell initialization file so that it is configured when you open a shell.
+
NOTE: This step assumes you are using the Bash shell; if you are using another shell, change the command to use your specific shell initialization file.
+
[source,bash,subs="verbatim,attributes"]
----
echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc
----

=== Windows [[windows_kubectl]]

Follow the steps below to install `kubectl` on Windows. The steps include:

* Choosing and downloading the binary for the Kubernetes version you want.
* Optionally checking the binary's checksum.
* Copying the binary to a folder in your PATH.
* Optionally adding the binary's directory to your PATH.

Procedure:

. Open a PowerShell terminal.
. Download the `kubectl` binary for your cluster's Kubernetes version from Amazon S3.
+
**** Kubernetes `1.33`
+
[source,bash,subs="verbatim,attributes"]
----
curl.exe -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.33.0/2025-05-01/bin/windows/amd64/kubectl.exe
----
**** Kubernetes `1.32`
+
[source,bash,subs="verbatim,attributes"]
----
curl.exe -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.32.3/2025-04-17/bin/windows/amd64/kubectl.exe
----
**** Kubernetes `1.31`
+
[source,bash,subs="verbatim,attributes"]
----
curl.exe -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.31.7/2025-04-17/bin/windows/amd64/kubectl.exe
----
**** Kubernetes `1.30`
+
[source,bash,subs="verbatim,attributes"]
----
curl.exe -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.30.11/2025-04-17/bin/windows/amd64/kubectl.exe
----
**** Kubernetes `1.29`
+
[source,bash,subs="verbatim,attributes"]
----
curl.exe -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.15/2025-04-17/bin/windows/amd64/kubectl.exe
----
**** Kubernetes `1.28`
+
[source,bash,subs="verbatim,attributes"]
----
curl.exe -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.28.15/2025-04-17/bin/windows/amd64/kubectl.exe
----
**** Kubernetes `1.27`
+
[source,bash,subs="verbatim,attributes"]
----
curl.exe -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.16/2024-12-12/bin/windows/amd64/kubectl.exe
----
**** Kubernetes `1.26`
+
[source,bash,subs="verbatim,attributes"]
----
curl.exe -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.26.15/2024-12-12/bin/windows/amd64/kubectl.exe
----
. (Optional) Verify the downloaded binary with the `SHA-256` checksum for your binary.
+
.. Download the `SHA-256` checksum for your cluster's Kubernetes version for Windows.
+
***** Kubernetes `1.33`
+
[source,bash,subs="verbatim,attributes"]
----
curl.exe -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.33.0/2025-05-01/bin/windows/amd64/kubectl.exe.sha256
----
***** Kubernetes `1.32`
+
[source,bash,subs="verbatim,attributes"]
----
curl.exe -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.32.3/2025-04-17/bin/windows/amd64/kubectl.exe.sha256
----
***** Kubernetes `1.31`
+
[source,bash,subs="verbatim,attributes"]
----
curl.exe -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.31.7/2025-04-17/bin/windows/amd64/kubectl.exe.sha256
----
***** Kubernetes `1.30`
+
[source,bash,subs="verbatim,attributes"]
----
curl.exe -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.30.11/2025-04-17/bin/windows/amd64/kubectl.exe.sha256
----
***** Kubernetes `1.29`
+
[source,bash,subs="verbatim,attributes"]
----
curl.exe -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.15/2025-04-17/bin/windows/amd64/kubectl.exe.sha256
----
***** Kubernetes `1.28`
+
[source,bash,subs="verbatim,attributes"]
----
curl.exe -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.28.15/2025-04-17/bin/windows/amd64/kubectl.exe.sha256
----
***** Kubernetes `1.27`
+
[source,bash,subs="verbatim,attributes"]
----
curl.exe -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.16/2024-12-12/bin/windows/amd64/kubectl.exe.sha256
----
***** Kubernetes `1.26`
+
[source,bash,subs="verbatim,attributes"]
----
curl.exe -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.26.15/2024-12-12/bin/windows/amd64/kubectl.exe.sha256
----
.. Check the `SHA-256` checksum for your downloaded binary.
+
[source,bash,subs="verbatim,attributes"]
----
Get-FileHash kubectl.exe
----
.. Make sure that the generated checksum in the output matches in the checksum in the downloaded `kubectl.sha256` file. The PowerShell output should be an uppercase equivalent string of characters.
. Copy the binary to a folder in your `PATH`. If you have an existing directory in your `PATH` that you use for command line utilities, copy the binary to that directory. Otherwise, complete the following steps.
+
.. Create a new directory for your command line binaries, such as `C:\bin`.
.. Copy the `kubectl.exe` binary to your new directory.
.. Edit your user or system `PATH` environment variable to add the new directory to your `PATH`.
.. Close your PowerShell terminal and open a new one to pick up the new `PATH` variable.
. After you install `kubectl`, you can verify its version.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl version --client
----
. When first installing `kubectl`, it isn't yet configured to communicate with any server. We will cover this configuration as needed in other procedures. If you ever need to update the configuration to communicate with a particular cluster, you can run the following command. Replace [.replaceable]`region-code` with the {aws} Region that your cluster is in. Replace [.replaceable]`my-cluster` with the name of your cluster.
+
[source,bash,subs="verbatim,attributes"]
----
aws eks update-kubeconfig --region region-code --name my-cluster
----
. Consider configuring auto completion, which lets you use the tab key to complete `kubectl` subcommands after typing the first few letters. See https://kubernetes.io/docs/reference/kubectl/quick-reference/#kubectl-autocomplete[Kubectl autocomplete] in the Kubernetes documentation for details.  


[#eksctl-install-update]
== Install `eksctl`

The `eksctl` CLI is used to work with EKS clusters. It automates many individual tasks. See https://eksctl.io/installation[Installation] in the `eksctl` documentation for instructions on installing `eksctl`. For Linux, use the UNIX instructions.

When using `eksctl` the IAM security principal that you're using must have permissions to work with Amazon EKS IAM roles, service linked roles, {aws} CloudFormation, a VPC, and related resources. For more information, see link:service-authorization/latest/reference/list_amazonelastickubernetesservice.html[Actions, resources, and condition keys for Amazon Elastic Container Service for Kubernetes,type="documentation"] and link:IAM/latest/UserGuide/using-service-linked-roles.html[Using service-linked roles,type="documentation"] in the IAM User Guide. You must complete all steps in this guide as the same user. To check the current user, run the following command:

[source,bash,subs="verbatim,attributes"]
----
aws sts get-caller-identity
----


[#install-kubectl-next-steps]
== Next steps

* <<quickstart,Quickstart: Deploy a web app and store data>>
