include::../attributes.txt[]

[.topic]
[#automode-get-started-console]
= Create an EKS Auto Mode Cluster with the {aws-management-console}
:info_titleabbrev: Management console

Creating an EKS Auto Mode cluster in the {aws-management-console} requires less configuration than other options. EKS integrates with {aws} IAM and VPC Networking to help you create the resources associated with an EKS cluster.

You have two options to create a cluster in the console:

* Quick configuration (with EKS Auto Mode)
* Custom configuration 

In this topic, you will learn how to create an EKS Auto Mode cluster using the Quick configuration option. 

== Create an EKS Auto Mode using the quick configuration option

You must be logged into the {aws-management-console} with sufficent permissions to manage {aws} resources including: EC2 instances, EC2 networking, EKS clusters, and IAM roles. 

. Navigate to the EKS Console
. Click *Create cluster*
. Confirm the *Quick configuration* option is selected
. Determine the following values, or use the defaults for a test cluster.
** Cluster *Name*
** Kubernetes Version
. Select the Cluster IAM Role. If this is your first time creating an EKS Auto Mode cluster, use the *Create recommended role* option. 
** Optionally, you can reuse a single Cluster IAM Role in your {aws} account for all EKS Auto Mode clusters. 
** The Cluster IAM Role includes required permissions for EKS Auto Mode to manage resources including EC2 instances, EBS volumes, and EC2 load balancers. 
** The *Create recommended role* option pre-fills all fields with recommended values. Select *Next* and then *Create*. The role will use the suggested `AmazonEKSAutoClusterRole` name. 
** If you recently created a new role, use the *Refresh* icon to reload the role selection dropdown. 
. Select the Node IAM Role. If this is your first time creating an EKS Auto Mode cluster, use the *Create recommended role* option. 
** Optionally, you can reuse a single Node IAM Role in your {aws} account for all EKS Auto Mode clusters. 
** The Node IAM Role includes required permissions for Auto Mode nodes to connect to the cluster. The Node IAM Role must include permissions to retrieve ECR images for your containers. 
** The *Create recommended role* option pre-fills all fields with recommended values. Select *Next* and then *Create*. The role will use the suggested `AmazonEKSAutoNodeRole` name. 
** If you recently created a new role, use the *Refresh* icon to reload the role selection dropdown. 
. Select the VPC for your EKS Auto Mode cluster. Choose the *Create VPC* to create a new VPC for EKS, or choose a VPC you previously created for EKS. 
** If you use the VPC Console to create a new VPC, {aws} suggests you create at least one NAT Gateway per Availability Zone. Otherwise, you can use all other defaults. 
** For more information and details of IPv6 cluster requirements, see <<creating-a-vpc>>.
. (optional) EKS Auto Mode automatically populates the private subnets for your selected VPC. You can remove unwanted subnets. 
** EKS automatically selects private subnets from the VPC following best practices. You can optionally select additional subnets from the VPC, such as public subnets.
. (optional) Select *View quick configuration defaults* to review all configuration values for the new cluster. The table indicates some values are not editable after the cluster is created. 
. Select *Create cluster* . Note it may take fifteen minutes for cluster creation to complete.

== Next Steps

* Learn how to <<sample-storage-workload,Deploy a Sample Workload to your EKS Auto Mode cluster>>

//call out refactored IAM