include::../attributes.txt[]

[#eks-networking]
= Configure networking for Amazon EKS clusters
:info_titleabbrev: Configure networking

[abstract]
--
Learn how to configure networking for your Amazon EKS cluster using a VPC, subnets, security groups, and networking add-ons to ensure secure and efficient communication.
--

Your Amazon EKS cluster is created in a VPC. Pod networking is provided by the Amazon VPC Container Network Interface (CNI) plugin for nodes that run on {aws} infrastructure. If you are running nodes on your own infrastructure, see <<hybrid-nodes-cni>>. This chapter includes the following topics for learning more about networking for your cluster.

[.topiclist]
[[Topic List]]

[#add-existing-subnet]
== Add an existing VPC Subnet to an Amazon EKS cluster from the management console

. Navigate to your cluster in the management console
. From the *Networking* tab select *Manage VPC Resources*
. From the *Subnets* dropdown, select additional subnets from the VPC of your cluster. 

To create a new VPC Subnet:

* xref:network-requirements-subnets[Review EKS Subnet Requirements]
* See link:vpc/latest/userguide/create-subnets.html["Create a Subnet",type="documentation"] in the Amazon Virtual Private Cloud User Guide.

include::network-reqs.adoc[leveloffset=+1]

include::creating-a-vpc.adoc[leveloffset=+1]

include::sec-group-reqs.adoc[leveloffset=+1]

include::eks-networking-add-ons.adoc[leveloffset=+1]

