[.topic]
[#kube-proxy-add-on-self-managed-update]
= Update the Kubernetes `kube-proxy` self-managed add-on
:info_titleabbrev: Update

include::../attributes.txt[]

[IMPORTANT]
====

We recommend adding the Amazon EKS type of the add-on to your cluster instead of using the self-managed type of the add-on. If you're not familiar with the difference between the types, see <<eks-add-ons>>. For more information about adding an Amazon EKS add-on to your cluster, see <<creating-an-add-on>>. If you're unable to use the Amazon EKS add-on, we encourage you to submit an issue about why you can't to the https://github.com/aws/containers-roadmap/issues[Containers roadmap GitHub repository].

====

[#managing-kube-proxy-prereqs]
== Prerequisites

* An existing Amazon EKS cluster. To deploy one, see <<getting-started>>.


[#managing-kube-proxy-considerations]
== Considerations

* `Kube-proxy` on an Amazon EKS cluster has the same https://kubernetes.io/releases/version-skew-policy/#kube-proxy[compatibility and skew policy as Kubernetes]. Learn how to <<addon-compat,Verifying Amazon EKS add-on version compatibility with a cluster>>.
. Confirm that you have the self-managed type of the add-on installed on your cluster. Replace [.replaceable]`my-cluster` with the name of your cluster.
+
[source,bash,subs="verbatim,attributes"]
----
aws eks describe-addon --cluster-name my-cluster --addon-name kube-proxy --query addon.addonVersion --output text
----
+
If an error message is returned, you have the self-managed type of the add-on installed on your cluster. The remaining steps in this topic are for updating the self-managed type of the add-on. If a version number is returned, you have the Amazon EKS type of the add-on installed on your cluster. To update it, use the procedure in  <<updating-an-add-on,Updating an Amazon EKS add-on>>, rather than using the procedure in this topic. If you're not familiar with the differences between the add-on types, see <<eks-add-ons>>.
. See which version of the container image is currently installed on your cluster.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl describe daemonset kube-proxy -n kube-system | grep Image
----
+
An example output is as follows.
+
[source,bash,subs="verbatim,attributes"]
----
Image:    602401143452.dkr.ecr.region-code.amazonaws.com/eks/kube-proxy:v1.29.1-eksbuild.2
----
+
In the example output, [.replaceable]`v1.29.1-eksbuild.2` is the version installed on the cluster.
. Update the `kube-proxy` add-on by replacing [.replaceable]`602401143452` and [.replaceable]`region-code` with the values from your output in the previous step. Replace [.replaceable]`v1.30.6-eksbuild.3` with the `kube-proxy` version listed in the <<managing-kube-proxy-images,Latest available self-managed kube-proxy container image version for each Amazon EKS cluster version>> table.
+
IMPORTANT: The manifests for each image type are different and not compatible between the _default_ or _minimal_ image types. You must use the same image type as the previous image, so that the entrypoint and arguments match.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl set image daemonset.apps/kube-proxy -n kube-system kube-proxy=602401143452.dkr.ecr.region-code.amazonaws.com/eks/kube-proxy:v1.30.6-eksbuild.3
----
+
An example output is as follows.
+
[source,bash,subs="verbatim,attributes"]
----
daemonset.apps/kube-proxy image updated
----
. Confirm that the new version is now installed on your cluster.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl describe daemonset kube-proxy -n kube-system | grep Image | cut -d ":" -f 3
----
+
An example output is as follows.
+
[source,bash,subs="verbatim,attributes"]
----
v1.30.0-eksbuild.3
----
. If you're using `x86` and `Arm` nodes in the same cluster and your cluster was deployed before August 17, 2020. Then, edit your `kube-proxy` manifest to include a node selector for multiple hardware architectures with the following command. This is a one-time operation. After you've added the selector to your manifest, you don't need to add it each time you update the add-on. If your cluster was deployed on or after August 17, 2020, then `kube-proxy` is already multi-architecture capable.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl edit -n kube-system daemonset/kube-proxy
----
+
Add the following node selector to the file in the editor and then save the file. For an example of where to include this text in the editor, see the https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.11/config/master/aws-k8s-cni.yaml#L265-#L269[CNI manifest] file on [.noloc]`GitHub`. This enables [.noloc]`Kubernetes` to pull the correct hardware image based on the node's hardware architecture.
+
[source,yaml,subs="verbatim,attributes"]
----
- key: "kubernetes.io/arch"
  operator: In
  values:
  - amd64
  - arm64
----
. If your cluster was originally created with [.noloc]`Kubernetes` version `1.14` or later, then you can skip this step because `kube-proxy` already includes this `Affinity Rule`. If you originally created an Amazon EKS cluster with [.noloc]`Kubernetes` version `1.13` or earlier and intend to use Fargate nodes in your cluster, then edit your `kube-proxy` manifest to include a `NodeAffinity` rule to prevent `kube-proxy` [.noloc]`Pods` from scheduling on Fargate nodes. This is a one-time edit. Once you've added the `Affinity Rule` to your manifest, you don't need to add it each time that you update the add-on. Edit your `kube-proxy` [.noloc]`DaemonSet`.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl edit -n kube-system daemonset/kube-proxy
----
+
Add the following `Affinity Rule` to the [.noloc]`DaemonSet`spec`` section of the file in the editor and then save the file. For an example of where to include this text in the editor, see the https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.11/config/master/aws-k8s-cni.yaml#L270-#L273[CNI manifest] file on [.noloc]`GitHub`.
+
[source,yaml,subs="verbatim,attributes"]
----
- key: eks.amazonaws.com/compute-type
  operator: NotIn
  values:
  - fargate
----


📝 https://github.com/search?q=repo%3Aawsdocs%2Famazon-eks-user-guide+%5B%23kube-proxy-add-on-self-managed-update%5D&type=code[Edit this page on GitHub]