//!!NODE_ROOT <section>
[.topic]
[[lbc-remove,lbc-remove.title]]
= Migrate apps from deprecated ALB [.noloc]`Ingress Controller`
:info_titleabbrev: Migrate from deprecated controller

include::../attributes.txt[]

[abstract]
--
Learn how to migrate from the deprecated ALB Ingress Controller to the latest [.noloc]`{aws} Load Balancer Controller` release, ensuring smooth transition and uninterrupted load balancing capabilities.
--

This topic describes how to migrate from deprecated controller versions. More specifically, it describes how to remove deprecated versions of the [.noloc]`{aws} Load Balancer Controller`.  



* Deprecated versions cannot be upgraded. You must remove them first, and then install a current version.
+
[[lbc-deprecated-list]]
* Deprecated versions include:
+
** {aws} ALB Ingress Controller for [.noloc]`Kubernetes` ("Ingress Controller"), a predecessor to the [.noloc]`{aws} Load Balancer Controller`.
** Any `0.1.[.replaceable]``x``` version of the [.noloc]`{aws} Load Balancer Controller`


[[lbc-remove-desc,lbc-remove-desc.title]]
== Remove the deprecated controller version

[NOTE]
====

You may have installed the deprecated version using Helm or manually with [.noloc]`Kubernetes` manifests. Complete the procedure using the tool that you originally installed it with.

====
. If you installed the `incubator/aws-alb-ingress-controller` Helm chart, uninstall it.
+
[source,shell,subs="verbatim,attributes"]
----
helm delete aws-alb-ingress-controller -n kube-system
----
. If you have version `0.1.[.replaceable]``x``` of the `eks-charts/aws-load-balancer-controller` chart installed, uninstall it. The upgrade from `0.1.[.replaceable]``x``` to version `1.0.0` doesn't work due to incompatibility with the webhook API version. 
+
[source,shell,subs="verbatim,attributes"]
----
helm delete aws-load-balancer-controller -n kube-system
----
. Check to see if the controller is currently installed.
+
[source,shell,subs="verbatim,attributes"]
----
kubectl get deployment -n kube-system alb-ingress-controller
----
+
This is the output if the controller isn't installed.  
+
+
This is the output if the controller is installed.
+
[source,bash,subs="verbatim,attributes"]
----
NAME                   READY UP-TO-DATE AVAILABLE AGE
alb-ingress-controller 1/1   1          1         122d
----
. Enter the following commands to remove the controller.
+
[source,shell,subs="verbatim,attributes"]
----
kubectl delete -f https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/v1.1.8/docs/examples/alb-ingress-controller.yaml
kubectl delete -f https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/v1.1.8/docs/examples/rbac-role.yaml
----


[[lbc-migrate,lbc-migrate.title]]
== Migrate to [.noloc]`{aws} Load Balancer Controller`

To migrate from the ALB Ingress Controller for [.noloc]`Kubernetes` to the [.noloc]`{aws} Load Balancer Controller`, you need to:

. Remove the ALB Ingress Controller (see above).
. <<lbc-overview,Install the {aws} Load Balancer Controller.>>
. Add an additional policy to the IAM Role used by the [.noloc]`{aws} Load Balancer Controller`. This policy permits the LBC to manage resources created by the ALB Ingress Controller for [.noloc]`Kubernetes`.
. Download the IAM policy. This policy permits the [.noloc]`{aws} Load Balancer Controller` to manage resources created by the ALB Ingress Controller for [.noloc]`Kubernetes`. You can also https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/install/iam_policy_v1_to_v2_additional.json[view the policy].
+
[source,shell,subs="verbatim,attributes"]
----
curl -O https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.11.0/docs/install/iam_policy_v1_to_v2_additional.json
----
. If your cluster is in the {aws} GovCloud (US-East) or {aws} GovCloud (US-West) {aws} Regions, then replace `{arn-aws}` with `arn:aws-us-gov:`..
+
[source,shell,subs="verbatim,attributes"]
----
sed -i.bak -e 's|{arn-aws}|arn:aws-us-gov:|' iam_policy_v1_to_v2_additional.json
----
. Create the IAM policy and note the ARN that is returned.
+
[source,shell,subs="verbatim,attributes"]
----
aws iam create-policy \
  --policy-name AWSLoadBalancerControllerAdditionalIAMPolicy \
  --policy-document file://iam_policy_v1_to_v2_additional.json
----
. Attach the IAM policy to the IAM role used by the [.noloc]`{aws} Load Balancer Controller`. Replace [.replaceable]`your-role-name` with the name of the role, such as `AmazonEKSLoadBalancerControllerRole`. 
+
If you created the role using `eksctl`, then to find the role name that was created, open the link:cloudformation[{aws} CloudFormation console,type="console"] and select the *eksctl-[.replaceable]`my-cluster`-addon-iamserviceaccount-kube-system-aws-load-balancer-controller* stack. Select the  *Resources* tab. The role name is in the  *Physical ID* column.  If your cluster is in the {aws} GovCloud (US-East) or {aws} GovCloud (US-West) {aws} Regions, then replace `{arn-aws}` with `arn:aws-us-gov:`.
+
[source,shell,subs="verbatim,attributes"]
----
aws iam attach-role-policy \
  --role-name your-role-name \
  --policy-arn {arn-aws}iam::111122223333:policy/AWSLoadBalancerControllerAdditionalIAMPolicy
----


