include::../attributes.txt[]

[.topic]
[#lbc-helm]
= Install {aws} Load Balancer Controller with Helm
:info_titleabbrev: Install with Helm

[abstract]
--
Learn how to install the {aws} Load Balancer Controller on Amazon EKS using Helm to manage K8s load balancing with {aws} Cloud. Discover the prerequisites and steps for creating an IAM role, installing with Helm, and verifying the controller deployment.
--

[TIP]
====
With Amazon EKS Auto Mode, you don't need to install or upgrade networking add-ons. Auto Mode includes pod networking and load balancing capabilities. 

For more information, see <<automode>>.
====

This topic describes how to install the {aws} Load Balancer Controller using Helm, a package manager for Kubernetes, and `eksctl`. The controller is installed with default options. For more information about the controller, including details on configuring it with annotations, see the https://kubernetes-sigs.github.io/aws-load-balancer-controller/[{aws} Load Balancer Controller Documentation] on GitHub.  

In the following steps, replace the [.replaceable]`example values` with your own values.

[#lbc-prereqs]
== Prerequisites

Before starting this tutorial, you must complete the following steps:

* Create an Amazon EKS cluster. To create one, see <<getting-started>>.
* Install https://helm.sh/docs/helm/helm_install/[Helm] on your local machine.
* Make sure that your Amazon VPC CNI plugin for Kubernetes, `kube-proxy`, and CoreDNS add-ons are at the minimum versions listed in <<boundserviceaccounttoken-validated-add-on-versions,Service account tokens>>.
* Learn about {aws} Elastic Load Balancing concepts. For more information, see the link:elasticloadbalancing/latest/userguide/[Elastic Load Balancing User Guide,type="documentation"].
* Learn about Kubernetes https://kubernetes.io/docs/concepts/services-networking/service/[service] and https://kubernetes.io/docs/concepts/services-networking/ingress/[ingress] resources.

[#lbc-considerations]
=== Considerations

Before proceeding with the configuration steps on this page, consider the following:

* The IAM policy and role (`AmazonEKSLoadBalancerControllerRole`) can be reused across multiple EKS clusters in the same {aws} account.
* If you're installing the controller on the same cluster where the role (`AmazonEKSLoadBalancerControllerRole`) was originally created, go to <<lbc-helm-install,Step 2: Install Load Balancer Controller>> after verifying the role exists.
* If you're using IAM Roles for Service Accounts (IRSA), IRSA must be set up for each cluster, and the OpenID Connect (OIDC) provider ARN in the role's trust policy is specific to each EKS cluster. Additionally, if you're installing the controller on a new cluster with an existing `AmazonEKSLoadBalancerControllerRole`, update the role's trust policy to include the new cluster's OIDC provider and create a new service account with the appropriate role annotation. To determine whether you already have an OIDC provider, or to create one, see <<enable-iam-roles-for-service-accounts>>.

[#lbc-helm-iam]
== Step 1: Create IAM Role using `eksctl`
The following steps refer to the {aws} Load Balancer Controller *v2.13.0* release version. For more information about all releases, see the https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/[{aws} Load Balancer Controller Release Page] on GitHub.

. Download an IAM policy for the {aws} Load Balancer Controller that allows it to make calls to {aws} APIs on your behalf. 
+
[source,shell,subs="verbatim,attributes"]
----
curl -O https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.13.0/docs/install/iam_policy.json
----
** If you are a non-standard {aws} partition, such as a Government or China region, https://github.com/kubernetes-sigs/aws-load-balancer-controller/tree/main/docs/install[review the policies on GitHub] and download the appropriate policy for your region.  
. Create an IAM policy using the policy downloaded in the previous step. 
+
[source,shell,subs="verbatim,attributes"]
----
aws iam create-policy \
    --policy-name AWSLoadBalancerControllerIAMPolicy \
    --policy-document file://iam_policy.json
----
+
NOTE: If you view the policy in the {aws-management-console}, the console shows warnings for the *ELB* service, but not for the *ELB v2* service. This happens because some of the actions in the policy exist for *ELB v2*, but not for *ELB*. You can ignore the warnings for *ELB*.
. Replace the values for cluster name, region code, and account ID. 
+
[source,shell,subs="verbatim,attributes"]
----
eksctl create iamserviceaccount \
    --cluster=<cluster-name> \
    --namespace=kube-system \
    --name=aws-load-balancer-controller \
    --attach-policy-arn={arn-aws}iam::<AWS_ACCOUNT_ID>:policy/AWSLoadBalancerControllerIAMPolicy \
    --override-existing-serviceaccounts \
    --region <aws-region-code> \
    --approve
----


[#lbc-helm-install]
== Step 2: Install {aws} Load Balancer Controller

. Add the `eks-charts` Helm chart repository. {aws} maintains https://github.com/aws/eks-charts[this repository] on GitHub.
+
[source,shell,subs="verbatim,attributes"]
----
helm repo add eks https://aws.github.io/eks-charts
----
. Update your local repo to make sure that you have the most recent charts.
+
[source,shell,subs="verbatim,attributes"]
----
helm repo update eks
----
. Install the {aws} Load Balancer Controller.
+
If you're deploying the controller to Amazon EC2 nodes that have https://aws.github.io/aws-eks-best-practices/security/docs/iam/#restrict-access-to-the-instance-profile-assigned-to-the-worker-node[restricted access to the Amazon EC2 instance metadata service (IMDS)], or if you're deploying to Fargate or Amazon EKS Hybrid Nodes, then add the following flags to the `helm` command that follows:
+
*** `--set region=[.replaceable]``region-code```
*** `--set vpcId=[.replaceable]``vpc-xxxxxxxx```
+
Replace [.replaceable]`my-cluster` with the name of your cluster. In the following command, `aws-load-balancer-controller` is the Kubernetes service account that you created in a previous step.
+
For more information about configuring the helm chart, see https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/values.yaml[values.yaml] on GitHub.
+
[source,shell,subs="verbatim,attributes"]
----
helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
  -n kube-system \
  --set clusterName=my-cluster \
  --set serviceAccount.create=false \
  --set serviceAccount.name=aws-load-balancer-controller \
  --version 1.13.0
----


[IMPORTANT]
====
The deployed chart doesn't receive security updates automatically. You need to manually upgrade to a newer chart when it becomes available. When upgrading, change [.replaceable]`install` to `upgrade` in the previous command.
====

The `helm install` command automatically installs the custom resource definitions (CRDs) for the controller. The `helm upgrade` command does not. If you use `helm upgrade,` you must manually install the CRDs. Run the following command to install the CRDs:

[source,shell,subs="verbatim,attributes"]
----
wget https://raw.githubusercontent.com/aws/eks-charts/master/stable/aws-load-balancer-controller/crds/crds.yaml 
kubectl apply -f crds.yaml
----


[#lbc-helm-verify]
== Step 3: Verify that the controller is installed
. Verify that the controller is installed.
+
[source,shell,subs="verbatim,attributes"]
----
kubectl get deployment -n kube-system aws-load-balancer-controller
----
+
An example output is as follows.
+
[source,bash,subs="verbatim,attributes"]
----
NAME                           READY   UP-TO-DATE   AVAILABLE   AGE
aws-load-balancer-controller   2/2     2            2           84s
----
+
You receive the previous output if you deployed using Helm. If you deployed using the Kubernetes manifest, you only have one replica.
. Before using the controller to provision {aws} resources, your cluster must meet specific requirements. For more information, see <<alb-ingress>> and <<network-load-balancing>>.


