include::attributes.txt[]

[.topic]
[#doc-history]
= Document history

[abstract]
--
Important updates to the Amazon EKS documentation, sorted by date, with brief descriptions of each update and when they occurred.
--

The following table describes some of the major updates and new features for the Amazon EKS User Guide. To receive notifications when this table gets a new entry, you can subscribe to the following URL with an RSS reader:

[source,none]
----
https://docs.aws.amazon.com/eks/latest/userguide/doc-history.rss
----

[.updates]
== Updates


[.update,date="2025-10-02"]
=== Kubernetes version `1.34`
[.update-ulink]
link:eks/latest/userguide/kubernetes-versions.html#kubernetes-1-34[type="documentation"]
 
Added Kubernetes version `1.34` support for new clusters and version upgrades.


[.update,date="2025-09-22"]
=== Configurable node auto repair
[.update-ulink]
link:eks/latest/userguide/node-health.html[type="documentation"]

Amazon EKS now provides more granular control over the node auto repair behavior.


[.update,date="2025-08-27"]
=== Refresh cluster insights
[.update-ulink]
link:eks/latest/userguide/view-cluster-insights.html[type="documentation"]

You can now manually refresh cluster insights.


[.update,date="2025-08-26"]
=== {aws} managed policy updates
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html[type="documentation"]

Added permission to `AmazonEKSServiceRolePolicy`. This role can attach new access policy `AmazonEKSEventPolicy`. Restricted permissions for `ec2:DeleteLaunchTemplate` and `ec2:TerminateInstances`.


[.update,date="2025-08-19"]
=== Cross-service confused deputy prevention
[.update-ulink]
link:eks/latest/userguide/cross-service-confused-deputy-prevention.html[type="documentation"]

Added a topic with an example trust policy that you can apply for Cross-service confused deputy prevention.
Amazon EKS accepts the `aws:SourceArn` and `aws:SourceAccount` conditions in the trust policy of an EKS cluster role.


[.update,date="2025-07-30"]
=== Amazon EKS platform version update
[.update-ulink]
link:eks/latest/userguide/platform-versions.html[type="documentation"]

This is a new platform version with security fixes and enhancements. This includes new patch versions of Kubernetes `1.33.2`, `1.32.6`, `1.31.10`, and `1.30.14`.


[.update,date="2025-07-15"]
=== VPC CNI Multi-NIC feature for multi-homed pods
[.update-ulink]
link:eks/latest/userguide/pod-multiple-network-interfaces.html[type="documentation"]

Amazon EKS adds multi-homed pods to the VPC CNI. Now you can configure a workload and the VPC CNI assigned IP addresses from every NIC on the EC2 instance to each pod. The application can make concurrent connections to use the bandwidth from each NIC. Every network interface is configured in the same subnet and security groups as the node.

Previously, you needed to use Multus CNI to run multiple other CNIs to create multi-homed pods. Documentation and steps to do this have been moved to link:eks/latest/userguide/pod-multus.html[type="documentation"].


[.update,date="2025-06-30"]
=== VPC CNI troubleshooting content update
[.update-ulink]
link:eks/latest/userguide/network-policies-troubleshooting.html[type="documentation"]

Expanded the troubleshooting page for Kubernetes _network policy_ in the VPC CNI. Added the CRDs and RBAC permissions, and 12 known issues.


[.update,date="2025-06-26"]
=== Amazon EKS platform version update
[.update-ulink]
link:eks/latest/userguide/platform-versions.html[type="documentation"]

This is a new platform version with security fixes and enhancements. There aren't any new patch versions of Kubernetes in these platform version.

[.update,date="2025-06-26"]
=== {aws} managed policy updates
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html[type="documentation"]

Added `ssmmessages:OpenDataChannel` permission to `AmazonEKSLocalOutpostServiceRolePolicy`.


[.update,date="2025-06-20"]
=== {aws} managed policy updates
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html[type="documentation"]

Added permissions to `AmazonEKSServiceRolePolicy` and `AmazonEKSComputePolicy` to allow Amazon EKS Auto Mode to launch instances by using the EC2 On-Demand Capacity Reservations in your account. Also, added the permissions to `AmazonEKSComputePolicy` for Amazon EKS to create the EC2 Spot service-linked role on your behalf.


[.update,date="2025-06-19"]
=== Managed policy updates
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html[type="documentation"]

Added `AmazonEKSDashboardConsoleReadOnly` policy.


[.update,date="2025-06-13"]
=== Amazon EKS Auto Mode update to `NodeClass`
[.update-ulink]
link:eks/latest/userguide/create-node-class.html#auto-node-class-spec[type="documentation"]

The `NodeClass` template for Auto Mode nodes added configuration for separate pod subnets. This adds the optional keys `podSubnetSelectorTerms` and `podSecurityGroupSelectorTerms` to set the subnets and security groups for the pods.


[.update,date="2025-06-11"]
=== Amazon EKS platform version update
[.update-ulink]
link:eks/latest/userguide/platform-versions.html[type="documentation"]

This is a new platform version with security fixes and enhancements. There aren't any new patch versions of Kubernetes in these platform version.

[.update,date="2025-06-11"]
=== Target secondary and cross-account roles with EKS Pod Identities 
[.update-ulink]
link:eks/latest/userguide/pod-id-assign-target-role.html[type="documentation"]

Amazon EKS adds __target IAM roles__ to EKS Pod Identities for automated role chaining. You can use this to automatically assume a role in another account and EKS Pod Identity rotates the temporary credentials. Each Pod Identity association must have an IAM role in the same account to assume first, then it uses that role to assume the target role.


[.update,date="2025-06-06"]
=== Amazon EKS {aws} Region expansion
Amazon EKS is now available in the Asia Pacific (Taipei) (`ap-east-2`) {aws} Region.

[.update,date="2025-06-05"]
=== `IPv6` access control for dual-stack public endpoints for new `IPv6` clusters
[.update-ulink]
link:eks/latest/userguide/cluster-endpoint.html[type="documentation"]

Amazon EKS adds `IPv6` CIDR blocks to control access to the public cluster endpoint for new `IPv6` clusters. Previously, you could only add `IPv4` CIDR blocks to allow traffic to the public cluster endpoint, even for dual-stack cluster endpoints.


[.update,date="2025-05-30"]
=== Amazon EKS platform version update
[.update-ulink]
link:eks/latest/userguide/platform-versions.html[type="documentation"]

This is a new platform version with security fixes and enhancements. This includes new patch versions of Kubernetes `1.32.5`, `1.31.9`, and `1.30.13`.


[.update,date="2025-05-29"]
=== Kubernetes version `1.33`
[.update-ulink]
link:eks/latest/userguide/kubernetes-versions-standard.html#kubernetes-1-33[type="documentation"]

Added Kubernetes version `1.33` support for new clusters and version upgrades.


[.update,date="2025-05-29"]
=== New cluster insights for EKS Hybrid Nodes
[.update-ulink]
link:eks/latest/userguide/cluster-insights.html[type="documentation"]

Amazon EKS adds new cluster insights that check the configuration of your hybrid nodes. These insight checks will warn you about issues with on-premises nodes and pods and the remote network configuration of the cluster. 


[.update,date="2025-05-23"]
=== Add-on support for Amazon FSx CSI driver
[.update-ulink]
link:eks/latest/userguide/fsx-csi.html[type="documentation"]

You can now use the {aws} Management Console, {aws} CLI, and API to manage the Amazon FSx CSI driver.


[.update,date="2025-05-22"]
=== Edit Prometheus scrapers in the console
[.update-ulink]
link:eks/latest/userguide/prometheus.html#viewing-prometheus-scraper-details[type="documentation"]

You can now edit Amazon Managed Service for Prometheus scrapers in the Amazon EKS console.


[.update,date="2025-05-21"]
=== Managed policy updates
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html[type="documentation"]

Added `AmazonEKSDashboardServiceRolePolicy` policy.


[.update,date="2025-05-16"]
=== Amazon EKS platform version update
[.update-ulink]
link:eks/latest/userguide/platform-versions.html[type="documentation"]

This is a new platform version with security fixes and enhancements. There aren't any new patch versions of Kubernetes in these platform versions.




[.update,date="2025-05-02"]
=== New pages for Amazon FSx for Lustre performance
[.update-ulink]
link:eks/latest/userguide/fsx-csi.html[type="documentation"]

Added new topics with details on optimizing Amazon FSx for Lustre performance.


[.update,date="2025-04-30"]
=== Amazon EKS Auto Mode update to `NodeClass`
[.update-ulink]
link:eks/latest/userguide/create-node-class.html#auto-node-class-spec[type="documentation"]

The `NodeClass` template for Auto Mode nodes added configuration for forward network proxies. This adds the optional key `advancedNetworking` to set your HTTPS proxy.


[.update,date="2025-04-29"]
=== Amazon EKS platform version update
[.update-ulink]
link:eks/latest/userguide/platform-versions.html[type="documentation"]

This is a new platform version with security fixes and enhancements. There aren't any new patch versions of Kubernetes in these platform versions.


[.update,date="2025-04-29"]
=== Bottlerocket for hybrid nodes
[.update-ulink]
link:eks/latest/userguide/hybrid-nodes-bottlerocket.html[type="documentation"]

Bottlerocket is now available for EKS Hybrid Nodes.


[.update,date="2025-04-18"]
=== New concepts pages for hybrid networking
[.update-ulink]
link:eks/latest/userguide/hybrid-nodes-concepts.html[type="documentation"]

Added pages for concepts of EKS Hybrid Nodes. These cover the on-premises and cloud networking in detail with diagrams.


[.update,date="2025-04-16"]
=== {aws} managed policy updates
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html[type="documentation"]

Added permissions to `AmazonEKSClusterPolicy` to allow Amazon EKS to elastic network interfaces created by the VPC CNI. This is required so that EKS can clean up elastic network interfaces that are left behind if the VPC CNI quits unexpectedly.


[.update,date="2025-04-14"]
=== {aws} managed policy updates
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-updates[type="documentation"]

Added permissions to `AmazonEKSServiceRolePolicy` to allow EKS AI/ML customers to add Egress rules to the default EKS Cluster security group.


=== Kubernetes version 1.31 is now available for local clusters on {aws} Outposts
[.update-ulink]
link:eks/latest/userguide/eks-outposts-platform-versions.html[type="documentation"]

You can now create an Amazon EKS local cluster on an {aws} Outposts using Kubernetes version 1.31.


[.update,date="2025-03-31"]
=== Node health for EKS Hybrid Nodes
[.update-ulink]
link:eks/latest/userguide/node-health.html[type="documentation"]

You can use `eks-node-monitoring-agent` on hybrid nodes, starting from version `1.2.0-eksbuild.1`. Run `eks-node-monitoring-agent` as an Amazon EKS add-on to detect and show health issues.


[.update,date="2025-03-31"]
=== EKS Hybrid Nodes for existing clusters
[.update-ulink]
link:eks/latest/userguide/hybrid-nodes-cluster-update.html[type="documentation"]

You can now add, change, or remove the hybrid nodes configuration of existing clusters. Previously, you could only add the hybrid nodes configuration to new clusters when you created them.
With Amazon EKS Hybrid Nodes, you can use your on-premises and edge infrastructure as nodes in Amazon EKS clusters. {aws} manages the {aws}-hosted Kubernetes control plane of the Amazon EKS cluster, and you manage the hybrid nodes that run in your on-premises or edge environments.


[.update,date="2025-03-28"]
=== Rollback: Prevent accidental upgrades with cluster insights
[.update-ulink]
link:eks/latest/userguide/update-cluster.html#update-cluster-control-plane[type="documentation"]

Amazon EKS has temporarily rolled back a feature that would
require you to use a `--force` flag to upgrade your cluster when there were certain cluster insight issues. For more information, see link:https://github.com/aws/containers-roadmap/issues/2570[Temporary rollback of enforcing upgrade insights on update cluster version] on GitHub.


[.update,date="2025-03-27"]
=== Bottlerocket FIPS AMIs
[.update-ulink]
link:eks/latest/userguide/bottlerocket-fips-amis.html[type="documentation"]

Bottlerocket FIPS AMIs are now available in standard managed node groups.


//[.update,date="2025-03-26"]
//=== Prevent accidental upgrades with cluster insights
//[.update-ulink]
//link:eks/latest/userguide/update-cluster.html#update-cluster-control-plane[type="documentation"]

//Cluster insights will proactively prevent you from upgrading your cluster for certain issues. You can override upgrade-blocking readiness checks if needed.


[.update,date="2025-02-28"]
=== {aws} managed policy updates
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html[type="documentation"]

Added permissions to `AmazonEKSServiceRolePolicy` to allow Amazon EKS to terminate EC2 instances created by Auto Mode.
Added permissions to `AmazonEKSServiceRolePolicy` to allow Amazon EKS to terminate EC2 instances created by Auto Mode. 


[.update,date="2025-01-27"]
=== Update strategies for managed node groups
[.update-ulink]
link:eks/latest/userguide/managed-node-update-behavior.html#managed-node-update-upgrade[type="documentation"]

You can now use update strategies to configure the version update process for managed node groups. This introduces the _minimal_ update strategy to terminate nodes before making new ones, which is useful in capacity constrained environments. The _default_ update strategy continues the existing behavior.


[.update,date="2025-01-23"]
=== Kubernetes version `1.32`
[.update-ulink]
link:eks/latest/userguide/kubernetes-versions.html#kubernetes-1-32[type="documentation"]

Added Kubernetes version `1.32` support for new clusters and version upgrades.

[.update,date="2025-01-14"]
=== Amazon EKS {aws} Region expansion
Amazon EKS is now available in the Asia Pacific (Thailand) Region (`ap-southeast-7`) and Mexico (Central) (`mx-central-1`) {aws} Regions. EKS Auto Mode and VPC Endpoints for the EKS API aren't available in either Region.


[.update,date="2025-01-13"]
=== {aws} managed policy updates
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html[type="documentation"]

Added multiple permissions to `AmazonEBSCSIDriverPolicy` to allow the Amazon EBS CSI Driver restore all snapshots, enable Fast Snapshot Restore (FSR) on EBS volumes, and modify tags on volumes.


[.update,date="2024-12-26"]
=== {aws} managed policy updates
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html[type="documentation"]

Added permissions to `AmazonEKSLoadBalancingPolicy`.


[.update,date="2024-12-20"]
=== Updated cluster insights
[.update-ulink]
link:eks/latest/userguide/cluster-insights.html[type="documentation"]

Amazon EKS upgrade insights will now warn about more cluster health and version compatibility issues. It can detect issues between different Kubernetes and Amazon EKS components such as `kubelet`, `kube-proxy`, and Amazon EKS add-ons.


[.update,date="2024-12-16"]
=== Node monitoring agent and auto repair
[.update-ulink]
link:eks/latest/userguide/node-health.html[type="documentation"]

You can use the new `eks-node-monitoring-agent` as an Amazon EKS add-on to detect and show health issues. You can also enable node auto repair to automatically replace nodes when issues are detected.


[.update,date="2024-12-01"]
=== Amazon EKS Hybrid Nodes
[.update-ulink]
link:eks/latest/userguide/hybrid-nodes-overview.html[type="documentation"]

You can now run node on-premises connected to Amazon EKS clusters. With Amazon EKS Hybrid Nodes, you can use your on-premises and edge infrastructure as nodes in Amazon EKS clusters. {aws} manages the {aws}-hosted Kubernetes control plane of the Amazon EKS cluster, and you manage the hybrid nodes that run in your on-premises or edge environments.


[.update,date="2024-12-01"]
=== Amazon EKS Auto Mode
[.update-ulink]
link:eks/latest/userguide/automode.html[type="documentation"]

Amazon EKS Auto Mode fully automates Kubernetes cluster infrastructure management for compute, storage, and networking on {aws}. It simplifies Kubernetes management by automatically provisioning infrastructure, selecting optimal compute instances, dynamically scaling resources, continuously optimizing costs, patching operating systems, and integrating with {aws} security services.


[.update,date="2024-11-22"]
=== {aws} managed policy updates
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html[type="documentation"]
 
Updated `AWSServiceRoleForAmazonEKSNodegroup` for compatibility with China regions.


[.update,date="2024-11-22"]
=== Amazon EKS platform version update
[.update-ulink]
link:eks/latest/userguide/platform-versions.html[type="documentation"]

This is a new platform version with security fixes and enhancements. This includes new patch versions of Kubernetes `1.31.2`, `1.30.6`, `1.29.10`, and `1.28.15`.


[.update,date="2024-11-21"]
=== {aws} managed policy updates
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html[type="documentation"]

EKS updated {aws} managed policy `AmazonEKSLocalOutpostClusterPolicy`. Added `ec2:DescribeAvailabilityZones` permission so the {aws} Cloud Controller Manager on the cluster control plane can identify the Availability Zone that each node is in.


[.update,date="2024-11-21"]
=== Kubernetes version 1.30 is now available for local clusters on {aws} Outposts
[.update-ulink]
link:eks/latest/userguide/eks-outposts-platform-versions.html[type="documentation"]

You can now create an Amazon EKS local cluster on an {aws} Outposts using Kubernetes version 1.30.


[.update,date="2024-11-20"]
=== Bottlerocket AMIs that use FIPS 140-3
[.update-ulink]
link:eks/latest/userguide/retrieve-ami-id-bottlerocket.html[type="documentation"]

Bottlerocket AMIs are available that are preconfigured to use FIPS 140-3 validated cryptographic modules. This includes the Amazon Linux 2023 Kernel Crypto API Cryptographic Module and the {aws}-LC Cryptographic Module.


[.update,date="2024-11-20"]
=== {aws} managed policy updates
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html[type="documentation"]

Updated `AWSServiceRoleForAmazonEKSNodegroup` policy to allow `ec2:RebootInstances` for instances created by Amazon EKS managed node groups. Restricted the `ec2:CreateTags` permissions for Amazon EC2 resources.


[.update,date="2024-11-18"]
=== Observability dashboard
[.update-ulink]
link:eks/latest/userguide/observability-dashboard.html[type="documentation"]

The observability dashboard helps you to quickly detect, troubleshoot, and remediate issues. There are also new link:eks/latest/userguide/cloudwatch.html[CloudWatch vended metrics,type="documentation"] available in the `AWS/EKS` namespace. 


[.update,date="2024-11-16"]
=== {aws} managed policy updates
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html[type="documentation"]

EKS updated {aws} managed policy `AmazonEKSServiceRolePolicy`. Added permissions for EKS access policies, load balancer management, and automated cluster resource cleanup.


[.update,date="2024-11-15"]
=== New role creation in console for add-ons that support EKS Pod Identities 
[.update-ulink]
link:eks/latest/userguide/creating-an-add-on.html#_create_add_on_console[type="documentation"]

There are new steps when using the console to create or update add-ons that support EKS Pod Identities where you can automatically generate IAM roles with the appropriate name, role policy, and trust policy for the add-on.


[.update,date="2024-11-15"]
=== Managed node groups in {aws} Local Zones
[.update-ulink]
link:eks/latest/userguide/local-zones.html[type="documentation"]

Managed node groups can now be created in {aws} Local Zones.


[.update,date="2024-11-11"]
=== New metrics are available 
[.update-ulink]
link:eks/latest/userguide/view-raw-metrics.html[type="documentation"]

There are new metrics available under the API group `metrics.eks.amazonaws.com`.


[.update,date="2024-11-07"]
=== {aws} managed policy updates
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html[type="documentation"]

EKS updated {aws} managed policy `AmazonEKSComputePolicy`. Updated resource permissions for the `iam:AddRoleToInstanceProfile` action.


[.update,date="2024-11-01"]
=== {aws} managed policy updates
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html[type="documentation"]

EKS added a new {aws} managed policy: `AmazonEKSComputePolicy`


[.update,date="2024-11-01"]
=== {aws} managed policy updates
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html[type="documentation"]

Added permissions to `AmazonEKSClusterPolicy`. Added `ec2:DescribeInstanceTopology` permission to allow Amazon EKS to attach topology information to the node as labels.


[.update,date="2024-10-30"]
=== {aws} managed policy updates
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html[type="documentation"]

EKS added a new {aws} managed policy: `AmazonEKSBlockStoragePolicy`


[.update,date="2024-10-30"]
=== {aws} managed policy updates
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html[type="documentation"]

EKS added a new {aws} managed policy: `AmazonEKSLoadBalancingPolicy`


[.update,date="2024-10-29"]
=== {aws} managed policy updates
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html[type="documentation"]

Added `cloudwatch:PutMetricData` permissions to `AmazonEKSServiceRolePolicy` to allow Amazon EKS to publish metrics to Amazon CloudWatch.


[.update,date="2024-10-28"]
=== {aws} managed policy updates
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html[type="documentation"]

EKS added a new {aws} managed policy: `AmazonEKSNetworkingPolicy`


[.update,date="2024-10-21"]
=== {aws} managed policy updates
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html[type="documentation"]

Added `autoscaling:ResumeProcesses`, `autoscaling:SuspendProcesses`, and associated permissions to `AWSServiceRoleForAmazonEKSNodegroup` in China regions to integrate with Amazon Application Recovery Controller for EKS. No changes to other regions. 


[.update,date="2024-10-21"]
=== Dual-stack endpoints for new `IPv6` clusters
[.update-ulink]
link:eks/latest/userguide/cluster-endpoint.html[Configure endpoint access,type="documentation"]

Connect to new `IPv6` clusters with a `eks-cluster.[.replaceable]``region``.api.aws` endpoint that is dual-stack. This endpoint is returned when you describe these clusters. `kubectl` and other Kubernetes API clients in `IPv4`, `IPv6`, or dual-stack environments can resolve and connect to these endpoints for public or private clusters.


[.update,date="2024-10-10"]
=== {aws} managed policy updates
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html[type="documentation"]

Added permissions to `AmazonEKSServicePolicy` and `AmazonEKSServiceRolePolicy`. Added `ec2:GetSecurityGroupsForVpc` and associated tag permissions to allow EKS to read security group information and update related tags.


[.update,date="2024-10-11"]
=== AL2023 accelerated AMIs
[.update-ulink]
link:eks/latest/userguide/retrieve-ami-id.html[type="documentation"]

You can now use accelerated `NVIDIA` and {aws} Neuron instances for AMIs based on AL2023.


[.update,date="2024-10-10"]
=== New source format

We have switched over to a new source format with some layout changes. There are temporary minor formatting issues that we are addressing.


[.update,date="2024-10-03"]
=== {aws} managed policy updates - New policy
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-updates[type="documentation"]

EKS added a new {aws} managed policy.

[.update,date="2024-09-24"]
=== Kubernetes version `1.31`
[.update-ulink]
link:eks/latest/userguide/kubernetes-versions.html#kubernetes-1-31[type="documentation"]

Added Kubernetes version `1.31` support for new clusters and version upgrades.


[.update,date="2024-08-21"]
=== {aws} managed policy updates - Update to an existing policy
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-updates[type="documentation"]

Amazon EKS updated an existing {aws} managed policy.


[.update,date="2024-08-20"]
=== Kubernetes version 1.29 is now available for local clusters on {aws} Outposts
[.update-ulink]
link:eks/latest/userguide/eks-outposts-platform-versions.html[type="documentation"]

You can now create an Amazon EKS local cluster on an {aws} Outposts using Kubernetes version 1.29.


[.update,date="2024-08-14"]
=== EKS Pod Identity in {aws} GovCloud (US)
[.update-ulink]
link:eks/latest/userguide/pod-identites.html[type="documentation"]

Amazon EKS Pod Identities associate an IAM role with a Kubernetes service account. With this feature, you no longer need to provide extended permissions to the node IAM role. This way, Pods on that node can call {aws} APIs. Unlike IAM roles for service accounts, EKS Pod Identities are completely inside EKS; you don't need an OIDC identity provider.


[.update,date="2024-08-09"]
=== Scenario-driven content updates
We renamed and updated topics to be more scenario-driven throughout the entire guide.


[.update,date="2024-08-07"]
=== Dual-stack VPC interface endpoints for Amazon EKS
[.update-ulink]
link:eks/latest/userguide/vpc-interface-endpoints.html[type="documentation"]

You can now create dual-stack VPC interface endpoints for Amazon EKS with both `IPv4` and `IPv6` IP addresses and DNS names. 


[.update,date="2024-08-01"]
=== New dual-stack endpoints for the Amazon EKS APIs with `IPv6` addresses
[.update-ulink]
link:eks/latest/userguide/network-reqs.html[type="documentation"]

The EKS API for creating and managing clusters, and the OIDC issuer URLs for clusters have new dual-stack endpoints. The new DNS name for the Amazon EKS API is `eks.[.replaceable]``region``.api.aws` which resolves to `IPv4` addresses and `IPv6` addresses. New clusters have a new dual-stack OIDC issuer URL (`oidc-eks.[.replaceable]``region``.api.aws`).


[.update,date="2024-07-01"]
=== Capacity Blocks for managed node groups
[.update-ulink]
link:eks/latest/userguide/capacity-blocks-mng.html[type="documentation"]

You can now use Capacity Blocks for managed node groups.


[.update,date="2024-06-28"]
=== Auto Scaling Group metrics collection enabled by default
[.update-ulink]
link:eks/latest/userguide/enable-asg-metrics.html[type="documentation"]

Amazon EKS managed node groups now have Amazon EC2 Auto Scaling group metrics enabled by default with no additional charge. Previously, you had to do several steps to enable this feature.


[.update,date="2024-06-27"]
=== {aws} managed policy updates - Update to an existing policy
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-updates[type="documentation"]

Amazon EKS updated an existing {aws} managed policy.


[.update,date="2024-06-12"]
=== Improvements to AMI information references
[.update-ulink]
link:eks/latest/userguide/eks-optimized-amis.html[type="documentation"]

We made improvements to the AMI information references, in particular for Bottlerocket.


[.update,date="2024-06-12"]
=== Kubernetes version `1.26`
[.update-ulink]
link:eks/latest/userguide/kubernetes-versions.html[type="documentation"]

Kubernetes version `1.26` is now in extended support.


[.update,date="2024-05-23"]
=== Kubernetes version `1.30`
[.update-ulink]
link:eks/latest/userguide/kubernetes-versions.html#kubernetes-1-30[type="documentation"]

Added Kubernetes version `1.30` support for new clusters and version upgrades.


[.update,date="2024-05-14"]
=== CoreDNS Autoscaling
[.update-ulink]
link:eks/latest/userguide/coredns-autoscaling.html[type="documentation"]

CoreDNS autoscaler will dynamically adapt the number of replicas of the CoreDNS deployment in an EKS cluster based on the number of nodes and CPU cores. This feature works for CoreDNS `v1.9` and the latest platform version of EKS release version `1.25` and later.


[.update,date="2024-05-14"]
=== Amazon EKS platform version update
[.update-ulink]
link:eks/latest/userguide/platform-versions.html[type="documentation"]

This is a new platform version with security fixes and enhancements. This includes new patch versions of Kubernetes `1.29.4`, `1.28.9`, and `1.27.13`.


[.update,date="2024-04-10"]
=== CloudWatch Container Insights support for Windows
[.update-ulink]
link:eks/latest/userguide/cloudwatch.html[type="documentation"]

The Amazon CloudWatch Observability Operator add-on now also allows Container Insights on Windows worker nodes in the cluster.


[.update,date="2024-04-05"]
=== Kubernetes concepts
[.update-ulink]
link:eks/latest/userguide/kubernetes-concepts.html[type="documentation"]

Added new Kubernetes concepts topic.


[.update,date="2024-04-02"]
=== Restructure Access and IAM Content
[.update-ulink]
link:eks/latest/userguide/cluster-auth.html[type="documentation"]

Move existing pages related to access and IAM topics, such as auth config map, access entries, Pod ID, and IRSA into new section. Revise overview content.


[.update,date="2024-03-13"]
=== Bottlerocket OS support for Amazon S3 CSI driver
[.update-ulink]
link:eks/latest/userguide/s3-csi.html[type="documentation"]

The Mountpoint for Amazon S3 CSI driver is now compatible with Bottlerocket.


[.update,date="2024-03-04"]
=== {aws} managed policy updates - Update to an existing policy
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-updates[type="documentation"]

Amazon EKS updated an existing {aws} managed policy.


[.update,date="2024-02-29"]
=== Amazon Linux 2023
[.update-ulink]
link:eks/latest/userguide/al2023.html[type="documentation"]

Amazon Linux 2023 (AL2023) is a new Linux-based operating system designed to provide a secure, stable, and high-performance environment for your cloud applications.


[.update,date="2024-02-26"]
=== EKS Pod Identity and IRSA support sidecars in Kubernetes `1.29`
[.update-ulink]
link:eks/latest/userguide/kubernetes-versions.html#kubernetes-1-29[type="documentation"]

In Kubernetes `1.29`, sidecar containers are available in Amazon EKS clusters. Sidecar containers are supported with IAM roles for service accounts or EKS Pod Identity. For more information about sidecars, see https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/[Sidecar Containers] in the Kubernetes documentation.


[.update,date="2024-01-23"]
=== Kubernetes version `1.29`
[.update-ulink]
link:eks/latest/userguide/kubernetes-versions.html#kubernetes-1-29[type="documentation"]

Added Kubernetes version `1.29` support for new clusters and version upgrades.


[.update,date="2024-01-16"]
=== Full release: Amazon EKS Extended Support for Kubernetes versions
[.update-ulink]
link:eks/latest/userguide/kubernetes-versions.html[type="documentation"]

Extended Kubernetes version support allows you to stay at a specific Kubernetes version for longer than 14 months.


[.update,date="2023-12-28"]
=== Amazon EKS cluster health detection in the {aws} Cloud
[.update-ulink]
link:eks/latest/userguide/troubleshooting.html#cluster-health-status[type="documentation"]

Amazon EKS detects issues with your Amazon EKS clusters and the infrastructure of the cluster prerequisites in _cluster health_. You can view the issues with your EKS clusters in the {aws-management-console} and in the `health` of the cluster in the EKS API. These issues are in addition to the issues that are detected by and displayed by the console. Previously, cluster health was only available for local clusters on {aws} Outposts.


[.update,date="2023-12-20"]
=== Amazon EKS {aws} Region expansion
Amazon EKS is now available in the Canada West (Calgary) (`ca-west-1`) {aws} Region.


[.update,date="2023-12-20"]
=== Cluster insights
[.update-ulink]
link:eks/latest/userguide/cluster-insights.html[type="documentation"]

You can now get recommendations on your cluster based on recurring checks.


[.update,date="2023-12-18"]
=== You can now grant IAM roles and users access to your cluster using access entries
[.update-ulink]
link:eks/latest/userguide/access-entries.html[type="documentation"]

Before the introduction of access entries, you granted IAM roles and users access to your cluster by adding entries to the `aws-auth` `ConfigMap`. Now each cluster has an access mode, and you can switch to using access entries on your schedule. After you switch modes, you can add users by adding access entries in the {aws} CLI, {aws} CloudFormation, and the {aws} SDKs.


[.update,date="2023-12-12"]
=== Amazon EKS platform version update
[.update-ulink]
link:eks/latest/userguide/platform-versions.html[type="documentation"]

This is a new platform version with security fixes and enhancements. This includes new patch versions of Kubernetes `1.28.4`, `1.27.8`, `1.26.11`, and `1.25.16`.


[.update,date="2023-11-27"]
=== Mountpoint for Amazon S3 CSI driver
[.update-ulink]
link:eks/latest/userguide/s3-csi.html[type="documentation"]

You can now install the Mountpoint for Amazon S3 CSI driver on Amazon EKS clusters.


[.update,date="2023-11-26"]
=== Amazon EKS Pod Identities
[.update-ulink]
link:eks/latest/userguide/pod-identites.html[type="documentation"]

Amazon EKS Pod Identities associate an IAM role with a Kubernetes service account. With this feature, you no longer need to provide extended permissions to the node IAM role. This way, Pods on that node can call {aws} APIs. Unlike IAM roles for service accounts, EKS Pod Identities are completely inside EKS; you don't need an OIDC identity provider.


[.update,date="2023-11-26"]
=== {aws} managed policy updates - Update to an existing policy
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-updates[type="documentation"]

Amazon EKS updated an existing {aws} managed policy.


[.update,date="2023-11-26"]
=== Turn on Prometheus metrics when creating a cluster
[.update-ulink]
link:eks/latest/userguide/prometheus.html[type="documentation"]

In the {aws-management-console}, you can now turn on Prometheus metrics when creating a cluster. You can also view Prometheus scraper details in the *Observability* tab.


[.update,date="2023-11-17"]
=== CSI snapshot controller
[.update-ulink]
link:eks/latest/userguide/csi-snapshot-controller.html[type="documentation"]

You can now install the CSI snapshot controller for use with compatible CSI drivers, such as the Amazon EBS CSI driver.


[.update,date="2023-11-14"]
=== ADOT Operator topic rewrite
[.update-ulink]
link:eks/latest/userguide/opentelemetry.html[type="documentation"]

The Amazon EKS add-on support for ADOT Operator section was redundant with the {aws} Distro for OpenTelemetry documentation. We migrated remaining essential information to that resource to reduce outdated and inconsistent information.


[.update,date="2023-11-10"]
=== CoreDNS EKS add-on support for Prometheus metrics
[.update-ulink]
link:eks/latest/userguide/managing-coredns.html[type="documentation"]

The `v1.10.1-eksbuild.5`, `v1.9.3-eksbuild.9`, and `v1.8.7-eksbuild.8` versions of the EKS add-on for CoreDNS expose the port that CoreDNS published metrics to, in the `kube-dns` service. This makes it easier to include the CoreDNS metrics in your monitoring systems.


[.update,date="2023-11-06"]
=== Amazon EKS CloudWatch Observability Operator add-on
[.update-ulink]
link:eks/latest/userguide/cloudwatch.html[type="documentation"]

Added Amazon EKS CloudWatch Observability Operator page.


[.update,date="2023-10-31"]
=== Capacity Blocks for self-managed P5 instances in US East (Ohio)
[.update-ulink]
link:eks/latest/userguide/capacity-blocks.html[type="documentation"]

In US East (Ohio), you can now use Capacity Blocks for self-managed P5 instances.


[.update,date="2023-10-24"]
=== Clusters support modifying subnets and security groups
[.update-ulink]
link:eks/latest/userguide/network-reqs.html[type="documentation"]

You can update the cluster to change which subnets and security groups the cluster uses. You can update from the {aws-management-console}, the latest version of the {aws} CLI, {aws} CloudFormation, and `eksctl` version `v0.164.0-rc.0` or later. You might need to do this to provide subnets with more available IP addresses to successfully upgrade a cluster version.


[.update,date="2023-10-23"]
=== Cluster role and managed node group role supports customer managed {aws} Identity and Access Management policies
[.update-ulink]
link:eks/latest/userguide/cluster-iam-role.html[type="documentation"]

You can use a custom IAM policy on the cluster role, instead of the link:aws-managed-policy/latest/reference/AmazonEKSClusterPolicy.html[AmazonEKSClusterPolicy,type="documentation"] {aws} managed policy. Also, you can use a custom IAM policy on the node role in a managed node group, instead of the link:aws-managed-policy/latest/reference/AmazonEKSWorkerNodePolicy.html[AmazonEKSWorkerNodePolicy,type="documentation"] {aws} managed policy. Do this to create a policy with the least privilege to meet strict compliance requirements.


[.update,date="2023-10-06"]
=== Fix link to eksctl installation
Fix install link for eksctl after the page was moved.


[.update,date="2023-10-04"]
=== Preview release: Amazon EKS Extended Support for Kubernetes versions
[.update-ulink]
link:eks/latest/userguide/kubernetes-versions.html[type="documentation"]

Extended Kubernetes version support allows you to stay at a specific Kubernetes version for longer than 14 months.


[.update,date="2023-09-29"]
=== Remove references to {aws} App Mesh integration
Amazon EKS integrations with {aws} App Mesh remain for existing customers of App Mesh only.


[.update,date="2023-09-26"]
=== Kubernetes version `1.28`
[.update-ulink]
link:eks/latest/userguide/kubernetes-versions.html#kubernetes-1-28[type="documentation"]

Added Kubernetes version `1.28` support for new clusters and version upgrades.


[.update,date="2023-09-15"]
=== CoreDNS Amazon EKS add-on supports modifying PDB
[.update-ulink]
link:eks/latest/userguide/managing-coredns.html[type="documentation"]

You can modify the `PodDisruptionBudget` of the EKS add-on for CoreDNS in versions `v1.9.3-eksbuild.7` and later and `v1.10.1-eksbuild.4` and later.


[.update,date="2023-09-15"]
=== Existing clusters support Kubernetes network policy enforcement in the Amazon VPC CNI plugin for Kubernetes
[.update-ulink]
link:eks/latest/userguide/cni-network-policy.html[type="documentation"]

You can use Kubernetes _network policy_ in existing clusters with the Amazon VPC CNI plugin for Kubernetes, instead of requiring a third party solution.
You can use Kubernetes _network policy_ in existing clusters with the Amazon VPC CNI plugin for Kubernetes, instead of requiring a third party solution.


[.update,date="2023-09-07"]
=== Amazon EKS support for shared subnets
[.update-ulink]
link:eks/latest/userguide/network-reqs.html#network-requirements-shared[type="documentation"]

New link:eks/latest/userguide/network-reqs.html#network-requirements-shared[Shared subnet requirements and considerations,type="documentation"] for making Amazon EKS clusters in shared subnets.


[.update,date="2023-09-06"]
=== Updates to What is Amazon EKS?
[.update-ulink]
link:eks/latest/userguide/what-is-eks.html[type="documentation"]

Added new link:eks/latest/userguide/common-use-cases.html[Common use cases,type="documentation"] and link:eks/latest/userguide/eks-architecture.html[Architecture,type="documentation"] topics. Refreshed other topics.


[.update,date="2023-08-29"]
=== Kubernetes network policy enforcement in the Amazon VPC CNI plugin for Kubernetes
[.update-ulink]
link:eks/latest/userguide/cni-network-policy.html[type="documentation"]

You can use Kubernetes _network policy_ with the Amazon VPC CNI plugin for Kubernetes, instead of requiring a third party solution.
You can use Kubernetes _network policy_ with the Amazon VPC CNI plugin for Kubernetes, instead of requiring a third party solution.


[.update,date="2023-08-01"]
=== Amazon EKS {aws} Region expansion
Amazon EKS is now available in the Israel (Tel Aviv) (`il-central-1`) {aws} Region.


[.update,date="2023-07-31"]
=== Configurable ephemeral storage for Fargate
[.update-ulink]
link:eks/latest/userguide/fargate-pod-configuration.html#fargate-storage[type="documentation"]

You can increase the total amount of ephemeral storage for each Pod running on Amazon EKS Fargate.


[.update,date="2023-07-26"]
=== Add-on support for Amazon EFS CSI driver
[.update-ulink]
link:eks/latest/userguide/eks-add-ons.html#add-ons-aws-efs-csi-driver[type="documentation"]

You can now use the {aws-management-console}, {aws} CLI, and API to manage the Amazon EFS CSI driver.


[.update,date="2023-07-26"]
=== {aws} managed policy updates - New policy
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-updates[type="documentation"]

Amazon EKS added a new {aws} managed policy.


[.update,date="2023-07-20"]
=== Kubernetes version updates for 1.27, 1.26, 1.25, and 1.24 are now available for local clusters on {aws} Outposts
[.update-ulink]
link:eks/latest/userguide/eks-outposts-platform-versions.html[type="documentation"]

Kubernetes version updates to 1.27.3, 1.26.6, 1.25.11, and 1.24.15 are now available for local clusters on {aws} Outposts


[.update,date="2023-07-06"]
=== IP prefixes support for Windows nodes
[.update-ulink]
link:eks/latest/userguide/cni-increase-ip-addresses.html[type="documentation"]

Assigning IP prefixes to your nodes can enable you to host a significantly higher number of Pods on your nodes than you can when assigning individual secondary IP addresses to your nodes.


[.update,date="2023-06-30"]
=== Amazon FSx for OpenZFS CSI driver
[.update-ulink]
link:eks/latest/userguide/fsx-openzfs-csi.html[type="documentation"]

You can now install the Amazon FSx for OpenZFS CSI driver on Amazon EKS clusters.


[.update,date="2023-06-19"]
=== Pods on Linux nodes in `IPv4` clusters can now communicate with `IPv6` endpoints.
[.update-ulink]
link:eks/latest/userguide/cni-ipv6-egress.html[type="documentation"]

After assigning an IPv6 address to your node, your Pods' `IPv4` address is network address translated to the `IPv6` address of the node that it's running on.


[.update,date="2023-05-30"]
=== Windows managed node groups in {aws} GovCloud (US) Regions
[.update-ulink]
link:eks/latest/userguide/create-managed-node-group.html[type="documentation"]

In the {aws} GovCloud (US) Regions, Amazon EKS managed node groups can now run Windows containers.


[.update,date="2023-05-24"]
=== Kubernetes version `1.27`
[.update-ulink]
link:eks/latest/userguide/kubernetes-versions.html#kubernetes-1-27[type="documentation"]

Added Kubernetes version `1.27` support for new clusters and version upgrades.


[.update,date="2023-04-11"]
=== Kubernetes version `1.26`
[.update-ulink]
link:eks/latest/userguide/kubernetes-versions.html[type="documentation"]

Added Kubernetes version `1.26` support for new clusters and version upgrades.


[.update,date="2023-03-27"]
=== Domainless gMSA
[.update-ulink]
link:eks/latest/userguide/eks-optimized-windows-ami.html#ad-and-gmsa-support[type="documentation"]

You can now use domainless gMSA with Windows Pods.


[.update,date="2023-03-10"]
=== Amazon EKS {aws} Region expansion
Amazon EKS is now available in the Asia Pacific (Melbourne) (`ap-southeast-4`) {aws} Region.


[.update,date="2023-03-03"]
=== Amazon File Cache CSI driver
[.update-ulink]
link:eks/latest/userguide/file-cache-csi.html[type="documentation"]

You can now install the Amazon File Cache CSI driver on Amazon EKS clusters.


[.update,date="2023-03-01"]
=== Kubernetes version 1.25 is now available for local clusters on {aws} Outposts
[.update-ulink]
link:eks/latest/userguide/eks-outposts-local-cluster-create.html[type="documentation"]

You can now create an Amazon EKS local cluster on an Outpost using Kubernetes versions `1.22` – `1.25`.


[.update,date="2023-02-22"]
=== Kubernetes version `1.25`
Added Kubernetes version `1.25` support for new clusters and version upgrades.


[.update,date="2023-02-07"]
=== {aws} managed policy updates - Update to an existing policy
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-updates[type="documentation"]

Amazon EKS updated an existing {aws} managed policy.


[.update,date="2023-02-06"]
=== Amazon EKS {aws} Region expansion
Amazon EKS is now available in the Asia Pacific (Hyderabad) (`ap-south-2`), Europe (Zurich) (`eu-central-2`), and Europe (Spain) (`eu-south-2`) {aws} Regions.


[.update,date="2023-01-17"]
=== Kubernetes versions `1.21` – `1.24` are now available for local clusters on {aws} Outposts.
[.update-ulink]
link:eks/latest/userguide/eks-outposts-local-cluster-create.html[type="documentation"]

You can now create an Amazon EKS local cluster on an Outpost using Kubernetes versions `1.21` – `1.24`. Previously, only version `1.21` was available.


[.update,date="2022-12-16"]
=== Amazon EKS now supports {aws} PrivateLink
[.update-ulink]
link:eks/latest/userguide/vpc-interface-endpoints.html[type="documentation"]

You can use an {aws} PrivateLink to create a private connection between your VPC and Amazon EKS.


[.update,date="2022-12-15"]
=== Managed node group Windows support
[.update-ulink]
link:eks/latest/userguide/managed-node-groups.html[type="documentation"]

You can now use Windows for Amazon EKS managed node groups.


[.update,date="2022-11-28"]
=== Amazon EKS add-ons from independent software vendors are now available in the {aws} Marketplace
[.update-ulink]
link:eks/latest/userguide/eks-add-ons.html[type="documentation"]

You can now browse and subscribe to Amazon EKS add-ons from independent software vendors through the {aws} Marketplace.


[.update,date="2022-11-17"]
=== {aws} managed policy updates - Update to an existing policy
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-updates[type="documentation"]

Amazon EKS updated an existing {aws} managed policy.


[.update,date="2022-11-15"]
=== Kubernetes version `1.24`
Added Kubernetes version `1.24` support for new clusters and version upgrades.


[.update,date="2022-11-03"]
=== Amazon EKS {aws} Region expansion
Amazon EKS is now available in the Middle East (UAE) (`me-central-1`) {aws} Region.


[.update,date="2022-10-24"]
=== {aws} managed policy updates - Update to an existing policy
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-updates[type="documentation"]

Amazon EKS updated an existing {aws} managed policy.


[.update,date="2022-10-20"]
=== {aws} managed policy updates - Update to an existing policy
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-updates[type="documentation"]

Amazon EKS updated an existing {aws} managed policy.


[.update,date="2022-09-19"]
=== Local clusters on {aws} Outposts are now available
[.update-ulink]
link:eks/latest/userguide/eks-outposts-local-cluster-create.html[type="documentation"]

You can now create an Amazon EKS local cluster on an Outpost.


[.update,date="2022-09-08"]
=== Fargate vCPU based quotas
[.update-ulink]
link:eks/latest/userguide/service-quotas.html#service-quotas-eks-fargate[type="documentation"]

Fargate is transitioning from Pod based quotas to vCPU based quotas.


[.update,date="2022-08-31"]
=== {aws} managed policy updates - Update to an existing policy
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-updates[type="documentation"]

Amazon EKS updated an existing {aws} managed policy.


[.update,date="2022-08-24"]
=== {aws} managed policy updates - New policy
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-updates[type="documentation"]

Amazon EKS added a new {aws} managed policy.


[.update,date="2022-08-24"]
=== Cost monitoring
[.update-ulink]
link:eks/latest/userguide/cost-monitoring[type="documentation"]

Amazon EKS now supports Kubecost, which enables you to monitor costs broken down by Kubernetes resources including Pods, nodes, namespaces, and labels.  


[.update,date="2022-08-23"]
=== {aws} managed policy updates - New policy
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-updates[type="documentation"]

Amazon EKS added a new {aws} managed policy.


[.update,date="2022-08-16"]
=== Tag resources for billing
[.update-ulink]
link:eks/latest/userguide/eks-using-tags.html#tag-resources-for-billing[type="documentation"]

Added `aws:eks:cluster-name` generated cost allocation tag support for all clusters.


[.update,date="2022-08-16"]
=== Fargate profile wildcards
[.update-ulink]
link:eks/latest/userguide/fargate-profile.html#fargate-profile-wildcards[type="documentation"]

Added support for Fargate profile wildcards in the selector criteria for namespaces, label keys, and label values.


[.update,date="2022-08-11"]
=== Kubernetes version `1.23`
Added Kubernetes version `1.23` support for new clusters and version upgrades.


[.update,date="2022-05-03"]
=== View Kubernetes resources in the {aws-management-console}
[.update-ulink]
link:eks/latest/userguide/view-kubernetes-resources.html[type="documentation"]

You can now view information about the Kubernetes resources deployed to your cluster using the {aws-management-console}.


[.update,date="2022-05-02"]
=== Amazon EKS {aws} Region expansion
Amazon EKS is now available in the Asia Pacific (Jakarta) (`ap-southeast-3`) {aws} Region.


[.update,date="2022-04-21"]
=== Observability page and ADOT add-on support
[.update-ulink]
link:eks/latest/userguide/eks-observe.html[type="documentation"]

Added Observability page and {aws} Distro for OpenTelemetry (ADOT).


[.update,date="2022-04-04"]
=== {aws} managed policy updates - New policy
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-updates[type="documentation"]

Amazon EKS added a new {aws} managed policy.


[.update,date="2022-04-04"]
=== Kubernetes version `1.22`
Added Kubernetes version `1.22` support for new clusters and version upgrades.


[.update,date="2022-04-01"]
=== Added Fargate Pod patching details  
[.update-ulink]
link:eks/latest/userguide/fargate-pod-patching.html[type="documentation"]

When upgrading Fargate Pods, Amazon EKS first tries to evict Pods based on your Pod disruption budgets. You can create event rules to react to failed evictions before the Pods are deleted.


[.update,date="2022-03-31"]
=== Full release: Add-on support for Amazon EBS CSI driver
[.update-ulink]
link:eks/latest/userguide/ebs-csi.html[type="documentation"]

You can now use the {aws-management-console}, {aws} CLI, and API to manage the Amazon EBS CSI driver.


[.update,date="2022-03-22"]
=== {aws} Outposts content update
[.update-ulink]
link:eks/latest/userguide/outposts.html[type="documentation"]

Instructions to deploy an Amazon EKS cluster on {aws} Outposts.


[.update,date="2022-03-21"]
=== {aws} managed policy updates - Update to an existing policy
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-updates[type="documentation"]

Amazon EKS updated an existing {aws} managed policy.


[.update,date="2022-03-14"]
=== Windows `containerd` support
[.update-ulink]
link:eks/latest/userguide/eks-optimized-windows-ami.html.html[type="documentation"]

You can now select the `containerd` runtime for Windows nodes.


[.update,date="2022-02-25"]
=== Added Amazon EKS Connector considerations to security documentation
[.update-ulink]
link:eks/latest/userguide/connector-considerations.html[type="documentation"]

Describes the shared responsibility model as it relates to connected clusters.


[.update,date="2022-01-06"]
=== Assign `IPv6` addresses to your Pods and services
[.update-ulink]
link:eks/latest/userguide/cni-ipv6.html[type="documentation"]

You can now create a `1.21` or later cluster that assigns `IPv6` addresses to your Pods and services.


[.update,date="2021-12-13"]
=== {aws} managed policy updates - Update to an existing policy
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-updates[type="documentation"]

Amazon EKS updated an existing {aws} managed policy.


[.update,date="2021-12-09"]
=== Preview release: Add-on support for Amazon EBS CSI driver
[.update-ulink]
link:eks/latest/userguide/ebs-csi.html[type="documentation"]

You can now preview using the {aws-management-console}, {aws} CLI, and API to manage the Amazon EBS CSI driver.


[.update,date="2021-11-29"]
=== Karpenter autoscaler support
[.update-ulink]
link:eks/latest/userguide/autoscaling.html#karpenter[type="documentation"]

You can now use the Karpenter open-source project to autoscale your nodes.


[.update,date="2021-11-10"]
=== Fluent Bit Kubernetes filter support in Fargate logging
[.update-ulink]
link:eks/latest/userguide/fargate-logging.html#fargate-logging-kubernetes-filter[type="documentation"]

You can now use the Fluent Bit Kubernetes filter with Fargate logging.


[.update,date="2021-11-09"]
=== Windows support available in the control plane
[.update-ulink]
link:eks/latest/userguide/windows-support.html[type="documentation"]

Windows support is now available in your control plane. You no longer need to enable it in your data plane.


[.update,date="2021-10-28"]
=== Bottlerocket added as an AMI type for managed node groups
[.update-ulink]
link:eks/latest/userguide/eks-optimized-ami-bottlerocket.html[type="documentation"]

Previously, Bottlerocket was only available as a self-managed node option. Now it can be configured as a managed node group, reducing the effort that's required to meet node compliance requirements.


[.update,date="2021-10-25"]
=== DL1 driver support
[.update-ulink]
link:eks/latest/userguide/eks-ami-build-scripts.html[type="documentation"]

Custom Amazon Linux AMIs now support deep learning workloads for Amazon Linux 2. This enablement allows a generic on-premises or cloud baseline configuration.


[.update,date="2021-09-13"]
=== VT1 video support
[.update-ulink]
link:eks/latest/userguide/eks-ami-build-scripts.html[type="documentation"]

Custom Amazon Linux AMIs now support VT1 for some distributions. This enablement advertises Xilinx U30 devices on your Amazon EKS cluster.


[.update,date="2021-09-08"]
=== Amazon EKS Anywhere is now available
[.update-ulink]
link:eks/latest/userguide/eks-deployment-options.html[type="documentation"]

Amazon EKS Anywhere is a new deployment option for Amazon EKS that you can use to create and operate Kubernetes clusters on-premises.


[.update,date="2021-09-08"]
=== Amazon EKS Connector is now available
[.update-ulink]
link:eks/latest/userguide/eks-connector.html[type="documentation"]

You can use Amazon EKS Connector to register and connect any conformant Kubernetes cluster to {aws} and visualize it in the Amazon EKS console.


[.update,date="2021-09-02"]
=== Amazon FSx for NetApp ONTAP CSI driver
[.update-ulink]
link:eks/latest/userguide/fsx-ontap.html[type="documentation"]

Added topic that summarizes the Amazon FSx for NetApp ONTAP CSI driver and gives links to other references.


[.update,date="2021-08-30"]
=== Managed node groups now auto-calculates the Amazon EKS recommended maximum Pods for nodes
[.update-ulink]
link:eks/latest/userguide/cni-increase-ip-addresses.html[type="documentation"]

Managed node groups now auto-calculate the Amazon EKS maximum Pods for nodes that you deploy without a launch template, or with a launch template that you haven't specified an AMI ID in.


[.update,date="2021-08-20"]
=== Remove Amazon EKS management of add-on settings without removing the Amazon EKS add-on software
[.update-ulink]
link:eks/latest/userguide/managing-vpc-cni.html#removing-vpc-cni-eks-add-on[type="documentation"]

You can now remove an Amazon EKS add-on without removing the add-on software from your cluster.


[.update,date="2021-08-02"]
=== Create multi-homed Pods using Multus
[.update-ulink]
link:eks/latest/userguide/pod-multiple-network-interfaces.html[type="documentation"]

You can now add multiple network interfaces to a Pod using Multus.


[.update,date="2021-07-27"]
=== Add more IP addresses to your Linux Amazon EC2 nodes
[.update-ulink]
link:eks/latest/userguide/cni-increase-ip-addresses.html[type="documentation"]

You can now add significantly more IP addresses to your Linux Amazon EC2 nodes. This means that you can run a higher density of Pods on each node.
You can now add significantly more IP addresses to your Linux Amazon EC2 nodes. This means that you can run a higher density of Pods on each node.


[.update,date="2021-07-19"]
=== Kubernetes version `1.21`
Added Kubernetes version `1.21` support.


[.update,date="2021-07-19"]
=== `containerd` runtime bootstrap
[.update-ulink]
link:eks/latest/userguide/eks-optimized-ami.html[type="documentation"]

The Amazon EKS optimized accelerated Amazon Linux Amazon Machine Image (AMI) now contains a bootstrap flag that you can use to enable the `containerd` runtime in Amazon EKS optimized and Bottlerocket AMIs. This flag is available in all supported Kubernetes versions of the AMI.


[.update,date="2021-06-17"]
=== Added managed policies topic
[.update-ulink]
link:eks/latest/userguide/security-iam-awsmanpol.html[type="documentation"]

A list of all Amazon EKS IAM managed policies and changes that were made to them since June 17, 2021.


[.update,date="2021-06-01"]
=== Use security groups for Pods with Fargate
[.update-ulink]
link:eks/latest/userguide/security-groups-for-pods.html[type="documentation"]

You can now use security groups for Pods with Fargate, in addition to using them with Amazon EC2 nodes.


[.update,date="2021-05-19"]
=== Added CoreDNS and `kube-proxy` Amazon EKS add-ons
[.update-ulink]
link:eks/latest/userguide/eks-add-ons.html[type="documentation"]

Amazon EKS can now help you manage the CoreDNS and `kube-proxy` Amazon EKS add-ons for your cluster.


[.update,date="2021-05-18"]
=== Kubernetes version `1.20`
Added Kubernetes version `1.20` support for new clusters and version upgrades.


[.update,date="2021-05-14"]
=== {aws} Load Balancer Controller `2.2.0` released
[.update-ulink]
link:eks/latest/userguide/aws-load-balancer-controller.html[type="documentation"]

You can now use the {aws} Load Balancer Controller to create Elastic Load Balancers using instance or IP targets.


[.update,date="2021-05-11"]
=== Node taints for managed node groups
[.update-ulink]
link:eks/latest/userguide/node-taints-managed-node-groups.html[type="documentation"]

Amazon EKS now supports adding note taints to managed node groups.


[.update,date="2021-02-26"]
=== Secrets encryption for existing clusters
[.update-ulink]
link:eks/latest/userguide/update-cluster.html#enable-kms[type="documentation"]

Amazon EKS now supports adding https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/[secrets encryption] to existing clusters.


[.update,date="2021-02-16"]
=== Kubernetes version `1.19`
Added Kubernetes version `1.19` support for new clusters and version upgrades.


[.update,date="2021-02-12"]
=== Amazon EKS now supports OpenID Connect (OIDC) identity providers as a method to authenticate users to a version `1.16` or later cluster.
[.update-ulink]
link:eks/latest/userguide/authenticate-oidc-identity-provider.html[type="documentation"]

OIDC identity providers can be used with, or as an alternative to {aws} Identity and Access Management (IAM). 


[.update,date="2020-12-01"]
=== Amazon EKS can now manage specific add-ons for your cluster
[.update-ulink]
link:eks/latest/userguide/eks-add-ons.html[type="documentation"]

You can manage add-ons yourself, or allow Amazon EKS to control the launch and version of an add-on through the Amazon EKS API.


[.update,date="2020-12-01"]
=== Deploy Spot Instance types in a managed node group
[.update-ulink]
link:eks/latest/userguide/managed-node-groups.html#managed-node-group-capacity-types[type="documentation"]

You can now deploy multiple Spot or On-Demand Instance types to a managed node group.


[.update,date="2020-12-01"]
=== View node and workload resources in the {aws-management-console}
[.update-ulink]
link:eks/latest/userguide/view-kubernetes-resources.html[type="documentation"]

You can now view details about your managed, self-managed, and Fargate nodes and your deployed Kubernetes workloads in the {aws-management-console}.


[.update,date="2020-10-23"]
=== NLB IP target support
[.update-ulink]
link:eks/latest/userguide/networkg-load-balancing.html#network-load-balancer[type="documentation"]

You can now deploy a Network Load Balancer with IP targets. This means that you can use an NLB to load balance network traffic to Fargate Pods and directly to Pods that are running on Amazon EC2 nodes.


[.update,date="2020-10-23"]
=== Share an ALB across multiple Ingresses
[.update-ulink]
link:eks/latest/userguide/alb-ingress.html[type="documentation"]

You can now share an {aws} Application Load Balancer (ALB) across multiple Kubernetes Ingresses. In the past, you had to deploy a separate ALB for each Ingress.


[.update,date="2020-10-13"]
=== Kubernetes version `1.18`
Added Kubernetes version `1.18` support for new clusters and version upgrades.


[.update,date="2020-09-29"]
=== Specify a custom CIDR block for Kubernetes service IP address assignment.
[.update-ulink]
link:eks/latest/userguide/create-cluster.html[type="documentation"]

You can now specify a custom CIDR block that Kubernetes assigns service IP addresses from.


[.update,date="2020-09-09"]
=== Assign security groups to individual Pods
[.update-ulink]
link:eks/latest/userguide/security-groups-for-pods.html[type="documentation"]

You can now associate different security groups to some of the individual Pods that are running on many Amazon EC2 instance types.


[.update,date="2020-08-31"]
=== Deploy Bottlerocket on your nodes
[.update-ulink]
link:eks/latest/userguide/launch-node-bottlerocket.html[type="documentation"]

You can now deploy nodes that are running link:bottlerocket/[Bottlerocket,type="marketing"].


[.update,date="2020-08-17"]
=== Managed node group launch templates and custom AMI
[.update-ulink]
link:eks/latest/userguide/launch-templates.html[type="documentation"]

You can now deploy a managed node group that uses an Amazon EC2 launch template. The launch template can specify a custom AMI, if you choose.


[.update,date="2020-08-17"]
=== The ability to launch Arm nodes is generally available
[.update-ulink]
link:eks/latest/userguide/eks-optimized-ami.html#arm-ami[type="documentation"]

You can now launch Arm nodes in managed and self-managed node groups.


[.update,date="2020-08-17"]
=== EFS support for {aws} Fargate
[.update-ulink]
link:eks/latest/userguide/efs-csi.html[type="documentation"]

You can now use Amazon EFS with {aws} Fargate.


[.update,date="2020-08-12"]
=== Amazon EKS platform version update
[.update-ulink]
link:eks/latest/userguide/platform-versions.html[type="documentation"]

This is a new platform version with security fixes and enhancements. This includes UDP support for services of type `LoadBalancer` when using Network Load Balancers with Kubernetes version `1.15` or later. For more information, see the https://github.com/kubernetes/kubernetes/pull/92109[Allow UDP for {aws} Network Load Balancer] issue on GitHub.


[.update,date="2020-08-06"]
=== Amazon EKS {aws} Region expansion
Amazon EKS is now available in the Africa (Cape Town) (`af-south-1`) and Europe (Milan) (`eu-south-1`) {aws} Regions.


[.update,date="2020-08-03"]
=== Fargate usage metrics
[.update-ulink]
link:eks/latest/userguide/monitoring-fargate-usage.html[type="documentation"]

{aws} Fargate provides CloudWatch usage metrics that provide visibility into your account's usage of Fargate On-Demand resources.


[.update,date="2020-07-10"]
=== Kubernetes version `1.17`
Added Kubernetes version `1.17` support for new clusters and version upgrades.


[.update,date="2020-06-18"]
=== Create and manage App Mesh resources from within Kubernetes with the App Mesh controller for Kubernetes
[.update-ulink]
link:eks/latest/userguide/mesh-k8s-integration.html[type="documentation"]

You can create and manage App Mesh resources from within Kubernetes. The controller also automatically injects the Envoy proxy and init containers into Pods that you deploy.


[.update,date="2020-06-04"]
=== Amazon EKS now supports Amazon EC2 Inf1 nodes
[.update-ulink]
link:eks/latest/userguide/inferentia-support.html[type="documentation"]

You can add Amazon EC2 Inf1 nodes to your cluster.


[.update,date="2020-05-13"]
=== Amazon EKS {aws} Region expansion
Amazon EKS is now available in the {aws} GovCloud (US-East) (`us-gov-east-1`) and {aws} GovCloud (US-West) (`us-gov-west-1`) {aws} Regions.


[.update,date="2020-05-12"]
=== Kubernetes `1.12` is no longer supported on Amazon EKS
[.update-ulink]
link:eks/latest/userguide/update-cluster.html[type="documentation"]

Kubernetes version `1.12` is no longer supported on Amazon EKS. Update any `1.12` clusters to version `1.13` or later to avoid service interruption.


[.update,date="2020-04-30"]
=== Kubernetes version `1.16`
Added Kubernetes version `1.16` support for new clusters and version upgrades.


[.update,date="2020-04-16"]
=== Added the *AWSServiceRoleForAmazonEKS* service-linked role
[.update-ulink]
link:eks/latest/userguide/using-service-linked-roles-eks.html[type="documentation"]

Added the *AWSServiceRoleForAmazonEKS* service-linked role.


[.update,date="2020-03-10"]
=== Kubernetes version `1.15`
Added Kubernetes version `1.15` support for new clusters and version upgrades.


[.update,date="2020-02-26"]
=== Amazon EKS {aws} Region expansion
Amazon EKS is now available in the Beijing (`cn-north-1`) and Ningxia (`cn-northwest-1`) {aws} Regions.


[.update,date="2019-12-23"]
=== FSx for Lustre CSI driver
[.update-ulink]
link:eks/latest/userguide/fsx-csi.html[type="documentation"]

Added topic for installing the FSx for Lustre CSI driver on Kubernetes `1.14` Amazon EKS clusters.


[.update,date="2019-12-20"]
=== Restrict network access to the public access endpoint of a cluster
[.update-ulink]
link:eks/latest/userguide/cluster-endpoint.html[type="documentation"]

With this update, you can use Amazon EKS to restrict the CIDR ranges that can communicate to the public access endpoint of the Kubernetes API server.


[.update,date="2019-12-13"]
=== Resolve the private access endpoint address for a cluster from outside of a VPC
[.update-ulink]
link:eks/latest/userguide/cluster-endpoint.html[type="documentation"]

With this update, you can use Amazon EKS to resolve the private access endpoint of the Kubernetes API server from outside of a VPC.


[.update,date="2019-12-04"]
=== (Beta) Amazon EC2 A1 Amazon EC2 instance nodes
[.update-ulink]
link:eks/latest/userguide/arm-support.html[type="documentation"]

Launch link:ec2/instance-types/a1/[Amazon EC2 A1,type="marketing"] Amazon EC2 instance nodes that register with your Amazon EKS cluster.


[.update,date="2019-12-03"]
=== Creating a cluster on {aws} Outposts
[.update-ulink]
link:eks/latest/userguide/eks-on-outposts.html[type="documentation"]

Amazon EKS now supports creating clusters on {aws} Outposts.


[.update,date="2019-12-03"]
=== {aws} Fargate on Amazon EKS
[.update-ulink]
link:eks/latest/userguide/fargate.html[type="documentation"]

Amazon EKS Kubernetes clusters now support running Pods on Fargate.


[.update,date="2019-11-21"]
=== Amazon EKS {aws} Region expansion
Amazon EKS is now available in the Canada (Central) (`ca-central-1`) {aws} Region.


[.update,date="2019-11-18"]
=== Managed node groups
[.update-ulink]
link:eks/latest/userguide/managed-node-groups.html[type="documentation"]

Amazon EKS managed node groups automate the provisioning and lifecycle management of nodes (Amazon EC2 instances) for Amazon EKS Kubernetes clusters.


[.update,date="2019-11-06"]
=== Amazon EKS platform version update
[.update-ulink]
link:eks/latest/userguide/platform-versions.html[type="documentation"]

New platform versions to address https://groups.google.com/forum/#!msg/kubernetes-security-announce/jk8polzSUxs/dfq6a-MnCQAJ[CVE-2019-11253].


[.update,date="2019-11-04"]
=== Kubernetes `1.11` is no longer supported on Amazon EKS
[.update-ulink]
link:eks/latest/userguide/update-cluster.html[type="documentation"]

Kubernetes version `1.11` is no longer supported on Amazon EKS. Please update any `1.11` clusters to version `1.12` or higher to avoid service interruption.


[.update,date="2019-10-16"]
=== Amazon EKS {aws} Region expansion
Amazon EKS is now available in the South America (São Paulo) (`sa-east-1`) {aws} Region.


[.update,date="2019-10-07"]
=== Windows support
[.update-ulink]
link:eks/latest/userguide/windows-support.html[type="documentation"]

Amazon EKS clusters running Kubernetes version `1.14` now support Windows workloads.


[.update,date="2019-09-30"]
=== Autoscaling
[.update-ulink]
link:eks/latest/userguide/autoscaling.html[type="documentation"]

Added a chapter to cover some of the different types of Kubernetes autoscaling that are supported on Amazon EKS clusters.


[.update,date="2019-09-28"]
=== Kubernetes Dashboard update
[.update-ulink]
link:eks/latest/userguide/dashboard-tutorial.html[type="documentation"]

Updated topic for installing the Kubernetes Dashboard on Amazon EKS clusters to use the beta `2.0` version.


[.update,date="2019-09-19"]
=== Amazon EFS CSI driver
[.update-ulink]
link:eks/latest/userguide/efs-csi.html[type="documentation"]

Added topic for installing the Amazon EFS CSI driver on Kubernetes `1.14` Amazon EKS clusters.


[.update,date="2019-09-18"]
=== Amazon EC2 Systems Manager parameter for Amazon EKS optimized AMI ID
[.update-ulink]
link:eks/latest/userguide/retrieve-ami-id.html[type="documentation"]

Added topic for retrieving the Amazon EKS optimized AMI ID using an Amazon EC2 Systems Manager parameter. The parameter eliminates the need for you to look up AMI IDs.


[.update,date="2019-09-16"]
=== Amazon EKS resource tagging
[.update-ulink]
link:eks/latest/userguide/eks-using-tags.html[type="documentation"]

You can manage the tagging of your Amazon EKS clusters.


[.update,date="2019-09-09"]
=== Amazon EBS CSI driver
[.update-ulink]
link:eks/latest/userguide/ebs-csi.html[type="documentation"]

Added topic for installing the Amazon EBS CSI driver on Kubernetes `1.14` Amazon EKS clusters.


[.update,date="2019-09-06"]
=== New Amazon EKS optimized AMI patched for `CVE-2019-9512` and `CVE-2019-9514`
[.update-ulink]
link:eks/latest/userguide/eks-optimized-ami.html[type="documentation"]

Amazon EKS has updated the Amazon EKS optimized AMI to address https://groups.google.com/forum/#!topic/kubernetes-security-announce/wlHLHit1BqA[CVE-2019-9512 and CVE-2019-9514].


[.update,date="2019-09-04"]
=== Announcing deprecation of Kubernetes `1.11` in Amazon EKS
[.update-ulink]
link:eks/latest/userguide/kubernetes-versions.html[type="documentation"]

Amazon EKS discontinued support for Kubernetes version `1.11` on November 4, 2019.


[.update,date="2019-09-03"]
=== IAM roles for service accounts
[.update-ulink]
link:eks/latest/userguide/iam-roles-for-service-accounts.html[type="documentation"]

With IAM roles for service accounts on Amazon EKS clusters, you can associate an IAM role with a Kubernetes service account. With this feature, you no longer need to provide extended permissions to the node IAM role. This way, Pods on that node can call {aws} APIs.


[.update,date="2019-09-03"]
=== Kubernetes version `1.14`
Added Kubernetes version `1.14` support for new clusters and version upgrades.


[.update,date="2019-08-29"]
=== Amazon EKS {aws} Region expansion
Amazon EKS is now available in the Middle East (Bahrain) (`me-south-1`) {aws} Region.


[.update,date="2019-08-28"]
=== Amazon EKS platform version update
[.update-ulink]
link:eks/latest/userguide/platform-versions.html[type="documentation"]

New platform versions to address https://groups.google.com/forum/#!topic/kubernetes-security-announce/wlHLHit1BqA[CVE-2019-9512 and CVE-2019-9514].


[.update,date="2019-08-05"]
=== Amazon EKS platform version update
[.update-ulink]
link:eks/latest/userguide/platform-versions.html[type="documentation"]

New platform versions to address https://groups.google.com/forum/#!topic/kubernetes-security-announce/vUtEcSEY6SM[CVE-2019-11247 and CVE-2019-11249].


[.update,date="2019-07-31"]
=== Amazon EKS Region expansion
Amazon EKS is now available in the Asia Pacific (Hong Kong) (`ap-east-1`) {aws} Region.


[.update,date="2019-07-30"]
=== Kubernetes `1.10` no longer supported on Amazon EKS
[.update-ulink]
link:eks/latest/userguide/update-cluster.html[type="documentation"]

Kubernetes version `1.10` is no longer supported on Amazon EKS. Update any `1.10` clusters to version `1.11` or higher to avoid service interruption.


[.update,date="2019-07-11"]
=== Added topic on ALB ingress controller
[.update-ulink]
link:eks/latest/userguide/alb-ingress.html[type="documentation"]

The {aws} ALB Ingress Controller for Kubernetes is a controller that causes an ALB to be created when ingress resources are created.


[.update,date="2019-07-03"]
=== New Amazon EKS optimized AMI
[.update-ulink]
link:eks/latest/userguide/eks-optimized-ami.html[type="documentation"]

Removing unnecessary `kubectl` binary from AMIs.


[.update,date="2019-06-18"]
=== Kubernetes version `1.13`
Added Kubernetes version `1.13` support for new clusters and version upgrades.


[.update,date="2019-06-17"]
=== New Amazon EKS optimized AMI patched for `{aws}-2019-005`
[.update-ulink]
link:eks/latest/userguide/eks-optimized-ami.html[type="documentation"]

Amazon EKS has updated the Amazon EKS optimized AMI to address the vulnerabilities that are described in link:security/security-bulletins/{aws}-2019-005/[{aws}-2019-005,type="marketing"].


[.update,date="2019-05-21"]
=== Amazon EKS platform version update
[.update-ulink]
link:eks/latest/userguide/platform-versions.html[type="documentation"]

New platform version for Kubernetes `1.11` and `1.10` clusters to support custom DNS names in the `kubelet` certificate and improve `etcd` performance.


[.update,date="2019-05-21"]
=== Announcing discontinuation of support of Kubernetes `1.10` in Amazon EKS
[.update-ulink]
link:eks/latest/userguide/kubernetes-versions.html[type="documentation"]

Amazon EKS stopped supporting Kubernetes version `1.10` on July 22, 2019.


[.update,date="2019-05-10"]
=== Getting started with `eksctl`
[.update-ulink]
link:eks/latest/userguide/getting-started-eksctl.html[type="documentation"]

This getting started guide describes how you can install all of the required resources to get started with Amazon EKS using `eksctl`. This is a simple command line utility for creating and managing Kubernetes clusters on Amazon EKS.


[.update,date="2019-05-10"]
=== {aws} CLI `get-token` command
The `aws eks get-token` command was added to the {aws} CLI. You no longer need to install the {aws} IAM Authenticator for Kubernetes to create client security tokens for cluster API server communication. Upgrade your {aws} CLI installation to the latest version to use this new functionality. For more information, see link:cli/latest/userguide/installing.html[Installing the {aws} Command Line Interface,type="documentation"] in the _{aws} Command Line Interface User Guide_.


[.update,date="2019-05-08"]
=== Amazon EKS platform version update
[.update-ulink]
link:eks/latest/userguide/platform-versions.html[type="documentation"]

New platform version for Kubernetes `1.12` clusters to support custom DNS names in the `kubelet` certificate and improve `etcd` performance. This fixes a bug that caused node `kubelet` daemons to request a new certificate every few seconds.


[.update,date="2019-04-05"]
=== Prometheus tutorial
[.update-ulink]
link:eks/latest/userguide/prometheus.html[type="documentation"]

Added topic for deploying Prometheus to your Amazon EKS cluster.


[.update,date="2019-04-04"]
=== Amazon EKS control plane logging
[.update-ulink]
link:eks/latest/userguide/control-plane-logs.html[type="documentation"]

With this update, you can get audit and diagnostic logs directly from the Amazon EKS control pane. You can use these CloudWatch logs in your account as reference for securing and running clusters.


[.update,date="2019-03-28"]
=== Kubernetes version `1.12`
Added Kubernetes version `1.12` support for new clusters and version upgrades.


[.update,date="2019-03-27"]
=== Added App Mesh getting started guide
[.update-ulink]
link:eks/latest/userguide/mesh-gs-k8s.html[type="documentation"]

Added documentation for getting started with App Mesh and Kubernetes.


[.update,date="2019-03-19"]
=== Amazon EKS API server endpoint private access
[.update-ulink]
link:eks/latest/userguide/cluster-endpoint.html[type="documentation"]

Added documentation for disabling public access for your Amazon EKS cluster's Kubernetes API server endpoint.


[.update,date="2019-03-18"]
=== Added topic for installing the Kubernetes Metrics Server
[.update-ulink]
link:eks/latest/userguide/metrics-server.html[type="documentation"]

The Kubernetes Metrics Server is an aggregator of resource usage data in your cluster.


[.update,date="2019-03-15"]
=== Added list of related open source projects
[.update-ulink]
link:eks/latest/userguide/metrics-server.html[type="documentation"]

These open source projects extend the functionality of Kubernetes clusters running on {aws}, including clusters that are managed by Amazon EKS.


[.update,date="2019-03-11"]
=== Added topic for installing Helm locally
[.update-ulink]
link:eks/latest/userguide/helm.html[type="documentation"]

The `helm` package manager for Kubernetes helps you install and manage applications on your Kubernetes cluster. This topic shows how to install and run the `helm` and `tiller` binaries locally. That way, you can install and manage charts using the Helm CLI on your local system.


[.update,date="2019-03-08"]
=== Amazon EKS platform version update
[.update-ulink]
link:eks/latest/userguide/platform-versions.html[type="documentation"]

New platform version that updates Amazon EKS Kubernetes `1.11` clusters to patch level `1.11.8` to address https://discuss.kubernetes.io/t/kubernetes-security-announcement-v1-11-8-1-12-6-1-13-4-released-to-address-medium-severity-cve-2019-1002100/5147[CVE-2019-1002100].


[.update,date="2019-02-13"]
=== Amazon EKS {aws} Region expansion
Amazon EKS is now available in the Europe (London) (`eu-west-2`), Europe (Paris) (`eu-west-3`), and Asia Pacific (Mumbai) (`ap-south-1`) {aws} Regions.


[.update,date="2019-02-13"]
=== Increased cluster limit
[.update-ulink]
link:eks/latest/userguide/service_limits.html[type="documentation"]

Amazon EKS has increased the number of clusters that you can create in an {aws} Region from 3 to 50.


[.update,date="2019-02-11"]
=== New Amazon EKS optimized AMI patched for `ALAS-2019-1156`
[.update-ulink]
link:eks/latest/userguide/eks-optimized-ami.html[type="documentation"]

Amazon EKS has updated the Amazon EKS optimized AMI to address the vulnerability that's described in https://alas.aws.amazon.com/ALAS-2019-1156.html[ALAS-2019-1156].


[.update,date="2019-01-09"]
=== New Amazon EKS optimized AMI patched for `ALAS2-2019-1141`
[.update-ulink]
link:eks/latest/userguide/eks-optimized-ami.html[type="documentation"]

Amazon EKS has updated the Amazon EKS optimized AMI to address the CVEs that are referenced in https://alas.aws.amazon.com/AL2/ALAS-2019-1141.html[ALAS2-2019-1141].


[.update,date="2019-01-09"]
=== Amazon EKS {aws} Region expansion
Amazon EKS is now available in the Asia Pacific (Seoul) (`ap-northeast-2`) {aws} Region.


[.update,date="2018-12-19"]
=== Amazon EKS region expansion
Amazon EKS is now available in the following additional {aws} Regions: Europe (Frankfurt) (`eu-central-1`), Asia Pacific (Tokyo) (`ap-northeast-1`), Asia Pacific (Singapore) (`ap-southeast-1`), and Asia Pacific (Sydney) (`ap-southeast-2`).


[.update,date="2018-12-12"]
=== Amazon EKS cluster updates
[.update-ulink]
link:eks/latest/userguide/update-cluster.html[type="documentation"]

Added documentation for Amazon EKS link:eks/latest/userguide/update-cluster.html[cluster Kubernetes version updates,type="documentation"] and link:eks/latest/userguide/update-workers.html[node replacement,type="documentation"].


[.update,date="2018-12-11"]
=== Amazon EKS {aws} Region expansion
Amazon EKS is now available in the Europe (Stockholm) (`eu-north-1`) {aws} Region.


[.update,date="2018-12-04"]
=== Amazon EKS platform version update
[.update-ulink]
link:eks/latest/userguide/platform-versions.html[type="documentation"]

New platform version updating Kubernetes to patch level `1.10.11` to address link:security/security-bulletins/{aws}-2018-020/[CVE-2018-1002105,type="marketing"].


[.update,date="2018-11-20"]
=== Added version `1.0.0` support for the ALB ingress controller
[.update-ulink]
https://github.com/kubernetes-sigs/aws-alb-ingress-controller

The ALB ingress controller releases version `1.0.0` with formal support from {aws}.


[.update,date="2018-10-16"]
=== Added support for CNI network configuration
[.update-ulink]
link:eks/latest/userguide/cni-custom-network.html[type="documentation"]

The Amazon VPC CNI plugin for Kubernetes version `1.2.1` now supports custom network configuration for secondary Pod network interfaces.


[.update,date="2018-10-10"]
=== Added support for `MutatingAdmissionWebhook` and `ValidatingAdmissionWebhook`
[.update-ulink]
link:eks/latest/userguide/platform-versions.html[type="documentation"]

Amazon EKS platform version `1.10-eks.2` now supports `MutatingAdmissionWebhook` and `ValidatingAdmissionWebhook` admission controllers.


[.update,date="2018-10-03"]
=== Added partner AMI information
[.update-ulink]
link:eks/latest/userguide/eks-partner-amis.html[type="documentation"]

Canonical has partnered with Amazon EKS to create node AMIs that you can use in your clusters.


[.update,date="2018-09-21"]
=== Added instructions for {aws} CLI `update-kubeconfig` command
[.update-ulink]
link:eks/latest/userguide/create-kubeconfig.html[type="documentation"]

Amazon EKS has added the `update-kubeconfig` to the {aws} CLI to simplify the process of creating a `kubeconfig` file for accessing your cluster.


[.update,date="2018-09-13"]
=== New Amazon EKS optimized AMIs
[.update-ulink]
link:eks/latest/userguide/eks-optimized-ami.html[type="documentation"]

Amazon EKS has updated the Amazon EKS optimized AMIs (with and without GPU support) to provide various security fixes and AMI optimizations.


[.update,date="2018-09-05"]
=== Amazon EKS {aws} Region expansion
Amazon EKS is now available in the Europe (Ireland) (`eu-west-1`) Region.


[.update,date="2018-08-31"]
=== Amazon EKS platform version update
[.update-ulink]
link:eks/latest/userguide/platform-versions.html[type="documentation"]

New platform version with support for Kubernetes https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/[aggregation layer] and the https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/[Horizontal Pod Autoscaler](HPA).


[.update,date="2018-08-22"]
=== New Amazon EKS optimized AMIs and GPU support
[.update-ulink]
link:eks/latest/userguide/eks-optimized-ami.html[type="documentation"]

Amazon EKS has updated the Amazon EKS optimized AMI to use a new {aws} CloudFormation node template and https://github.com/awslabs/amazon-eks-ami/blob/main/templates/al2/runtime/bootstrap.sh[bootstrap script]. In addition, a new link:eks/latest/userguide/eks-optimized-ami.html#gpu-ami[Amazon EKS optimized AMI with GPU support,type="documentation"] is available.


[.update,date="2018-08-14"]
=== New Amazon EKS optimized AMI patched for `ALAS2-2018-1058`
[.update-ulink]
link:eks/latest/userguide/eks-optimized-ami.html[type="documentation"]

Amazon EKS has updated the Amazon EKS optimized AMI to address the CVEs that are referenced in https://alas.aws.amazon.com/AL2/ALAS-2018-1058.html[ALAS2-2018-1058].


[.update,date="2018-07-10"]
=== Amazon EKS optimized AMI build scripts
[.update-ulink]
link:eks/latest/userguide/eks-optimized-ami.html[type="documentation"]

Amazon EKS has open-sourced the build scripts that are used to build the Amazon EKS optimized AMI. These build scripts are now available on GitHub.  


[.update,date="2018-06-05"]
=== Amazon EKS initial release
Initial documentation for service launch

[.level]
== {blank}

[.update-history]
|===
|===
