[.topic]
[#infrastructure-security]
= Infrastructure security in Amazon EKS
:info_titleabbrev: Infrastructure security

include::../attributes.txt[]

include::vpc-interface-endpoints.adoc[leveloffset=+1]

[abstract]
--
Learn how Amazon EKS isolates service traffic.
--

As a managed service, Amazon Elastic Kubernetes Service is protected by {aws} global network security. For information about {aws} security services and how {aws} protects infrastructure, see link:security/[{aws} Cloud Security,type="marketing"]. To design your {aws} environment using the best practices for infrastructure security, see link:wellarchitected/latest/security-pillar/infrastructure-protection.html[Infrastructure Protection,type="documentation"] in _Security Pillar {aws} Well‐Architected Framework_.

You use {aws} published API calls to access Amazon EKS through the network. Clients must support the following:

* Transport Layer Security (TLS). We require TLS 1.2 and recommend TLS 1.3.
* Cipher suites with perfect forward secrecy (PFS) such as DHE (Ephemeral Diffie-Hellman) or ECDHE (Elliptic Curve Ephemeral Diffie-Hellman). Most modern systems such as Java 7 and later support these modes.

Additionally, requests must be signed by using an access key ID and a secret access key that is associated with an IAM principal. Or you can use the link:STS/latest/APIReference/welcome.html[{aws} Security Token Service,type="documentation"] ({aws} STS) to generate temporary security credentials to sign requests.

When you create an Amazon EKS cluster, you specify the VPC subnets for your cluster to use. Amazon EKS requires subnets in at least two Availability Zones. We recommend a VPC with public and private subnets so that [.noloc]`Kubernetes` can create public load balancers in the public subnets that load balance traffic to [.noloc]`Pods` running on nodes that are in private subnets.

For more information about VPC considerations, see <<network-reqs>>.

If you create your VPC and node groups with the {aws} CloudFormation templates provided in the <<getting-started,Get started with Amazon EKS>> walkthrough, then your control plane and node security groups are configured with our recommended settings.

For more information about security group considerations, see <<sec-group-reqs>>. 

When you create a new cluster, Amazon EKS creates an endpoint for the managed [.noloc]`Kubernetes` API server that you use to communicate with your cluster (using [.noloc]`Kubernetes` management tools such as `kubectl`). By default, this API server endpoint is public to the internet, and access to the API server is secured using a combination of {aws} Identity and Access Management (IAM) and native [.noloc]`Kubernetes` https://kubernetes.io/docs/reference/access-authn-authz/rbac/[Role Based Access Control] (RBAC).

You can enable private access to the [.noloc]`Kubernetes` API server so that all communication between your nodes and the API server stays within your VPC. You can limit the IP addresses that can access your API server from the internet, or completely disable internet access to the API server.

For more information about modifying cluster endpoint access, see <<modify-endpoint-access>>.

You can implement [.noloc]`Kubernetes` _network policies_ with the Amazon VPC CNI or third-party tools such as https://docs.tigera.io/calico/latest/about/[Project Calico]. For more information about using the Amazon VPC CNI for network policies, see <<cni-network-policy>>. Project [.noloc]`Calico` is a third party open source project. For more information, see the https://docs.tigera.io/calico/latest/getting-started/kubernetes/managed-public-cloud/eks/[Project Calico documentation].


📝 https://github.com/search?q=repo:awsdocs/amazon-eks-user-guide+&#91;&#91;infrastructure-security,&type=code[Edit this page on GitHub]