[.topic]
[#file-cache-csi]
= Minimize latency with Amazon File Cache
:info_titleabbrev: Amazon File Cache
:keywords: Amazon File Cache CSI driver, storage

include::../attributes.txt[]

[abstract]
--
The Amazon File Cache Container Storage Interface (CSI) driver provides a CSI interface that allows Amazon EKS clusters to manage the life cycle of Amazon file caches.
--

Amazon File Cache is a fully managed, high-speed cache on {aws} that's used to process file data, regardless of where the data is stored. Amazon File Cache automatically loads data into the cache when it's accessed for the first time and releases data when it's not used. For more information, see the link:fsx/latest/FileCacheGuide/what-is.html[Amazon File Cache User Guide,type="documentation"].

The Amazon File Cache Container Storage Interface (CSI) driver provides a CSI interface that allows Amazon EKS clusters to manage the life cycle of Amazon file caches. Note that the Amazon File Cache CSI driver is not compatible with Amazon EKS Hybrid Nodes. To deploy the Amazon File Cache CSI driver to your Amazon EKS cluster, see https://github.com/kubernetes-sigs/aws-file-cache-csi-driver[aws-file-cache-csi-driver] on GitHub.


📝 https://github.com/search?q=repo%3Aawsdocs%2Famazon-eks-user-guide+%5B%23file-cache-csi%5D&type=code[Edit this page on GitHub]