include::../attributes.txt[]

[.topic]
[#s3-csi]
= Access Amazon S3 objects with Mountpoint for Amazon S3 CSI driver
:info_titleabbrev: Mountpoint for Amazon S3

[abstract]
--
Learn about the Amazon S3 Container Storage Interface (CSI) driver, which provides a CSI interface for managing Amazon S3 files and buckets.
--

With the https://github.com/awslabs/mountpoint-s3-csi-driver[Mountpoint for Amazon S3 Container Storage Interface (CSI) driver], your Kubernetes applications can access Amazon S3 objects through a file system interface, achieving high aggregate throughput without changing any application code. Built on https://github.com/awslabs/mountpoint-s3[Mountpoint for Amazon S3], the CSI driver presents an Amazon S3 bucket as a volume that can be accessed by containers in Amazon EKS and self-managed Kubernetes clusters.

[#s3-csi-considerations]
== Considerations

* The Mountpoint for Amazon S3 CSI driver isn't presently compatible with Windows-based container images.
* The Mountpoint for Amazon S3 CSI driver isn't presently compatible with Amazon EKS Hybrid Nodes.
* The Mountpoint for Amazon S3 CSI driver doesn't support {aws} Fargate. However, containers that are running in Amazon EC2 (either with Amazon EKS or a custom Kubernetes installation) are supported.
* The Mountpoint for Amazon S3 CSI driver supports only static provisioning. Dynamic provisioning, or creation of new buckets, isn't supported.
+
NOTE: Static provisioning refers to using an existing Amazon S3 bucket that is specified as the `bucketName` in the `volumeAttributes` in the `PersistentVolume` object. For more information, see https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/examples/kubernetes/static_provisioning/README.md[Static Provisioning] on GitHub.
* Volumes mounted with the Mountpoint for Amazon S3 CSI driver don't support all POSIX file-system features. For details about file-system behavior, see https://github.com/awslabs/mountpoint-s3/blob/main/doc/SEMANTICS.md[Mountpoint for Amazon S3 file system behavior] on GitHub.

For details on deploying the driver, see <<s3-csi-create>>. For details on removing the driver, see <<removing-s3-csi-eks-add-on>>.

include::s3-csi-create.adoc[leveloffset=+1]

include::removing-s3-csi-eks-add-on.adoc[leveloffset=+1]

